# Form implementation generated from reading ui file 'Applicants_Page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
# Author: Wilkeans Bellamy
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt

# ── Shared palette ────────────────────────────────────────────────────────────
_NAVY      = "#0d1b3e"
_ACCENT    = "#5870ff"
_PURPLE    = "#7c5cfc"
_BG        = "#f0f2f5"
_WHITE     = "#ffffff"
_BORDER    = "#e5e7eb"
_TEXT_DARK = "#1a1a2e"
_TEXT_GREY = "#6b7280"
_TEXT_MID  = "#374151"

# ── Status colours ─────────────────────────────────────────────────────────────
STATUS_COLOURS = {
    "New":          ("#15803d", "#dcfce7"),
    "Under Review": ("#1d4ed8", "#dbeafe"),
    "Shortlisted":  ("#d97706", "#fef3c7"),
    "Rejected":     ("#b91c1c", "#fee2e2"),
}

# ── Avatar colour palette (cycled per row) ─────────────────────────────────────
AVATAR_COLOURS = ["#5870ff", "#10b981", "#f59e0b", "#8b5cf6", "#ef4444",
                  "#0ea5e9", "#ec4899", "#14b8a6", "#f97316", "#6366f1"]

# ── Sample applicant data ────────────────────────────────────────────────────
# (num, name, reg_no, institution, course, department, applied_on, status)
SAMPLE_APPLICANTS = [
    (1,  "John Kamau",     "REG/2025/001", "Kenyatta University",   "BSc. Information Tech.", "Information Technology", "22 Jun 2025", "Under Review"),
    (2,  "Grace Njeri",    "REG/2025/002", "Jomo Kenyatta Uni.",    "BCom. Marketing",         "Marketing & Comms",      "21 Jun 2025", "New"),
    (3,  "David Mwangi",   "REG/2025/003", "University of Nairobi", "BSc. Computer Science",  "Information Technology", "20 Jun 2025", "Shortlisted"),
    (4,  "Susan Akinyi",   "REG/2025/004", "Strathmore University", "BSc. Finance",           "Finance & Accounts",     "19 Jun 2025", "Under Review"),
    (5,  "Brian Otieno",   "REG/2025/005", "Kisii University",      "BBA Operations",         "Operations",             "18 Jun 2025", "New"),
    (6,  "Lilian Moraa",   "REG/2025/006", "Egerton University",    "BSc. Procurement",       "Procurement",            "18 Jun 2025", "Under Review"),
    (7,  "Peter Ochieng",  "REG/2025/007", "Maseno University",     "BSc. Information Tech.", "IT Support",             "17 Jun 2025", "Shortlisted"),
    (8,  "Aisha Hassan",   "REG/2025/008", "Technical University",  "BSc. Marketing",         "Marketing & Comms",      "17 Jun 2025", "New"),
    (9,  "Kevin Odhiambo", "REG/2025/009", "KISAT",                 "Diploma in ICT",         "Information Technology", "15 Jun 2025", "Rejected"),
    (10, "Mary Wanjiku",   "REG/2025/010", "Kenyatta University",   "BSc. Actuarial Science", "Finance & Accounts",     "14 Jun 2025", "Under Review"),
]

DEPARTMENTS = [
    "All Departments", "Information Technology", "Marketing & Comms",
    "Finance & Accounts", "Operations", "Procurement",
    "Human Resources", "IT Support", "Others",
]

COURSES = [
    "All Programs", "BSc. Information Technology", "BSc. Computer Science",
    "BCom. Marketing", "BSc. Finance", "BBA Operations",
    "BSc. Procurement", "Diploma in ICT", "BSc. Actuarial Science",
]

STATUSES = ["All Statuses", "New", "Under Review", "Shortlisted", "Rejected"]

# ── Applications Trend (This Month) — line chart data ───────────────────────
TREND_DATA = [
    ("1 Jun", 8), ("7 Jun", 15), ("14 Jun", 22), ("21 Jun", 28), ("22 Jun", 32),
]

# ── Applications by Department — horizontal bar data ─────────────────────────
DEPT_BARS = [
    ("Information Technology", 42, "#3b82f6"),
    ("Marketing & Comms",      24, "#10b981"),
    ("Finance & Accounts",     18, "#f59e0b"),
    ("Operations",             16, "#8b5cf6"),
    ("Procurement",            12, "#06b6d4"),
    ("Human Resources",         7, "#ec4899"),
    ("Others",                  5, "#6b7280"),
]

# ── Applications by Institution — donut data ─────────────────────────────────
INSTITUTION_SLICES = [
    ("Kenyatta University",   36, "#6b7280"),
    ("Jomo Kenyatta Uni.",    24, "#3b82f6"),
    ("University of Nairobi", 18, "#10b981"),
    ("Strathmore University", 12, "#f59e0b"),
    ("Egerton University",    10, "#ef4444"),
    ("Others",                24, "#8b5cf6"),
]

# ── Application Status Distribution — vertical bar data ──────────────────────
STATUS_DIST = [
    ("New",          32, "#10b981"),
    ("Under Review", 48, "#3b82f6"),
    ("Shortlisted",  28, "#f59e0b"),
    ("Rejected",     16, "#ef4444"),
]

# ── Application Overview (right panel) — donut data ──────────────────────────
OVERVIEW_SLICES = [
    ("New",          32, "#10b981"),
    ("Under Review", 48, "#3b82f6"),
    ("Shortlisted",  28, "#f59e0b"),
    ("Rejected",     16, "#ef4444"),
]

# ── Top Programs Applied (right panel) ───────────────────────────────────────
TOP_PROGRAMS = [
    ("BSc. Information Technology", 42, "33.87%"),
    ("BSc. Computer Science",       26, "20.97%"),
    ("BCom. Marketing",             18, "14.52%"),
    ("BSc. Finance",                15, "12.10%"),
    ("Others",                      23, "18.55%"),
]


# ==============================================================================
# STYLE HELPERS
# ==============================================================================
def _card(parent=None) -> QtWidgets.QFrame:
    f = QtWidgets.QFrame(parent)
    f.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
    f.setStyleSheet(f"""
        QFrame {{
            background:{_WHITE};
            border:1px solid {_BORDER};
            border-radius:10px;
        }}
    """)
    return f


def _outline_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_WHITE}; color:{_TEXT_MID};
            border:1px solid {_BORDER}; border-radius:6px;
            padding:0 14px; font-size:12px;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#f9fafb; }}
    """)
    return btn


def _primary_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_ACCENT}; color:{_WHITE}; border:none;
            border-radius:6px; padding:0 16px;
            font-size:12px; font-weight:bold;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#4a60ee; }}
    """)
    return btn


def _link_label(text: str) -> QtWidgets.QLabel:
    lbl = QtWidgets.QLabel(text)
    lbl.setStyleSheet(f"color:{_ACCENT}; font-size:11px; font-weight:600;")
    lbl.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    return lbl


# ==============================================================================
# BADGE
# ==============================================================================
class _Badge(QtWidgets.QLabel):
    def __init__(self, text: str, fg: str, bg: str, parent=None):
        super().__init__(text, parent)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setFixedHeight(22)
        self.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                           QtWidgets.QSizePolicy.Policy.Fixed)
        self.setStyleSheet(f"""
            QLabel {{
                color:{fg}; background:{bg};
                border-radius:10px; padding:0 10px;
                font-size:10px; font-weight:700;
                font-family:'Segoe UI',Arial;
            }}
        """)


# ==============================================================================
# AVATAR CIRCLE
# ==============================================================================
class _AvatarCircle(QtWidgets.QLabel):
    def __init__(self, name: str, colour: str, parent=None):
        parts = name.split()
        initials = (parts[0][0] + parts[-1][0]).upper() if len(parts) > 1 else name[:2].upper()
        super().__init__(initials, parent)
        self.setFixedSize(32, 32)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setStyleSheet(f"""
            QLabel {{
                background-color:{colour};
                color:{_WHITE};
                border-radius:16px;
                font-size:11px;
                font-weight:bold;
                font-family:'Segoe UI',Arial;
            }}
        """)


# ==============================================================================
# STAT CARD
# ==============================================================================
class _StatCard(QtWidgets.QFrame):
    def __init__(self, icon, icon_bg, label, value, sublabel, parent=None):
        super().__init__(parent)
        self.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.setStyleSheet(f"""
            QFrame {{
                background:{_WHITE};
                border:1px solid {_BORDER};
                border-radius:10px;
            }}
        """)
        hl = QtWidgets.QHBoxLayout(self)
        hl.setContentsMargins(16, 14, 16, 14)
        hl.setSpacing(12)

        il = QtWidgets.QLabel(icon)
        il.setFixedSize(46, 46)
        il.setAlignment(Qt.AlignmentFlag.AlignCenter)
        il.setStyleSheet(f"background:{icon_bg};border-radius:12px;font-size:20px;")

        vl = QtWidgets.QVBoxLayout(); vl.setSpacing(2)
        top = QtWidgets.QLabel(label)
        top.setStyleSheet(f"color:{_TEXT_MID};font-size:12px;font-weight:600;")
        val = QtWidgets.QLabel(value)
        val.setStyleSheet(f"color:{_TEXT_DARK};font-size:26px;font-weight:bold;"
                          "font-family:'Segoe UI',Arial;")
        sub = QtWidgets.QLabel(sublabel)
        sub.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
        vl.addWidget(top); vl.addWidget(val); vl.addWidget(sub)
        hl.addWidget(il); hl.addLayout(vl); hl.addStretch()


# ==============================================================================
# DONUT CHART  (reusable — takes any list of (label, value, colour) slices)
# ==============================================================================
class _DonutChart(QtWidgets.QWidget):
    def __init__(self, slices: list, centre_label: str = "Total", parent=None):
        super().__init__(parent)
        self.setMinimumSize(150, 150)
        self._slices = slices
        self._total = sum(s[1] for s in slices) or 1
        self._centre_label = centre_label

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        w, h = self.width(), self.height()
        size = min(w, h) - 14
        x = (w - size) // 2
        y = (h - size) // 2
        rect = QtCore.QRectF(x, y, size, size)
        start = 90 * 16
        for _, val, col in self._slices:
            span = int(round(val / self._total * 360 * 16))
            p.setBrush(QtGui.QColor(col))
            p.setPen(Qt.PenStyle.NoPen)
            p.drawPie(rect, start, -span)
            start -= span
        hole = size * 0.56
        hx = (w - hole) / 2
        hy = (h - hole) / 2
        p.setBrush(QtGui.QColor(_WHITE))
        p.drawEllipse(QtCore.QRectF(hx, hy, hole, hole))
        p.setPen(QtGui.QColor(_TEXT_DARK))
        p.setFont(QtGui.QFont("Segoe UI", 16, QtGui.QFont.Weight.Bold))
        p.drawText(QtCore.QRectF(hx, hy - 6, hole, hole / 2 + 6),
                   Qt.AlignmentFlag.AlignCenter, str(self._total))
        p.setFont(QtGui.QFont("Segoe UI", 8))
        p.setPen(QtGui.QColor(_TEXT_GREY))
        p.drawText(QtCore.QRectF(hx, hy + hole / 2 - 10, hole, 16),
                   Qt.AlignmentFlag.AlignCenter, self._centre_label)
        p.end()


# ==============================================================================
# LINE CHART  (Applications Trend)
# ==============================================================================
class _LineChart(QtWidgets.QWidget):
    def __init__(self, points: list, y_max: int = 40, y_step: int = 10, parent=None):
        super().__init__(parent)
        self.setMinimumSize(240, 150)
        self._points = points
        self._y_max = y_max
        self._y_step = y_step

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        w, h = self.width(), self.height()
        m_left, m_right, m_top, m_bottom = 26, 10, 16, 22
        plot_w = w - m_left - m_right
        plot_h = h - m_top - m_bottom

        # Gridlines + y-axis labels
        steps = self._y_max // self._y_step
        font_sm = QtGui.QFont("Segoe UI", 8)
        p.setFont(font_sm)
        for i in range(steps + 1):
            val = i * self._y_step
            gy = m_top + plot_h - (val / self._y_max) * plot_h
            p.setPen(QtGui.QColor(_BORDER))
            p.drawLine(QtCore.QPointF(m_left, gy), QtCore.QPointF(w - m_right, gy))
            p.setPen(QtGui.QColor(_TEXT_GREY))
            p.drawText(QtCore.QRectF(0, gy - 7, m_left - 5, 14),
                       Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter, str(val))

        n = len(self._points)
        if n < 2:
            p.end()
            return
        step_x = plot_w / (n - 1)

        def xy(i, val):
            gx = m_left + i * step_x
            gy = m_top + plot_h - (val / self._y_max) * plot_h
            return QtCore.QPointF(gx, gy)

        pts = [xy(i, v) for i, (_, v) in enumerate(self._points)]

        # Filled gradient area under the line
        path = QtGui.QPainterPath()
        path.moveTo(pts[0].x(), m_top + plot_h)
        for pt in pts:
            path.lineTo(pt)
        path.lineTo(pts[-1].x(), m_top + plot_h)
        path.closeSubpath()
        grad = QtGui.QLinearGradient(0, m_top, 0, m_top + plot_h)
        grad.setColorAt(0.0, QtGui.QColor(88, 112, 255, 70))
        grad.setColorAt(1.0, QtGui.QColor(88, 112, 255, 0))
        p.setBrush(QtGui.QBrush(grad))
        p.setPen(Qt.PenStyle.NoPen)
        p.drawPath(path)

        # Line itself
        p.setPen(QtGui.QPen(QtGui.QColor(_ACCENT), 2))
        for i in range(len(pts) - 1):
            p.drawLine(pts[i], pts[i + 1])

        # Points + value labels + x-axis labels
        for i, (label, val) in enumerate(self._points):
            pt = pts[i]
            p.setBrush(QtGui.QColor(_WHITE))
            p.setPen(QtGui.QPen(QtGui.QColor(_ACCENT), 2))
            p.drawEllipse(pt, 4, 4)

            p.setPen(QtGui.QColor(_TEXT_DARK))
            p.setFont(QtGui.QFont("Segoe UI", 8, QtGui.QFont.Weight.Bold))
            p.drawText(QtCore.QRectF(pt.x() - 16, pt.y() - 20, 32, 16),
                       Qt.AlignmentFlag.AlignCenter, str(val))

            p.setPen(QtGui.QColor(_TEXT_GREY))
            p.setFont(font_sm)
            p.drawText(QtCore.QRectF(pt.x() - 20, m_top + plot_h + 4, 40, 14),
                       Qt.AlignmentFlag.AlignCenter, label)
        p.end()


# ==============================================================================
# NEW APPLICATION DIALOG
# ==============================================================================
class NewApplicationDialog(QtWidgets.QDialog):
    application_saved = QtCore.pyqtSignal(dict)

    def __init__(self, parent=None, data: dict = None):
        super().__init__(parent)
        self._edit = data is not None
        self.setWindowTitle("Edit Application" if self._edit else "New Application")
        self.setModal(True)
        self.setFixedSize(520, 600)
        self.setStyleSheet(f"""
            QDialog {{ background:{_WHITE}; font-family:'Segoe UI',Arial; }}
            QLabel#hdrTitle {{ color:{_TEXT_DARK}; font-size:15px; font-weight:bold; }}
            QLabel#hdrSub   {{ color:{_TEXT_GREY}; font-size:12px; }}
            QLabel#fldLbl   {{ color:{_TEXT_MID};  font-size:12px; font-weight:600; }}
            QLineEdit, QComboBox {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:7px 10px; font-size:12px;
                color:{_TEXT_DARK}; background:#f9fafb;
            }}
            QLineEdit:focus, QComboBox:focus {{
                border:1.5px solid {_ACCENT}; background:{_WHITE};
            }}
            QPushButton#cancelBtn {{
                background:{_WHITE}; border:1px solid {_BORDER};
                border-radius:6px; padding:8px 22px;
                font-size:12px; color:{_TEXT_MID};
            }}
            QPushButton#cancelBtn:hover {{ background:#f9fafb; }}
            QPushButton#saveBtn {{
                background:{_ACCENT}; border:none; border-radius:6px;
                padding:8px 26px; font-size:12px;
                font-weight:bold; color:{_WHITE};
            }}
            QPushButton#saveBtn:hover {{ background:#4a60ee; }}
            QFrame#div {{ border:none; border-top:1px solid {_BORDER}; }}
        """)

        root = QtWidgets.QVBoxLayout(self)
        root.setContentsMargins(26, 22, 26, 18)
        root.setSpacing(0)

        hhl = QtWidgets.QHBoxLayout()
        ico = QtWidgets.QLabel("🧑‍🎓")
        ico.setFixedSize(40, 40)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:#ede9fe;border-radius:20px;font-size:18px;")
        hvl = QtWidgets.QVBoxLayout(); hvl.setSpacing(2)
        ht = QtWidgets.QLabel("Edit Application" if self._edit else "New Application")
        ht.setObjectName("hdrTitle")
        hs = QtWidgets.QLabel("Update applicant details." if self._edit
                              else "Fill in the details to register a new applicant.")
        hs.setObjectName("hdrSub")
        hvl.addWidget(ht); hvl.addWidget(hs)
        hhl.addWidget(ico); hhl.addSpacing(10)
        hhl.addLayout(hvl); hhl.addStretch()
        root.addLayout(hhl); root.addSpacing(14)

        d0 = QtWidgets.QFrame(); d0.setObjectName("div"); d0.setFixedHeight(1)
        root.addWidget(d0); root.addSpacing(14)

        def lbl(t):
            l = QtWidgets.QLabel(t); l.setObjectName("fldLbl"); return l

        form = QtWidgets.QFormLayout()
        form.setVerticalSpacing(12); form.setHorizontalSpacing(14)
        form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft)

        self.name_edit = QtWidgets.QLineEdit()
        self.name_edit.setPlaceholderText("e.g. John Kamau")
        form.addRow(lbl("Full Name *"), self.name_edit)

        self.email_edit = QtWidgets.QLineEdit()
        self.email_edit.setPlaceholderText("e.g. john.kamau@email.com")
        form.addRow(lbl("Email Address *"), self.email_edit)

        self.phone_edit = QtWidgets.QLineEdit()
        self.phone_edit.setPlaceholderText("e.g. +254 712 345 678")
        form.addRow(lbl("Phone Number"), self.phone_edit)

        self.inst_edit = QtWidgets.QLineEdit()
        self.inst_edit.setPlaceholderText("e.g. Kenyatta University")
        form.addRow(lbl("Institution *"), self.inst_edit)

        self.course_combo = QtWidgets.QComboBox()
        self.course_combo.addItems(COURSES[1:])
        form.addRow(lbl("Course / Program *"), self.course_combo)

        self.dept_combo = QtWidgets.QComboBox()
        self.dept_combo.addItem("— Select Department —")
        self.dept_combo.addItems(DEPARTMENTS[1:])
        form.addRow(lbl("Preferred Department *"), self.dept_combo)

        self.status_combo = QtWidgets.QComboBox()
        self.status_combo.addItems(STATUSES[1:])
        form.addRow(lbl("Status"), self.status_combo)

        root.addLayout(form)

        if self._edit and data:
            self.name_edit.setText(data.get("name", ""))
            self.inst_edit.setText(data.get("institution", ""))
            idx = self.course_combo.findText(data.get("course", ""))
            if idx >= 0: self.course_combo.setCurrentIndex(idx)
            idx = self.dept_combo.findText(data.get("department", ""))
            if idx >= 0: self.dept_combo.setCurrentIndex(idx)
            idx = self.status_combo.findText(data.get("status", ""))
            if idx >= 0: self.status_combo.setCurrentIndex(idx)

        root.addStretch()

        self.err_lbl = QtWidgets.QLabel("")
        self.err_lbl.setStyleSheet("color:#b91c1c;font-size:11px;")
        self.err_lbl.setVisible(False)
        root.addWidget(self.err_lbl); root.addSpacing(8)

        d1 = QtWidgets.QFrame(); d1.setObjectName("div"); d1.setFixedHeight(1)
        root.addWidget(d1); root.addSpacing(12)

        bhl = QtWidgets.QHBoxLayout(); bhl.addStretch()
        cb = QtWidgets.QPushButton("Cancel"); cb.setObjectName("cancelBtn")
        cb.setFixedHeight(36)
        cb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        cb.clicked.connect(self.reject)
        sb = QtWidgets.QPushButton(
            "💾  Save Changes" if self._edit else "✚  Register Applicant")
        sb.setObjectName("saveBtn"); sb.setFixedHeight(36)
        sb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        sb.clicked.connect(self._on_save)
        bhl.addWidget(cb); bhl.addSpacing(8); bhl.addWidget(sb)
        root.addLayout(bhl)

    def _on_save(self):
        name = self.name_edit.text().strip()
        email = self.email_edit.text().strip()
        inst = self.inst_edit.text().strip()
        dept = self.dept_combo.currentText()
        errs = []
        if not name: errs.append("Full Name is required.")
        if not email or "@" not in email: errs.append("A valid Email is required.")
        if not inst: errs.append("Institution is required.")
        if dept.startswith("—"): errs.append("Select a Department.")
        if errs:
            self.err_lbl.setText("⚠  " + "  •  ".join(errs))
            self.err_lbl.setVisible(True)
            return
        self.err_lbl.setVisible(False)
        self.application_saved.emit({
            "name": name, "email": email, "phone": self.phone_edit.text().strip(),
            "institution": inst, "course": self.course_combo.currentText(),
            "department": dept, "status": self.status_combo.currentText(),
        })
        self.accept()


# ==============================================================================
# APPLICANTS PAGE
# ==============================================================================
class ApplicantsPage(QtWidgets.QWidget):
    """
    Full Applicants page — slots into the Industrial Attachment sub-tab stack
    (or stackedWidget_2 index 0).

    Layout
    ──────
    Left scroll area
      • Page header + breadcrumb
      • 5 stat cards (Total / New / Under Review / Shortlisted / Rejected)
      • Filter row (Status / Department / Course / Date Range / Search / Actions)
      • Applicants List section: table + pagination
      • Bottom analytics row: trend line | dept bars | institution donut | status bars
    Right panel (fixed 280px)
      • Application Overview donut
      • Top Programs Applied
      • Quick Actions
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("Applicants_Page")
        self.setStyleSheet(f"background:{_BG};")
        self._applicants = list(SAMPLE_APPLICANTS)
        self._build_ui()
        self._populate_table()

    # ──────────────────────────────────────────────────────────────────────────
    def _build_ui(self):
        outer = QtWidgets.QHBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0); outer.setSpacing(0)

        # ════════════════════ LEFT SCROLL AREA ═══════════════════════════════
        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        scroll.setStyleSheet("background:transparent;border:none;")

        lc = QtWidgets.QWidget(); lc.setStyleSheet(f"background:{_BG};")
        lv = QtWidgets.QVBoxLayout(lc)
        lv.setContentsMargins(22, 18, 14, 18); lv.setSpacing(14)

        # ── Page header ───────────────────────────────────────────────
        hdr = QtWidgets.QHBoxLayout(); hdr.setSpacing(12)
        ico = QtWidgets.QLabel("👥")
        ico.setFixedSize(52, 52)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:{_PURPLE};border-radius:14px;font-size:22px;")
        tvl = QtWidgets.QVBoxLayout(); tvl.setSpacing(2)
        pg_t = QtWidgets.QLabel("Applicants")
        pg_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:22px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        pg_s = QtWidgets.QLabel("View, search and manage all industrial attachment applicants.")
        pg_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        tvl.addWidget(pg_t); tvl.addWidget(pg_s)
        hdr.addWidget(ico); hdr.addLayout(tvl); hdr.addStretch()

        breadcrumb = QtWidgets.QLabel(
            f'<span style="color:{_TEXT_GREY};">Dashboard &nbsp;›&nbsp; '
            f'Industrial Attachments &nbsp;›&nbsp;</span> '
            f'<span style="color:{_TEXT_DARK};font-weight:600;">Applicants</span>'
        )
        breadcrumb.setStyleSheet("font-size:11px;")
        hdr.addWidget(breadcrumb)
        lv.addLayout(hdr)

        # ── Stat cards ────────────────────────────────────────────────
        cards_hl = QtWidgets.QHBoxLayout(); cards_hl.setSpacing(12)
        for icon, ibg, label, val, sub in [
            ("👥", "#ede9fe", "Total Applicants", "124", "All time"),
            ("📄", "#dcfce7", "New Applications",  "32",  "This month"),
            ("⏳", "#dbeafe", "Under Review",       "48",  "Pending review"),
            ("📅", "#fef3c7", "Shortlisted",        "28",  "Ready for interview"),
            ("❌", "#fee2e2", "Rejected",           "16",  "Not successful"),
        ]:
            cards_hl.addWidget(_StatCard(icon, ibg, label, val, sub))
        lv.addLayout(cards_hl)

        # ── Filter row ────────────────────────────────────────────────
        filter_hl = QtWidgets.QHBoxLayout(); filter_hl.setSpacing(12)

        for combo_lbl, items, attr in [
            ("Application Status", STATUSES,    "_status_combo"),
            ("Department",         DEPARTMENTS, "_dept_combo"),
            ("Course / Program",   COURSES,     "_course_combo"),
        ]:
            combo = QtWidgets.QComboBox()
            combo.addItems(items)
            combo.setFixedHeight(36); combo.setMinimumWidth(150)
            combo.setStyleSheet(f"""
                QComboBox {{
                    border:1px solid {_BORDER}; border-radius:6px;
                    padding:0 10px; font-size:12px;
                    color:{_TEXT_MID}; background:{_WHITE};
                }}
                QComboBox:focus {{ border:1.5px solid {_ACCENT}; }}
                QComboBox::drop-down {{ border:none; width:20px; }}
            """)
            combo.currentIndexChanged.connect(self._apply_filters)
            setattr(self, attr, combo)
            lbl_vl = QtWidgets.QVBoxLayout(); lbl_vl.setSpacing(3)
            ll = QtWidgets.QLabel(combo_lbl)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;font-weight:600;")
            lbl_vl.addWidget(ll); lbl_vl.addWidget(combo)
            filter_hl.addLayout(lbl_vl)

        date_vl = QtWidgets.QVBoxLayout(); date_vl.setSpacing(3)
        dl = QtWidgets.QLabel("Date Range")
        dl.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;font-weight:600;")
        self.date_range_btn = QtWidgets.QPushButton("📅  01 Jan 2025 - 22 Jun 2025")
        self.date_range_btn.setFixedHeight(36)
        self.date_range_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        self.date_range_btn.setStyleSheet(f"""
            QPushButton {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 10px; font-size:12px; text-align:left;
                color:{_TEXT_MID}; background:{_WHITE};
            }}
            QPushButton:hover {{ background:#f9fafb; }}
        """)
        date_vl.addWidget(dl); date_vl.addWidget(self.date_range_btn)
        filter_hl.addLayout(date_vl)

        self.search_edit = QtWidgets.QLineEdit()
        self.search_edit.setPlaceholderText("🔍  Search applicants...")
        self.search_edit.setFixedHeight(36)
        self.search_edit.setMinimumWidth(190)
        self.search_edit.setStyleSheet(f"""
            QLineEdit {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 12px; font-size:12px;
                color:{_TEXT_MID}; background:{_WHITE};
            }}
            QLineEdit:focus {{ border:1.5px solid {_ACCENT}; }}
        """)
        self.search_edit.textChanged.connect(self._apply_filters)
        search_vl = QtWidgets.QVBoxLayout(); search_vl.setSpacing(3)
        search_vl.addSpacing(15)
        search_vl.addWidget(self.search_edit)
        filter_hl.addLayout(search_vl)
        filter_hl.addStretch()

        btn_vl = QtWidgets.QVBoxLayout(); btn_vl.setSpacing(3)
        btn_vl.addSpacing(15)
        btn_row = QtWidgets.QHBoxLayout(); btn_row.setSpacing(8)
        self.filter_btn = _outline_btn("▽  Filter")
        self.export_btn = _outline_btn("↓  Export")
        self.add_btn    = _primary_btn("＋  New Application")
        self.filter_btn.setFixedHeight(36)
        self.export_btn.setFixedHeight(36)
        self.add_btn.setFixedHeight(36)
        self.filter_btn.clicked.connect(self._on_filter_menu)
        self.export_btn.clicked.connect(self._on_export)
        self.add_btn.clicked.connect(self._on_add)
        btn_row.addWidget(self.filter_btn)
        btn_row.addWidget(self.export_btn)
        btn_row.addWidget(self.add_btn)
        btn_vl.addLayout(btn_row)
        filter_hl.addLayout(btn_vl)
        lv.addLayout(filter_hl)

        # ── Section title ─────────────────────────────────────────────
        sec_vl = QtWidgets.QVBoxLayout(); sec_vl.setSpacing(2)
        sec_t = QtWidgets.QLabel("Applicants List")
        sec_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:14px;font-weight:bold;"
                            "font-family:'Segoe UI',Arial;")
        sec_s = QtWidgets.QLabel("View and manage all industrial attachment applicants.")
        sec_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        sec_vl.addWidget(sec_t); sec_vl.addWidget(sec_s)
        lv.addLayout(sec_vl)

        # ── Table card ────────────────────────────────────────────────
        tcard = _card()
        tcvl = QtWidgets.QVBoxLayout(tcard)
        tcvl.setContentsMargins(0, 0, 0, 0); tcvl.setSpacing(0)

        self.table = QtWidgets.QTableWidget()
        self.table.setColumnCount(9)
        self.table.setHorizontalHeaderLabels([
            "#", "Applicant", "Reg. No.", "Institution", "Course / Program",
            "Department", "Applied On", "Status", "Actions"
        ])
        self.table.setShowGrid(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.verticalHeader().setVisible(False)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)

        for i, w in enumerate([30, 170, 100, 160, 160, 150, 90, 100, 90]):
            self.table.setColumnWidth(i, w)
        self.table.horizontalHeader().setSectionResizeMode(
            3, QtWidgets.QHeaderView.ResizeMode.Stretch)

        self.table.setStyleSheet(f"""
            QTableWidget {{
                border:none; background:{_WHITE};
                alternate-background-color:#fafbfc;
                font-size:12px; color:{_TEXT_MID};
                font-family:'Segoe UI',Arial; outline:none;
            }}
            QTableWidget::item {{
                padding:4px 6px; border-bottom:1px solid #f3f4f6;
            }}
            QTableWidget::item:selected {{
                background:#eff6ff; color:{_TEXT_DARK};
            }}
            QHeaderView::section {{
                background:#f9fafb; color:{_TEXT_GREY};
                font-size:10px; font-weight:bold;
                border:none; border-bottom:1px solid {_BORDER}; padding:8px 6px;
            }}
            QScrollBar:vertical {{
                border:none; background:#f0f2f5;
                width:7px; border-radius:3px;
            }}
            QScrollBar::handle:vertical {{
                background:#d1d5db; border-radius:3px;
            }}
        """)
        tcvl.addWidget(self.table)

        # Pagination bar
        pg_bar = QtWidgets.QWidget()
        pg_bar.setFixedHeight(46)
        pg_bar.setStyleSheet(f"""
            QWidget {{
                background:{_WHITE};
                border-top:1px solid {_BORDER};
                border-bottom-left-radius:10px;
                border-bottom-right-radius:10px;
            }}
        """)
        pg_hl = QtWidgets.QHBoxLayout(pg_bar)
        pg_hl.setContentsMargins(14, 0, 14, 0); pg_hl.setSpacing(4)
        self.showing_lbl = QtWidgets.QLabel("Showing 1 to 10 of 124 applicants")
        self.showing_lbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(self.showing_lbl); pg_hl.addStretch()

        for txt, act in [("«", False), ("‹", False), ("1", True), ("2", False),
                         ("3", False), ("4", False), ("5", False), ("…", None),
                         ("13", False), ("›", False), ("»", False)]:
            if act is None:
                dots = QtWidgets.QLabel(txt)
                dots.setFixedSize(26, 26)
                dots.setAlignment(Qt.AlignmentFlag.AlignCenter)
                dots.setStyleSheet(f"color:{_TEXT_GREY};font-size:12px;")
                pg_hl.addWidget(dots)
                continue
            b = QtWidgets.QPushButton(txt)
            b.setFixedSize(26, 26)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{"#1e3a6e" if act else _WHITE};
                    color:{"#fff" if act else _TEXT_MID};
                    border:1px solid {"#1e3a6e" if act else _BORDER};
                    border-radius:4px; font-size:11px;
                }}
                QPushButton:hover {{
                    background:{"#254d91" if act else "#f9fafb"};
                }}
            """)
            pg_hl.addWidget(b)

        pg_hl.addSpacing(10)
        pp = QtWidgets.QLabel("10 / page  ▾")
        pp.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(pp)
        tcvl.addWidget(pg_bar)
        lv.addWidget(tcard)

        # ── Bottom analytics row ──────────────────────────────────────
        bot = QtWidgets.QHBoxLayout(); bot.setSpacing(12)

        # Applications Trend (line chart)
        trend = _card()
        tr_vl = QtWidgets.QVBoxLayout(trend)
        tr_vl.setContentsMargins(14, 14, 14, 12); tr_vl.setSpacing(8)
        tr_t = QtWidgets.QLabel("Applications Trend (This Month)")
        tr_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        tr_t.setWordWrap(True)
        tr_vl.addWidget(tr_t)
        tr_vl.addWidget(_LineChart(TREND_DATA), stretch=1)
        tr_link = _link_label("View Full Report")
        tr_vl.addWidget(tr_link, alignment=Qt.AlignmentFlag.AlignLeft)
        bot.addWidget(trend, stretch=3)

        # Applications by Department (horizontal bars)
        dept = _card()
        dp_vl = QtWidgets.QVBoxLayout(dept)
        dp_vl.setContentsMargins(14, 14, 14, 12); dp_vl.setSpacing(6)
        dp_t = QtWidgets.QLabel("Applications by Department")
        dp_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        dp_vl.addWidget(dp_t)
        max_dept = max(v for _, v, _ in DEPT_BARS)
        for name, val, col in DEPT_BARS:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            nl = QtWidgets.QLabel(name)
            nl.setFixedWidth(118)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:9px;")
            bar_bg = QtWidgets.QFrame()
            bar_bg.setFixedHeight(9)
            bar_bg.setStyleSheet("background:#f3f4f6;border-radius:4px;")
            bar_hl = QtWidgets.QHBoxLayout(bar_bg)
            bar_hl.setContentsMargins(0, 0, 0, 0); bar_hl.setSpacing(0)
            fill = QtWidgets.QFrame()
            fill.setFixedHeight(9)
            fill.setStyleSheet(f"background:{col};border-radius:4px;")
            pct = int(val / max_dept * 100)
            bar_hl.addWidget(fill, stretch=pct)
            bar_hl.addStretch(100 - pct)
            vlbl = QtWidgets.QLabel(f"{val} ({val/124*100:.2f}%)")
            vlbl.setFixedWidth(72)
            vlbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            vlbl.setAlignment(Qt.AlignmentFlag.AlignRight)
            row.addWidget(nl); row.addWidget(bar_bg, stretch=1); row.addWidget(vlbl)
            dp_vl.addLayout(row)
        dp_link = _link_label("View Full Report")
        dp_vl.addWidget(dp_link, alignment=Qt.AlignmentFlag.AlignLeft)
        bot.addWidget(dept, stretch=4)

        # Applications by Institution (donut)
        inst = _card()
        in_vl = QtWidgets.QVBoxLayout(inst)
        in_vl.setContentsMargins(14, 14, 14, 12); in_vl.setSpacing(8)
        in_t = QtWidgets.QLabel("Applications by Institution")
        in_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        in_vl.addWidget(in_t)
        in_row = QtWidgets.QHBoxLayout(); in_row.setSpacing(8)
        in_donut = _DonutChart(INSTITUTION_SLICES)
        in_donut.setFixedSize(110, 110)
        in_row.addWidget(in_donut)
        in_leg = QtWidgets.QVBoxLayout(); in_leg.setSpacing(4)
        for name, val, col in INSTITUTION_SLICES:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(4)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{col};font-size:9px;")
            dot.setFixedWidth(10)
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:8px;")
            row.addWidget(dot); row.addWidget(nl); row.addStretch()
            in_leg.addLayout(row)
        in_row.addLayout(in_leg)
        in_vl.addLayout(in_row)
        in_link = _link_label("View Full Report")
        in_vl.addWidget(in_link, alignment=Qt.AlignmentFlag.AlignLeft)
        bot.addWidget(inst, stretch=3)

        # Application Status Distribution (vertical bars)
        dist = _card()
        ds_vl = QtWidgets.QVBoxLayout(dist)
        ds_vl.setContentsMargins(14, 14, 14, 12); ds_vl.setSpacing(8)
        ds_t = QtWidgets.QLabel("Application Status Distribution")
        ds_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        ds_t.setWordWrap(True)
        ds_vl.addWidget(ds_t)

        max_status = max(v for _, v, _ in STATUS_DIST)
        bar_area = QtWidgets.QWidget()
        bar_area.setMinimumHeight(110)
        bar_layout = QtWidgets.QHBoxLayout(bar_area)
        bar_layout.setContentsMargins(6, 0, 6, 0); bar_layout.setSpacing(14)
        bar_layout.setAlignment(Qt.AlignmentFlag.AlignBottom)
        for name, val, col in STATUS_DIST:
            col_vl = QtWidgets.QVBoxLayout()
            col_vl.setSpacing(3)
            col_vl.setAlignment(Qt.AlignmentFlag.AlignBottom)
            cnt = QtWidgets.QLabel(str(val))
            cnt.setAlignment(Qt.AlignmentFlag.AlignCenter)
            cnt.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:bold;")
            bar_h = int((val / max_status) * 80)
            bar = QtWidgets.QFrame()
            bar.setFixedSize(30, bar_h)
            bar.setStyleSheet(f"background:{col};border-radius:4px;")
            cat = QtWidgets.QLabel(name)
            cat.setAlignment(Qt.AlignmentFlag.AlignCenter)
            cat.setStyleSheet(f"color:{_TEXT_GREY};font-size:8px;")
            cat.setWordWrap(True)
            cat.setFixedWidth(50)
            col_vl.addWidget(cnt, alignment=Qt.AlignmentFlag.AlignCenter)
            col_vl.addWidget(bar, alignment=Qt.AlignmentFlag.AlignCenter)
            col_vl.addWidget(cat, alignment=Qt.AlignmentFlag.AlignCenter)
            bar_layout.addLayout(col_vl)
        ds_vl.addWidget(bar_area)
        ds_link = _link_label("View Full Report")
        ds_vl.addWidget(ds_link, alignment=Qt.AlignmentFlag.AlignLeft)
        bot.addWidget(dist, stretch=3)

        lv.addLayout(bot)
        lv.addStretch()
        scroll.setWidget(lc)
        outer.addWidget(scroll, stretch=1)

        # ════════════════════ RIGHT PANEL ════════════════════════════════════
        rp = QtWidgets.QWidget()
        rp.setFixedWidth(280)
        rp.setStyleSheet(f"background:{_BG};border-left:1px solid {_BORDER};")

        rp_scroll = QtWidgets.QScrollArea()
        rp_scroll.setWidgetResizable(True)
        rp_scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        rp_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        rp_scroll.setStyleSheet("background:transparent;border:none;")

        ri = QtWidgets.QWidget(); ri.setStyleSheet(f"background:{_BG};")
        rv = QtWidgets.QVBoxLayout(ri)
        rv.setContentsMargins(12, 16, 12, 16); rv.setSpacing(12)

        # ── Application Overview donut ────────────────────────────────
        ov = _card()
        ov_vl = QtWidgets.QVBoxLayout(ov)
        ov_vl.setContentsMargins(14, 14, 14, 14); ov_vl.setSpacing(10)
        ov_t = QtWidgets.QLabel("Application Overview")
        ov_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        ov_vl.addWidget(ov_t)

        ov_row = QtWidgets.QHBoxLayout(); ov_row.setSpacing(12)
        ov_donut = _DonutChart(OVERVIEW_SLICES)
        ov_donut.setFixedSize(120, 120)
        ov_row.addWidget(ov_donut)

        leg_vl = QtWidgets.QVBoxLayout(); leg_vl.setSpacing(7)
        leg_vl.setAlignment(Qt.AlignmentFlag.AlignVCenter)
        total_ov = sum(v for _, v, _ in OVERVIEW_SLICES)
        for name, val, col in OVERVIEW_SLICES:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{col};font-size:11px;")
            dot.setFixedWidth(12)
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:10px;")
            pct = f"{val} ({val/total_ov*100:.2f}%)"
            vr = QtWidgets.QLabel(pct)
            vr.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            row.addWidget(dot); row.addWidget(nl); row.addStretch(); row.addWidget(vr)
            leg_vl.addLayout(row)
        ov_row.addLayout(leg_vl)
        ov_vl.addLayout(ov_row)
        rv.addWidget(ov)

        # ── Top Programs Applied ──────────────────────────────────────
        tp = _card()
        tp_vl = QtWidgets.QVBoxLayout(tp)
        tp_vl.setContentsMargins(14, 14, 14, 14); tp_vl.setSpacing(10)
        tp_hdr = QtWidgets.QHBoxLayout()
        tp_t = QtWidgets.QLabel("Top Programs Applied")
        tp_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        tp_va = _link_label("View all")
        tp_hdr.addWidget(tp_t); tp_hdr.addStretch(); tp_hdr.addWidget(tp_va)
        tp_vl.addLayout(tp_hdr)

        prog_icons = ["💻", "🖥", "📈", "💰", "📚"]
        prog_colors = ["#eff0ff", "#dcfce7", "#fef3c7", "#dbeafe", "#f3f4f6"]
        for i, (name, val, pct) in enumerate(TOP_PROGRAMS):
            row = QtWidgets.QHBoxLayout(); row.setSpacing(8)
            il = QtWidgets.QLabel(prog_icons[i % len(prog_icons)])
            il.setFixedSize(28, 28)
            il.setAlignment(Qt.AlignmentFlag.AlignCenter)
            il.setStyleSheet(f"background:{prog_colors[i % len(prog_colors)]};"
                             "border-radius:7px;font-size:13px;")
            nl = QtWidgets.QLabel(name)
            nl.setWordWrap(True)
            nl.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:600;")
            vr = QtWidgets.QLabel(f"{val} ({pct})")
            vr.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            vr.setAlignment(Qt.AlignmentFlag.AlignRight)
            row.addWidget(il); row.addWidget(nl, stretch=1); row.addWidget(vr)
            tp_vl.addLayout(row)
        rv.addWidget(tp)

        # ── Quick Actions ─────────────────────────────────────────────
        qa = _card()
        qa_vl = QtWidgets.QVBoxLayout(qa)
        qa_vl.setContentsMargins(14, 14, 14, 10); qa_vl.setSpacing(6)
        qa_t = QtWidgets.QLabel("Quick Actions")
        qa_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        qa_vl.addWidget(qa_t)

        for qico, qlabel, qslot in [
            ("＋", "Register New Application", self._on_add),
            ("📋", "Application Criteria",      self._on_placeholder),
            ("⬇",  "Download Application Form", self._on_placeholder),
            ("📄", "Application Templates",     self._on_placeholder),
            ("📊", "Generate Applicants Report", self._on_placeholder),
        ]:
            btn = QtWidgets.QPushButton(f"  {qico}   {qlabel}")
            btn.setFixedHeight(34)
            btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            btn.setStyleSheet(f"""
                QPushButton {{
                    background:transparent; color:{_ACCENT};
                    border:none; text-align:left;
                    font-size:11px; font-weight:600;
                    font-family:'Segoe UI',Arial;
                    border-bottom:1px solid {_BORDER};
                }}
                QPushButton:hover {{ background:#f9fafb; }}
            """)
            btn.clicked.connect(qslot)
            qa_vl.addWidget(btn)
        rv.addWidget(qa)
        rv.addStretch()

        rp_scroll.setWidget(ri)
        rp_vl = QtWidgets.QVBoxLayout(rp)
        rp_vl.setContentsMargins(0, 0, 0, 0)
        rp_vl.addWidget(rp_scroll)
        outer.addWidget(rp)

    # ──────────────────────────────────────────────────────────────────────────
    # TABLE POPULATION
    # ──────────────────────────────────────────────────────────────────────────
    def _populate_table(self, data: list = None):
        rows = data if data is not None else self._applicants
        self.table.setRowCount(0)
        for i, app in enumerate(rows):
            num, name, reg_no, inst, course, dept, applied_on, status = app
            self.table.insertRow(i)
            self.table.setRowHeight(i, 50)

            self._set_item(i, 0, str(i + 1))

            applicant_w = QtWidgets.QWidget()
            aw_hl = QtWidgets.QHBoxLayout(applicant_w)
            aw_hl.setContentsMargins(6, 0, 6, 0); aw_hl.setSpacing(8)
            colour = AVATAR_COLOURS[i % len(AVATAR_COLOURS)]
            aw_hl.addWidget(_AvatarCircle(name, colour))
            name_lbl = QtWidgets.QLabel(name)
            name_lbl.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:600;")
            aw_hl.addWidget(name_lbl)
            aw_hl.addStretch()
            self.table.setCellWidget(i, 1, applicant_w)

            self._set_item(i, 2, reg_no)
            self._set_item(i, 3, inst)
            self._set_item(i, 4, course)
            self._set_item(i, 5, dept)
            self._set_item(i, 6, applied_on)

            fg, bg = STATUS_COLOURS.get(status, (_TEXT_MID, "#f3f4f6"))
            self.table.setCellWidget(i, 7, self._centre(_Badge(status, fg, bg)))
            self.table.setCellWidget(i, 8, self._action_widget(i))

        count = len(rows)
        self.showing_lbl.setText(
            f"Showing 1 to {min(10, count)} of {count} applicants")

    def _set_item(self, row, col, text):
        it = QtWidgets.QTableWidgetItem(text)
        it.setFlags(it.flags() & ~Qt.ItemFlag.ItemIsEditable)
        self.table.setItem(row, col, it)

    @staticmethod
    def _centre(widget) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.addWidget(widget)
        hl.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        hl.setContentsMargins(6, 0, 0, 0)
        return w

    def _action_widget(self, row: int) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.setContentsMargins(4, 0, 4, 0); hl.setSpacing(4)
        for ico, tip, col, slot in [
            ("👁", "View",   "#64748b", lambda _, r=row: self._on_view(r)),
            ("✏",  "Edit",   "#2563eb", lambda _, r=row: self._on_edit(r)),
            ("🗑",  "Delete", "#dc2626", lambda _, r=row: self._on_delete(r)),
        ]:
            b = QtWidgets.QPushButton(ico)
            b.setFixedSize(24, 24)
            b.setToolTip(tip)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{col}22; color:{col};
                    border:1px solid {col}44;
                    border-radius:5px; font-size:11px;
                }}
                QPushButton:hover {{ background:{col}44; }}
            """)
            b.clicked.connect(slot)
            hl.addWidget(b)
        hl.addStretch()
        return w

    # ──────────────────────────────────────────────────────────────────────────
    # SLOTS
    # ──────────────────────────────────────────────────────────────────────────
    def _apply_filters(self):
        text = self.search_edit.text().lower()
        status_f = self._status_combo.currentText()
        dept_f = self._dept_combo.currentText()
        course_f = self._course_combo.currentText()
        results = []
        for app in self._applicants:
            num, name, reg_no, inst, course, dept, applied_on, status = app
            if status_f != "All Statuses" and status != status_f: continue
            if dept_f != "All Departments" and dept != dept_f: continue
            if course_f != "All Programs" and course != course_f: continue
            if text and not any(text in v.lower() for v in
                                (name, reg_no, inst, course, dept)):
                continue
            results.append(app)
        self._populate_table(results)

    def _on_add(self):
        dlg = NewApplicationDialog(self)
        dlg.application_saved.connect(self._append_application)
        dlg.exec()

    def _append_application(self, data: dict):
        from datetime import date
        new_num = len(self._applicants) + 1
        reg_no = f"REG/2025/{new_num:03d}"
        self._applicants.insert(0, (
            new_num, data["name"], reg_no, data["institution"], data["course"],
            data["department"], date.today().strftime("%d %b %Y"), data["status"]
        ))
        self._apply_filters()
        QtWidgets.QMessageBox.information(
            self, "Application Registered",
            f"✅  '{data['name']}' has been registered successfully."
        )

    def _on_view(self, row: int):
        if row >= len(self._applicants): return
        a = self._applicants[row]
        QtWidgets.QMessageBox.information(
            self, "Applicant Details",
            f"<b>{a[1]}</b><br>Reg. No: {a[2]}<br>Institution: {a[3]}<br>"
            f"Course: {a[4]}<br>Department: {a[5]}<br>Applied On: {a[6]}<br>"
            f"Status: {a[7]}"
        )

    def _on_edit(self, row: int):
        if row >= len(self._applicants): return
        a = self._applicants[row]
        dlg = NewApplicationDialog(self, data={
            "name": a[1], "institution": a[3], "course": a[4],
            "department": a[5], "status": a[7],
        })
        dlg.application_saved.connect(lambda d, r=row: self._save_edit(r, d))
        dlg.exec()

    def _save_edit(self, row: int, data: dict):
        old = self._applicants[row]
        self._applicants[row] = (
            old[0], data["name"], old[2], data["institution"], data["course"],
            data["department"], old[6], data["status"]
        )
        self._apply_filters()

    def _on_delete(self, row: int):
        if row >= len(self._applicants): return
        name = self._applicants[row][1]
        reply = QtWidgets.QMessageBox.question(
            self, "Delete Applicant",
            f"Delete <b>{name}</b>? This cannot be undone.",
            QtWidgets.QMessageBox.StandardButton.Yes |
            QtWidgets.QMessageBox.StandardButton.No,
            QtWidgets.QMessageBox.StandardButton.No,
        )
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            self._applicants.pop(row)
            self._apply_filters()

    def _on_filter_menu(self):
        QtWidgets.QMessageBox.information(
            self, "Advanced Filters",
            "Advanced filter panel will be available in the next sprint."
        )

    def _on_export(self):
        QtWidgets.QMessageBox.information(
            self, "Export",
            "Export functionality will be connected in the next sprint."
        )

    def _on_placeholder(self):
        QtWidgets.QMessageBox.information(
            self, "Coming Soon",
            "This feature will be available in the next sprint."
        )