# Form implementation generated from reading ui file 'AttachmentReports_Page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
# Author: Wilkeans Bellamy
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
#

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt

# ── Shared palette ────────────────────────────────────────────────────────────
_NAVY      = "#0d1b3e"
_ACCENT    = "#5870ff"
_PURPLE    = "#7c5cfc"
_BG        = "#f0f2f5"
_WHITE     = "#ffffff"
_BORDER    = "#e5e7eb"
_TEXT_DARK = "#1a1a2e"
_TEXT_GREY = "#6b7280"
_TEXT_MID  = "#374151"

# ── Status colours ─────────────────────────────────────────────────────────────
STATUS_COLOURS = {
    "Generated": ("#15803d", "#dcfce7"),
    "Scheduled": ("#1d4ed8", "#dbeafe"),
    "Pending":   ("#d97706", "#fef3c7"),
    "Failed":    ("#b91c1c", "#fee2e2"),
}

# ── Report type colours (used across donuts + Recent Reports icons) ─────────
REPORT_TYPE_COLOURS = {
    "Attendance":  "#3b82f6",
    "Evaluations": "#10b981",
    "Clearances":  "#f59e0b",
    "Attachees":   "#8b5cf6",
    "Placements":  "#ef4444",
    "Interviews":  "#06b6d4",
    "General":     "#6366f1",
    "Others":      "#d1d5db",
}

# ── Sample report data ────────────────────────────────────────────────────────
# (num, report_name, report_type, dept_scope, generated_by, generated_on,
#  period_covered, status)
SAMPLE_REPORTS = [
    (1,  "Monthly Attendance Report",       "Attendance",  "All Departments",        "Mary Wanjiku",   "22 Jun 2025 10:30 AM", "May 2025",           "Generated"),
    (2,  "Performance Evaluation Summary",  "Evaluations", "All Departments",        "David Mwangi",   "21 Jun 2025 03:15 PM", "May – Jun 2025",     "Generated"),
    (3,  "Attachment Completion Report",    "General",     "All Departments",        "CEO",            "20 Jun 2025 11:45 AM", "Jan – Jun 2025",     "Generated"),
    (4,  "Clearance Status Report",         "Clearances",  "All Departments",        "Lilian Moraa",   "19 Jun 2025 09:20 AM", "As at 19 Jun 2025",  "Generated"),
    (5,  "Active Attachees Report",         "Attachees",   "All Departments",        "Mary Wanjiku",   "18 Jun 2025 02:10 PM", "As at 18 Jun 2025",  "Generated"),
    (6,  "Interview Outcome Report",        "Interviews",  "All Departments",        "Susan Akinyi",   "16 Jun 2025 04:05 PM", "May – Jun 2025",     "Generated"),
    (7,  "Departmental Placement Report",   "Placements",  "All Departments",        "David Mwangi",   "15 Jun 2025 10:00 AM", "Jan – Jun 2025",     "Scheduled"),
    (8,  "Attendance Summary Report",       "Attendance",  "Information Technology", "Kevin Odhiambo", "14 Jun 2025 01:30 PM", "May 2025",           "Pending"),
    (9,  "Evaluation Overdue Report",       "Evaluations", "All Departments",        "Lilian Moraa",   "12 Jun 2025 09:45 AM", "As at 12 Jun 2025",  "Failed"),
    (10, "Supervisor Feedback Report",      "Evaluations", "All Departments",        "Peter Ochieng",  "10 Jun 2025 04:30 PM", "Apr – May 2025",     "Failed"),
]

REPORT_TYPES = ["All Types", "Attendance", "Evaluations", "Clearances",
                "Attachees", "Interviews", "Placements", "General"]

DEPARTMENTS = [
    "All Departments", "Information Technology", "Marketing & Comms",
    "Finance & Accounts", "Human Resources", "Operations",
    "Procurement", "IT Support",
]

STATUSES = ["All Statuses", "Generated", "Scheduled", "Pending", "Failed"]

# ── Reports by Type — donut data (shared with right panel "Report Types") ────
REPORTS_BY_TYPE = [
    ("Attendance",  16, REPORT_TYPE_COLOURS["Attendance"]),
    ("Evaluations", 14, REPORT_TYPE_COLOURS["Evaluations"]),
    ("Clearances",   8, REPORT_TYPE_COLOURS["Clearances"]),
    ("Attachees",    7, REPORT_TYPE_COLOURS["Attachees"]),
    ("Placements",   6, REPORT_TYPE_COLOURS["Placements"]),
    ("Others",       5, REPORT_TYPE_COLOURS["Others"]),
]

# ── Reports Trend (This Year) — single-line series ───────────────────────────
TREND_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
TREND_VALUES = [6, 9, 8, 11, 12, 10]

# ── Top Reports (By Downloads) — horizontal bar data ─────────────────────────
TOP_REPORTS = [
    ("Monthly Attendance Report",      37, "#3b82f6"),
    ("Performance Evaluation Summary", 31, "#10b981"),
    ("Attachment Completion Report",   28, "#f59e0b"),
    ("Active Attachees Report",        22, "#8b5cf6"),
    ("Clearance Status Report",        19, "#ef4444"),
]

# ── Reports Status Overview — donut data ─────────────────────────────────────
STATUS_OVERVIEW = [
    ("Generated", 42, "#10b981"),
    ("Scheduled",  7, "#3b82f6"),
    ("Pending",    4, "#f59e0b"),
    ("Failed",     3, "#ef4444"),
]

# ── Recent Reports (right panel) — (name, type, date_time) ───────────────────
RECENT_REPORTS = [
    ("Monthly Attendance Report",      "Attendance",  "22 Jun 2025 10:30 AM"),
    ("Performance Evaluation Summary", "Evaluations", "21 Jun 2025 03:15 PM"),
    ("Attachment Completion Report",   "General",     "20 Jun 2025 11:45 AM"),
    ("Clearance Status Report",        "Clearances",  "19 Jun 2025 09:20 AM"),
    ("Active Attachees Report",        "Attachees",   "18 Jun 2025 02:10 PM"),
]


# ==============================================================================
# STYLE HELPERS
# ==============================================================================
def _card(parent=None) -> QtWidgets.QFrame:
    f = QtWidgets.QFrame(parent)
    f.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
    f.setStyleSheet(f"""
        QFrame {{
            background:{_WHITE};
            border:1px solid {_BORDER};
            border-radius:10px;
        }}
    """)
    return f


def _outline_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_WHITE}; color:{_TEXT_MID};
            border:1px solid {_BORDER}; border-radius:6px;
            padding:0 14px; font-size:12px;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#f9fafb; }}
    """)
    return btn


def _primary_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_ACCENT}; color:{_WHITE}; border:none;
            border-radius:6px; padding:0 16px;
            font-size:12px; font-weight:bold;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#4a60ee; }}
    """)
    return btn


def _link_label(text: str) -> QtWidgets.QLabel:
    lbl = QtWidgets.QLabel(text)
    lbl.setStyleSheet(f"color:{_ACCENT}; font-size:11px; font-weight:600;")
    lbl.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    return lbl


# ==============================================================================
# BADGE
# ==============================================================================
class _Badge(QtWidgets.QLabel):
    def __init__(self, text: str, fg: str, bg: str, parent=None):
        super().__init__(text, parent)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setFixedHeight(22)
        self.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                           QtWidgets.QSizePolicy.Policy.Fixed)
        self.setStyleSheet(f"""
            QLabel {{
                color:{fg}; background:{bg};
                border-radius:10px; padding:0 10px;
                font-size:10px; font-weight:700;
                font-family:'Segoe UI',Arial;
            }}
        """)


# ==============================================================================
# STAT CARD
# ==============================================================================
class _StatCard(QtWidgets.QFrame):
    def __init__(self, icon, icon_bg, label, value, sublabel, parent=None):
        super().__init__(parent)
        self.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.setStyleSheet(f"""
            QFrame {{
                background:{_WHITE};
                border:1px solid {_BORDER};
                border-radius:10px;
            }}
        """)
        hl = QtWidgets.QHBoxLayout(self)
        hl.setContentsMargins(16, 14, 16, 14)
        hl.setSpacing(12)

        il = QtWidgets.QLabel(icon)
        il.setFixedSize(46, 46)
        il.setAlignment(Qt.AlignmentFlag.AlignCenter)
        il.setStyleSheet(f"background:{icon_bg};border-radius:12px;font-size:20px;")

        vl = QtWidgets.QVBoxLayout(); vl.setSpacing(2)
        top = QtWidgets.QLabel(label)
        top.setStyleSheet(f"color:{_TEXT_MID};font-size:12px;font-weight:600;")
        val = QtWidgets.QLabel(value)
        val.setStyleSheet(f"color:{_TEXT_DARK};font-size:26px;font-weight:bold;"
                          "font-family:'Segoe UI',Arial;")
        sub = QtWidgets.QLabel(sublabel)
        sub.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
        vl.addWidget(top); vl.addWidget(val); vl.addWidget(sub)
        hl.addWidget(il); hl.addLayout(vl); hl.addStretch()


# ==============================================================================
# DONUT CHART  (reusable — takes any list of (label, value, colour) slices)
# ==============================================================================
class _DonutChart(QtWidgets.QWidget):
    def __init__(self, slices: list, centre_label: str = "Total", parent=None):
        super().__init__(parent)
        self.setMinimumSize(150, 150)
        self._slices = slices
        self._total = sum(s[1] for s in slices) or 1
        self._centre_label = centre_label

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        w, h = self.width(), self.height()
        size = min(w, h) - 14
        x = (w - size) // 2
        y = (h - size) // 2
        rect = QtCore.QRectF(x, y, size, size)
        start = 90 * 16
        for _, val, col in self._slices:
            span = int(round(val / self._total * 360 * 16))
            p.setBrush(QtGui.QColor(col))
            p.setPen(Qt.PenStyle.NoPen)
            p.drawPie(rect, start, -span)
            start -= span
        hole = size * 0.56
        hx = (w - hole) / 2
        hy = (h - hole) / 2
        p.setBrush(QtGui.QColor(_WHITE))
        p.drawEllipse(QtCore.QRectF(hx, hy, hole, hole))
        p.setPen(QtGui.QColor(_TEXT_DARK))
        p.setFont(QtGui.QFont("Segoe UI", 16, QtGui.QFont.Weight.Bold))
        p.drawText(QtCore.QRectF(hx, hy - 6, hole, hole / 2 + 6),
                   Qt.AlignmentFlag.AlignCenter, str(self._total))
        p.setFont(QtGui.QFont("Segoe UI", 8))
        p.setPen(QtGui.QColor(_TEXT_GREY))
        p.drawText(QtCore.QRectF(hx, hy + hole / 2 - 10, hole, 16),
                   Qt.AlignmentFlag.AlignCenter, self._centre_label)
        p.end()


# ==============================================================================
# LINE CHART  (Reports Trend — single series)
# ==============================================================================
class _LineChart(QtWidgets.QWidget):
    def __init__(self, x_labels: list, values: list, colour: str = "#5870ff",
                 y_max: int = 25, y_step: int = 5, parent=None):
        super().__init__(parent)
        self.setMinimumSize(240, 150)
        self._x_labels = x_labels
        self._values = values
        self._colour = colour
        self._y_max = y_max
        self._y_step = y_step

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        w, h = self.width(), self.height()
        m_left, m_right, m_top, m_bottom = 26, 10, 16, 22
        plot_w = w - m_left - m_right
        plot_h = h - m_top - m_bottom

        steps = self._y_max // self._y_step
        font_sm = QtGui.QFont("Segoe UI", 8)
        p.setFont(font_sm)
        for i in range(steps + 1):
            val = i * self._y_step
            gy = m_top + plot_h - (val / self._y_max) * plot_h
            p.setPen(QtGui.QColor(_BORDER))
            p.drawLine(QtCore.QPointF(m_left, gy), QtCore.QPointF(w - m_right, gy))
            p.setPen(QtGui.QColor(_TEXT_GREY))
            p.drawText(QtCore.QRectF(0, gy - 7, m_left - 5, 14),
                       Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter, str(val))

        n = len(self._x_labels)
        if n < 2:
            p.end()
            return
        step_x = plot_w / (n - 1)

        def xy(i, val):
            gx = m_left + i * step_x
            gy = m_top + plot_h - (val / self._y_max) * plot_h
            return QtCore.QPointF(gx, gy)

        pts = [xy(i, v) for i, v in enumerate(self._values)]

        path = QtGui.QPainterPath()
        path.moveTo(pts[0].x(), m_top + plot_h)
        for pt in pts:
            path.lineTo(pt)
        path.lineTo(pts[-1].x(), m_top + plot_h)
        path.closeSubpath()
        c = QtGui.QColor(self._colour)
        grad = QtGui.QLinearGradient(0, m_top, 0, m_top + plot_h)
        grad.setColorAt(0.0, QtGui.QColor(c.red(), c.green(), c.blue(), 70))
        grad.setColorAt(1.0, QtGui.QColor(c.red(), c.green(), c.blue(), 0))
        p.setBrush(QtGui.QBrush(grad))
        p.setPen(Qt.PenStyle.NoPen)
        p.drawPath(path)

        p.setPen(QtGui.QPen(QtGui.QColor(self._colour), 2))
        for i in range(len(pts) - 1):
            p.drawLine(pts[i], pts[i + 1])

        for i, val in enumerate(self._values):
            pt = pts[i]
            p.setBrush(QtGui.QColor(_WHITE))
            p.setPen(QtGui.QPen(QtGui.QColor(self._colour), 2))
            p.drawEllipse(pt, 4, 4)

            p.setPen(QtGui.QColor(_TEXT_DARK))
            p.setFont(QtGui.QFont("Segoe UI", 8, QtGui.QFont.Weight.Bold))
            p.drawText(QtCore.QRectF(pt.x() - 16, pt.y() - 20, 32, 16),
                       Qt.AlignmentFlag.AlignCenter, str(val))

            p.setPen(QtGui.QColor(_TEXT_GREY))
            p.setFont(font_sm)
            p.drawText(QtCore.QRectF(pt.x() - 20, m_top + plot_h + 4, 40, 14),
                       Qt.AlignmentFlag.AlignCenter, self._x_labels[i])
        p.end()


# ==============================================================================
# GENERATE / EDIT REPORT DIALOG
# ==============================================================================
class GenerateReportDialog(QtWidgets.QDialog):
    report_saved = QtCore.pyqtSignal(dict)

    def __init__(self, parent=None, data: dict = None):
        super().__init__(parent)
        self._edit = data is not None
        self.setWindowTitle("Edit Report" if self._edit else "Generate Report")
        self.setModal(True)
        self.setFixedSize(500, 560)
        self.setStyleSheet(f"""
            QDialog {{ background:{_WHITE}; font-family:'Segoe UI',Arial; }}
            QLabel#hdrTitle {{ color:{_TEXT_DARK}; font-size:15px; font-weight:bold; }}
            QLabel#hdrSub   {{ color:{_TEXT_GREY}; font-size:12px; }}
            QLabel#fldLbl   {{ color:{_TEXT_MID};  font-size:12px; font-weight:600; }}
            QLineEdit, QComboBox {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:7px 10px; font-size:12px;
                color:{_TEXT_DARK}; background:#f9fafb;
            }}
            QLineEdit:focus, QComboBox:focus {{
                border:1.5px solid {_ACCENT}; background:{_WHITE};
            }}
            QPushButton#cancelBtn {{
                background:{_WHITE}; border:1px solid {_BORDER};
                border-radius:6px; padding:8px 22px;
                font-size:12px; color:{_TEXT_MID};
            }}
            QPushButton#cancelBtn:hover {{ background:#f9fafb; }}
            QPushButton#saveBtn {{
                background:{_ACCENT}; border:none; border-radius:6px;
                padding:8px 26px; font-size:12px;
                font-weight:bold; color:{_WHITE};
            }}
            QPushButton#saveBtn:hover {{ background:#4a60ee; }}
            QFrame#div {{ border:none; border-top:1px solid {_BORDER}; }}
        """)

        root = QtWidgets.QVBoxLayout(self)
        root.setContentsMargins(26, 22, 26, 18)
        root.setSpacing(0)

        hhl = QtWidgets.QHBoxLayout()
        ico = QtWidgets.QLabel("📄")
        ico.setFixedSize(40, 40)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:#ede9fe;border-radius:20px;font-size:18px;")
        hvl = QtWidgets.QVBoxLayout(); hvl.setSpacing(2)
        ht = QtWidgets.QLabel("Edit Report" if self._edit else "Generate Report")
        ht.setObjectName("hdrTitle")
        hs = QtWidgets.QLabel("Update report details below." if self._edit
                              else "Fill in the details to generate a new report.")
        hs.setObjectName("hdrSub")
        hvl.addWidget(ht); hvl.addWidget(hs)
        hhl.addWidget(ico); hhl.addSpacing(10)
        hhl.addLayout(hvl); hhl.addStretch()
        root.addLayout(hhl); root.addSpacing(14)

        d0 = QtWidgets.QFrame(); d0.setObjectName("div"); d0.setFixedHeight(1)
        root.addWidget(d0); root.addSpacing(14)

        def lbl(t):
            l = QtWidgets.QLabel(t); l.setObjectName("fldLbl"); return l

        form = QtWidgets.QFormLayout()
        form.setVerticalSpacing(12); form.setHorizontalSpacing(14)
        form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft)

        self.name_edit = QtWidgets.QLineEdit()
        self.name_edit.setPlaceholderText("e.g. Monthly Attendance Report")
        form.addRow(lbl("Report Name *"), self.name_edit)

        self.type_combo = QtWidgets.QComboBox()
        self.type_combo.addItems(REPORT_TYPES[1:])
        form.addRow(lbl("Report Type *"), self.type_combo)

        self.dept_combo = QtWidgets.QComboBox()
        self.dept_combo.addItems(DEPARTMENTS)
        form.addRow(lbl("Department / Scope *"), self.dept_combo)

        self.generated_by_edit = QtWidgets.QLineEdit()
        self.generated_by_edit.setPlaceholderText("e.g. CEO")
        form.addRow(lbl("Generated By"), self.generated_by_edit)

        self.period_edit = QtWidgets.QLineEdit()
        self.period_edit.setPlaceholderText("e.g. May 2025")
        form.addRow(lbl("Period Covered"), self.period_edit)

        self.status_combo = QtWidgets.QComboBox()
        self.status_combo.addItems(STATUSES[1:])
        form.addRow(lbl("Status"), self.status_combo)

        root.addLayout(form)

        if self._edit and data:
            self.name_edit.setText(data.get("name", ""))
            idx = self.type_combo.findText(data.get("report_type", ""))
            if idx >= 0: self.type_combo.setCurrentIndex(idx)
            idx = self.dept_combo.findText(data.get("dept_scope", ""))
            if idx >= 0: self.dept_combo.setCurrentIndex(idx)
            self.generated_by_edit.setText(data.get("generated_by", ""))
            self.period_edit.setText(data.get("period_covered", ""))
            idx = self.status_combo.findText(data.get("status", ""))
            if idx >= 0: self.status_combo.setCurrentIndex(idx)

        root.addStretch()

        self.err_lbl = QtWidgets.QLabel("")
        self.err_lbl.setStyleSheet("color:#b91c1c;font-size:11px;")
        self.err_lbl.setVisible(False)
        root.addWidget(self.err_lbl); root.addSpacing(8)

        d1 = QtWidgets.QFrame(); d1.setObjectName("div"); d1.setFixedHeight(1)
        root.addWidget(d1); root.addSpacing(12)

        bhl = QtWidgets.QHBoxLayout(); bhl.addStretch()
        cb = QtWidgets.QPushButton("Cancel"); cb.setObjectName("cancelBtn")
        cb.setFixedHeight(36)
        cb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        cb.clicked.connect(self.reject)
        sb = QtWidgets.QPushButton(
            "💾  Save Changes" if self._edit else "✚  Generate Report")
        sb.setObjectName("saveBtn"); sb.setFixedHeight(36)
        sb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        sb.clicked.connect(self._on_save)
        bhl.addWidget(cb); bhl.addSpacing(8); bhl.addWidget(sb)
        root.addLayout(bhl)

    def _on_save(self):
        name = self.name_edit.text().strip()
        errs = []
        if not name: errs.append("Report Name is required.")
        if errs:
            self.err_lbl.setText("⚠  " + "  •  ".join(errs))
            self.err_lbl.setVisible(True)
            return
        self.err_lbl.setVisible(False)
        self.report_saved.emit({
            "name": name,
            "report_type": self.type_combo.currentText(),
            "dept_scope": self.dept_combo.currentText(),
            "generated_by": self.generated_by_edit.text().strip() or "System Administrator",
            "period_covered": self.period_edit.text().strip() or "-",
            "status": self.status_combo.currentText(),
        })
        self.accept()


# ==============================================================================
# ATTACHMENT REPORTS PAGE
# ==============================================================================
class AttachmentReportsPage(QtWidgets.QWidget):
    """
    Full Attachment Reports page — slots into the Industrial Attachment
    sub-tab stack (or stackedWidget_2 index 4).

    Layout
    ──────
    Left scroll area
      • Page header + breadcrumb
      • 5 stat cards (Total / Generated / Scheduled / Pending / Failed)
      • Filter row (Report Type / Date Range / Department / Status / Search / Actions)
      • Reports List section: table + pagination
      • Bottom analytics row: by-type donut | trend | top downloads | status donut
    Right panel (fixed 280px)
      • Report Types donut
      • Recent Reports
      • Quick Actions
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("AttachmentReports_Page")
        self.setStyleSheet(f"background:{_BG};")
        self._reports = list(SAMPLE_REPORTS)
        self._build_ui()
        self._populate_table()

    # ──────────────────────────────────────────────────────────────────────────
    def _build_ui(self):
        outer = QtWidgets.QHBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0); outer.setSpacing(0)

        # ════════════════════ LEFT SCROLL AREA ═══════════════════════════════
        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        scroll.setStyleSheet("background:transparent;border:none;")

        lc = QtWidgets.QWidget(); lc.setStyleSheet(f"background:{_BG};")
        lv = QtWidgets.QVBoxLayout(lc)
        lv.setContentsMargins(22, 18, 14, 18); lv.setSpacing(14)

        # ── Page header ───────────────────────────────────────────────
        hdr = QtWidgets.QHBoxLayout(); hdr.setSpacing(12)
        ico = QtWidgets.QLabel("📄")
        ico.setFixedSize(52, 52)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:{_PURPLE};border-radius:14px;font-size:22px;")
        tvl = QtWidgets.QVBoxLayout(); tvl.setSpacing(2)
        pg_t = QtWidgets.QLabel("Attachment Reports")
        pg_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:22px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        pg_s = QtWidgets.QLabel("Generate, view and manage industrial attachment reports.")
        pg_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        tvl.addWidget(pg_t); tvl.addWidget(pg_s)
        hdr.addWidget(ico); hdr.addLayout(tvl); hdr.addStretch()

        breadcrumb = QtWidgets.QLabel(
            f'<span style="color:{_TEXT_GREY};">Dashboard &nbsp;›&nbsp; '
            f'Industrial Attachments &nbsp;›&nbsp;</span> '
            f'<span style="color:{_TEXT_DARK};font-weight:600;">Reports</span>'
        )
        breadcrumb.setStyleSheet("font-size:11px;")
        hdr.addWidget(breadcrumb)
        lv.addLayout(hdr)

        # ── Stat cards ────────────────────────────────────────────────
        cards_hl = QtWidgets.QHBoxLayout(); cards_hl.setSpacing(12)
        for icon, ibg, label, val, sub in [
            ("📄", "#ede9fe", "Total Reports", "56", "All time"),
            ("✅", "#dcfce7", "Generated",      "42", "75.00% of total"),
            ("🕐", "#dbeafe", "Scheduled",      "7",  "12.50% of total"),
            ("⏳", "#fef3c7", "Pending",        "4",  "7.14% of total"),
            ("❌", "#fee2e2", "Failed",         "3",  "5.36% of total"),
        ]:
            cards_hl.addWidget(_StatCard(icon, ibg, label, val, sub))
        lv.addLayout(cards_hl)

        # ── Filter row ────────────────────────────────────────────────
        filter_hl = QtWidgets.QHBoxLayout(); filter_hl.setSpacing(12)

        for combo_lbl, items, attr in [
            ("Report Type", REPORT_TYPES, "_type_combo"),
        ]:
            combo = QtWidgets.QComboBox()
            combo.addItems(items)
            combo.setFixedHeight(36); combo.setMinimumWidth(140)
            combo.setStyleSheet(f"""
                QComboBox {{
                    border:1px solid {_BORDER}; border-radius:6px;
                    padding:0 10px; font-size:12px;
                    color:{_TEXT_MID}; background:{_WHITE};
                }}
                QComboBox:focus {{ border:1.5px solid {_ACCENT}; }}
                QComboBox::drop-down {{ border:none; width:20px; }}
            """)
            combo.currentIndexChanged.connect(self._apply_filters)
            setattr(self, attr, combo)
            lbl_vl = QtWidgets.QVBoxLayout(); lbl_vl.setSpacing(3)
            ll = QtWidgets.QLabel(combo_lbl)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;font-weight:600;")
            lbl_vl.addWidget(ll); lbl_vl.addWidget(combo)
            filter_hl.addLayout(lbl_vl)

        date_vl = QtWidgets.QVBoxLayout(); date_vl.setSpacing(3)
        dl = QtWidgets.QLabel("Date Range")
        dl.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;font-weight:600;")
        self.date_range_btn = QtWidgets.QPushButton("📅  01 Jan 2025 - 22 Jun 2025")
        self.date_range_btn.setFixedHeight(36)
        self.date_range_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        self.date_range_btn.setStyleSheet(f"""
            QPushButton {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 10px; font-size:12px; text-align:left;
                color:{_TEXT_MID}; background:{_WHITE};
            }}
            QPushButton:hover {{ background:#f9fafb; }}
        """)
        date_vl.addWidget(dl); date_vl.addWidget(self.date_range_btn)
        filter_hl.addLayout(date_vl)

        for combo_lbl, items, attr in [
            ("Department", DEPARTMENTS, "_dept_combo"),
            ("Status",     STATUSES,    "_status_combo"),
        ]:
            combo = QtWidgets.QComboBox()
            combo.addItems(items)
            combo.setFixedHeight(36); combo.setMinimumWidth(140)
            combo.setStyleSheet(f"""
                QComboBox {{
                    border:1px solid {_BORDER}; border-radius:6px;
                    padding:0 10px; font-size:12px;
                    color:{_TEXT_MID}; background:{_WHITE};
                }}
                QComboBox:focus {{ border:1.5px solid {_ACCENT}; }}
                QComboBox::drop-down {{ border:none; width:20px; }}
            """)
            combo.currentIndexChanged.connect(self._apply_filters)
            setattr(self, attr, combo)
            lbl_vl = QtWidgets.QVBoxLayout(); lbl_vl.setSpacing(3)
            ll = QtWidgets.QLabel(combo_lbl)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;font-weight:600;")
            lbl_vl.addWidget(ll); lbl_vl.addWidget(combo)
            filter_hl.addLayout(lbl_vl)

        self.search_edit = QtWidgets.QLineEdit()
        self.search_edit.setPlaceholderText("🔍  Search reports...")
        self.search_edit.setFixedHeight(36)
        self.search_edit.setMinimumWidth(160)
        self.search_edit.setStyleSheet(f"""
            QLineEdit {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 12px; font-size:12px;
                color:{_TEXT_MID}; background:{_WHITE};
            }}
            QLineEdit:focus {{ border:1.5px solid {_ACCENT}; }}
        """)
        self.search_edit.textChanged.connect(self._apply_filters)
        search_vl = QtWidgets.QVBoxLayout(); search_vl.setSpacing(3)
        search_vl.addSpacing(15)
        search_vl.addWidget(self.search_edit)
        filter_hl.addLayout(search_vl)
        filter_hl.addStretch()

        btn_vl = QtWidgets.QVBoxLayout(); btn_vl.setSpacing(3)
        btn_vl.addSpacing(15)
        btn_row = QtWidgets.QHBoxLayout(); btn_row.setSpacing(8)
        self.filter_btn = _outline_btn("▽  Filter")
        self.export_btn = _outline_btn("↓  Export")
        self.add_btn    = _primary_btn("＋  Generate Report")
        self.filter_btn.setFixedHeight(36)
        self.export_btn.setFixedHeight(36)
        self.add_btn.setFixedHeight(36)
        self.filter_btn.clicked.connect(self._on_filter_menu)
        self.export_btn.clicked.connect(self._on_export)
        self.add_btn.clicked.connect(self._on_add)
        btn_row.addWidget(self.filter_btn)
        btn_row.addWidget(self.export_btn)
        btn_row.addWidget(self.add_btn)
        btn_vl.addLayout(btn_row)
        filter_hl.addLayout(btn_vl)
        lv.addLayout(filter_hl)

        # ── Section title ─────────────────────────────────────────────
        sec_vl = QtWidgets.QVBoxLayout(); sec_vl.setSpacing(2)
        sec_t = QtWidgets.QLabel("Reports List")
        sec_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:14px;font-weight:bold;"
                            "font-family:'Segoe UI',Arial;")
        sec_s = QtWidgets.QLabel("View and manage all industrial attachment reports.")
        sec_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        sec_vl.addWidget(sec_t); sec_vl.addWidget(sec_s)
        lv.addLayout(sec_vl)

        # ── Table card ────────────────────────────────────────────────
        tcard = _card()
        tcvl = QtWidgets.QVBoxLayout(tcard)
        tcvl.setContentsMargins(0, 0, 0, 0); tcvl.setSpacing(0)

        self.table = QtWidgets.QTableWidget()
        self.table.setColumnCount(9)
        self.table.setHorizontalHeaderLabels([
            "#", "Report Name", "Report Type", "Department / Scope",
            "Generated By", "Generated On", "Period Covered", "Status", "Actions"
        ])
        self.table.setShowGrid(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.verticalHeader().setVisible(False)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)

        for i, w in enumerate([28, 190, 100, 150, 110, 145, 130, 90, 90]):
            self.table.setColumnWidth(i, w)
        self.table.horizontalHeader().setSectionResizeMode(
            1, QtWidgets.QHeaderView.ResizeMode.Stretch)

        self.table.setStyleSheet(f"""
            QTableWidget {{
                border:none; background:{_WHITE};
                alternate-background-color:#fafbfc;
                font-size:12px; color:{_TEXT_MID};
                font-family:'Segoe UI',Arial; outline:none;
            }}
            QTableWidget::item {{
                padding:4px 6px; border-bottom:1px solid #f3f4f6;
            }}
            QTableWidget::item:selected {{
                background:#eff6ff; color:{_TEXT_DARK};
            }}
            QHeaderView::section {{
                background:#f9fafb; color:{_TEXT_GREY};
                font-size:10px; font-weight:bold;
                border:none; border-bottom:1px solid {_BORDER}; padding:8px 6px;
            }}
            QScrollBar:vertical {{
                border:none; background:#f0f2f5;
                width:7px; border-radius:3px;
            }}
            QScrollBar::handle:vertical {{
                background:#d1d5db; border-radius:3px;
            }}
        """)
        tcvl.addWidget(self.table)

        # Pagination bar
        pg_bar = QtWidgets.QWidget()
        pg_bar.setFixedHeight(46)
        pg_bar.setStyleSheet(f"""
            QWidget {{
                background:{_WHITE};
                border-top:1px solid {_BORDER};
                border-bottom-left-radius:10px;
                border-bottom-right-radius:10px;
            }}
        """)
        pg_hl = QtWidgets.QHBoxLayout(pg_bar)
        pg_hl.setContentsMargins(14, 0, 14, 0); pg_hl.setSpacing(4)
        self.showing_lbl = QtWidgets.QLabel("Showing 1 to 10 of 56 reports")
        self.showing_lbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(self.showing_lbl); pg_hl.addStretch()

        for txt, act in [("«", False), ("‹", False), ("1", True), ("2", False),
                         ("3", False), ("4", False), ("5", False), ("6", False),
                         ("›", False), ("»", False)]:
            b = QtWidgets.QPushButton(txt)
            b.setFixedSize(26, 26)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{"#1e3a6e" if act else _WHITE};
                    color:{"#fff" if act else _TEXT_MID};
                    border:1px solid {"#1e3a6e" if act else _BORDER};
                    border-radius:4px; font-size:11px;
                }}
                QPushButton:hover {{
                    background:{"#254d91" if act else "#f9fafb"};
                }}
            """)
            pg_hl.addWidget(b)

        pg_hl.addSpacing(10)
        pp = QtWidgets.QLabel("10 / page  ▾")
        pp.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(pp)
        tcvl.addWidget(pg_bar)
        lv.addWidget(tcard)

        # ── Bottom analytics row ──────────────────────────────────────
        bot = QtWidgets.QHBoxLayout(); bot.setSpacing(12)

        # Reports by Type (donut)
        byt = _card()
        bt_vl = QtWidgets.QVBoxLayout(byt)
        bt_vl.setContentsMargins(14, 14, 14, 12); bt_vl.setSpacing(8)
        bt_t = QtWidgets.QLabel("Reports by Type")
        bt_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        bt_vl.addWidget(bt_t)
        bt_row = QtWidgets.QHBoxLayout(); bt_row.setSpacing(10)
        bt_donut = _DonutChart(REPORTS_BY_TYPE)
        bt_donut.setFixedSize(110, 110)
        bt_row.addWidget(bt_donut)
        bt_leg = QtWidgets.QVBoxLayout(); bt_leg.setSpacing(4)
        total_bt = sum(v for _, v, _ in REPORTS_BY_TYPE)
        for name, val, col in REPORTS_BY_TYPE:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(5)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{col};font-size:9px;")
            dot.setFixedWidth(10)
            nl = QtWidgets.QLabel(f"{name}  {val} ({val/total_bt*100:.2f}%)")
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:8px;")
            row.addWidget(dot); row.addWidget(nl); row.addStretch()
            bt_leg.addLayout(row)
        bt_row.addLayout(bt_leg)
        bt_vl.addLayout(bt_row)
        bot.addWidget(byt, stretch=3)

        # Reports Trend (This Year)
        trend = _card()
        tr_vl = QtWidgets.QVBoxLayout(trend)
        tr_vl.setContentsMargins(14, 14, 14, 12); tr_vl.setSpacing(6)
        tr_t = QtWidgets.QLabel("Reports Trend (This Year)")
        tr_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        tr_vl.addWidget(tr_t)
        tr_leg = QtWidgets.QHBoxLayout(); tr_leg.setSpacing(4)
        dot = QtWidgets.QLabel("●")
        dot.setStyleSheet(f"color:{_ACCENT};font-size:9px;")
        nl = QtWidgets.QLabel("Reports Generated")
        nl.setStyleSheet(f"color:{_TEXT_MID};font-size:8px;")
        tr_leg.addWidget(dot); tr_leg.addWidget(nl); tr_leg.addStretch()
        tr_vl.addLayout(tr_leg)
        tr_vl.addWidget(_LineChart(TREND_MONTHS, TREND_VALUES, _ACCENT), stretch=1)
        tr_link = _link_label("View Full Report")
        tr_vl.addWidget(tr_link, alignment=Qt.AlignmentFlag.AlignLeft)
        bot.addWidget(trend, stretch=4)

        # Top Reports (By Downloads)
        topr = _card()
        tp_vl = QtWidgets.QVBoxLayout(topr)
        tp_vl.setContentsMargins(14, 14, 14, 12); tp_vl.setSpacing(8)
        tp_t = QtWidgets.QLabel("Top Reports (By Downloads)")
        tp_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        tp_vl.addWidget(tp_t)
        max_dl = max(v for _, v, _ in TOP_REPORTS)
        for name, val, col in TOP_REPORTS:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            nl = QtWidgets.QLabel(name)
            nl.setWordWrap(True)
            nl.setFixedWidth(120)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:9px;")
            bar_bg = QtWidgets.QFrame()
            bar_bg.setFixedHeight(9)
            bar_bg.setStyleSheet("background:#f3f4f6;border-radius:4px;")
            bar_hl = QtWidgets.QHBoxLayout(bar_bg)
            bar_hl.setContentsMargins(0, 0, 0, 0); bar_hl.setSpacing(0)
            fill = QtWidgets.QFrame()
            fill.setFixedHeight(9)
            fill.setStyleSheet(f"background:{col};border-radius:4px;")
            pct = int(val / max_dl * 100)
            bar_hl.addWidget(fill, stretch=pct)
            bar_hl.addStretch(100 - pct)
            vlbl = QtWidgets.QLabel(str(val))
            vlbl.setFixedWidth(24)
            vlbl.setStyleSheet(f"color:{_TEXT_DARK};font-size:9px;font-weight:bold;")
            vlbl.setAlignment(Qt.AlignmentFlag.AlignRight)
            row.addWidget(nl); row.addWidget(bar_bg, stretch=1); row.addWidget(vlbl)
            tp_vl.addLayout(row)
        tp_link = _link_label("View All Reports")
        tp_vl.addWidget(tp_link, alignment=Qt.AlignmentFlag.AlignLeft)
        bot.addWidget(topr, stretch=4)

        # Reports Status Overview (donut)
        stov = _card()
        sv_vl = QtWidgets.QVBoxLayout(stov)
        sv_vl.setContentsMargins(14, 14, 14, 12); sv_vl.setSpacing(8)
        sv_t = QtWidgets.QLabel("Reports Status Overview")
        sv_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        sv_vl.addWidget(sv_t)
        sv_row = QtWidgets.QHBoxLayout(); sv_row.setSpacing(10)
        sv_donut = _DonutChart(STATUS_OVERVIEW)
        sv_donut.setFixedSize(110, 110)
        sv_row.addWidget(sv_donut)
        sv_leg = QtWidgets.QVBoxLayout(); sv_leg.setSpacing(5)
        total_sv = sum(v for _, v, _ in STATUS_OVERVIEW)
        for name, val, col in STATUS_OVERVIEW:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(5)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{col};font-size:9px;")
            dot.setFixedWidth(10)
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:9px;")
            vr = QtWidgets.QLabel(f"{val} ({val/total_sv*100:.2f}%)")
            vr.setStyleSheet(f"color:{_TEXT_GREY};font-size:8px;")
            row.addWidget(dot); row.addWidget(nl); row.addStretch(); row.addWidget(vr)
            sv_leg.addLayout(row)
        sv_row.addLayout(sv_leg)
        sv_vl.addLayout(sv_row)
        bot.addWidget(stov, stretch=3)

        lv.addLayout(bot)
        lv.addStretch()
        scroll.setWidget(lc)
        outer.addWidget(scroll, stretch=1)

        # ════════════════════ RIGHT PANEL ════════════════════════════════════
        rp = QtWidgets.QWidget()
        rp.setFixedWidth(280)
        rp.setStyleSheet(f"background:{_BG};border-left:1px solid {_BORDER};")

        rp_scroll = QtWidgets.QScrollArea()
        rp_scroll.setWidgetResizable(True)
        rp_scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        rp_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        rp_scroll.setStyleSheet("background:transparent;border:none;")

        ri = QtWidgets.QWidget(); ri.setStyleSheet(f"background:{_BG};")
        rv = QtWidgets.QVBoxLayout(ri)
        rv.setContentsMargins(12, 16, 12, 16); rv.setSpacing(12)

        # ── Report Types donut ────────────────────────────────────────
        rt = _card()
        rt_vl = QtWidgets.QVBoxLayout(rt)
        rt_vl.setContentsMargins(14, 14, 14, 14); rt_vl.setSpacing(10)
        rt_t = QtWidgets.QLabel("Report Types")
        rt_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        rt_vl.addWidget(rt_t)

        rt_row = QtWidgets.QHBoxLayout(); rt_row.setSpacing(12)
        rt_donut = _DonutChart(REPORTS_BY_TYPE)
        rt_donut.setFixedSize(120, 120)
        rt_row.addWidget(rt_donut)

        rt_leg = QtWidgets.QVBoxLayout(); rt_leg.setSpacing(7)
        rt_leg.setAlignment(Qt.AlignmentFlag.AlignVCenter)
        total_rt = sum(v for _, v, _ in REPORTS_BY_TYPE)
        for name, val, col in REPORTS_BY_TYPE:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{col};font-size:11px;")
            dot.setFixedWidth(12)
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:10px;")
            pct = f"{val} ({val/total_rt*100:.2f}%)"
            vr = QtWidgets.QLabel(pct)
            vr.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            row.addWidget(dot); row.addWidget(nl); row.addStretch(); row.addWidget(vr)
            rt_leg.addLayout(row)
        rt_row.addLayout(rt_leg)
        rt_vl.addLayout(rt_row)
        rv.addWidget(rt)

        # ── Recent Reports ────────────────────────────────────────────
        rr = _card()
        rr_vl = QtWidgets.QVBoxLayout(rr)
        rr_vl.setContentsMargins(14, 14, 14, 14); rr_vl.setSpacing(10)
        rr_hdr = QtWidgets.QHBoxLayout()
        rr_t = QtWidgets.QLabel("Recent Reports")
        rr_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        rr_va = _link_label("View All")
        rr_hdr.addWidget(rr_t); rr_hdr.addStretch(); rr_hdr.addWidget(rr_va)
        rr_vl.addLayout(rr_hdr)

        for name, rtype, dt in RECENT_REPORTS:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(8)
            colour = REPORT_TYPE_COLOURS.get(rtype, "#6b7280")
            il = QtWidgets.QLabel("📄")
            il.setFixedSize(30, 30)
            il.setAlignment(Qt.AlignmentFlag.AlignCenter)
            il.setStyleSheet(f"background:{colour}22;border-radius:8px;font-size:13px;")
            info_vl = QtWidgets.QVBoxLayout(); info_vl.setSpacing(1)
            nl = QtWidgets.QLabel(name)
            nl.setWordWrap(True)
            nl.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:600;")
            sub_hl = QtWidgets.QHBoxLayout(); sub_hl.setSpacing(4)
            sub1 = QtWidgets.QLabel(rtype)
            sub1.setStyleSheet(f"color:{colour};font-size:8px;font-weight:600;")
            sub2 = QtWidgets.QLabel(f"•  {dt}")
            sub2.setStyleSheet(f"color:{_TEXT_GREY};font-size:8px;")
            sub_hl.addWidget(sub1); sub_hl.addWidget(sub2); sub_hl.addStretch()
            info_vl.addWidget(nl); info_vl.addLayout(sub_hl)
            row.addWidget(il); row.addLayout(info_vl, 1)
            rr_vl.addLayout(row)
        rv.addWidget(rr)

        # ── Quick Actions ─────────────────────────────────────────────
        qa = _card()
        qa_vl = QtWidgets.QVBoxLayout(qa)
        qa_vl.setContentsMargins(14, 14, 14, 10); qa_vl.setSpacing(6)
        qa_t = QtWidgets.QLabel("Quick Actions")
        qa_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        qa_vl.addWidget(qa_t)

        for qico, qlabel, qslot in [
            ("＋", "Generate New Report", self._on_add),
            ("📄", "Report Templates",    self._on_placeholder),
            ("📅", "Schedule Report",     self._on_placeholder),
            ("🗓", "Reports Calendar",    self._on_placeholder),
            ("⬇",  "Export All Reports",  self._on_export),
            ("⚙",  "Report Settings",     self._on_placeholder),
        ]:
            btn = QtWidgets.QPushButton(f"  {qico}   {qlabel}")
            btn.setFixedHeight(34)
            btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            btn.setStyleSheet(f"""
                QPushButton {{
                    background:transparent; color:{_ACCENT};
                    border:none; text-align:left;
                    font-size:11px; font-weight:600;
                    font-family:'Segoe UI',Arial;
                    border-bottom:1px solid {_BORDER};
                }}
                QPushButton:hover {{ background:#f9fafb; }}
            """)
            btn.clicked.connect(qslot)
            qa_vl.addWidget(btn)
        rv.addWidget(qa)
        rv.addStretch()

        rp_scroll.setWidget(ri)
        rp_vl = QtWidgets.QVBoxLayout(rp)
        rp_vl.setContentsMargins(0, 0, 0, 0)
        rp_vl.addWidget(rp_scroll)
        outer.addWidget(rp)

    # ──────────────────────────────────────────────────────────────────────────
    # TABLE POPULATION
    # ──────────────────────────────────────────────────────────────────────────
    def _populate_table(self, data: list = None):
        rows = data if data is not None else self._reports
        self.table.setRowCount(0)
        for i, rec in enumerate(rows):
            (num, name, rtype, dept_scope, generated_by, generated_on,
             period, status) = rec
            self.table.insertRow(i)
            self.table.setRowHeight(i, 48)

            self._set_item(i, 0, str(i + 1))

            name_item = QtWidgets.QTableWidgetItem(name)
            name_item.setFlags(name_item.flags() & ~Qt.ItemFlag.ItemIsEditable)
            name_item.setFont(QtGui.QFont("Segoe UI", 11, QtGui.QFont.Weight.Bold))
            self.table.setItem(i, 1, name_item)

            self._set_item(i, 2, rtype)
            self._set_item(i, 3, dept_scope)
            self._set_item(i, 4, generated_by)
            self._set_item(i, 5, generated_on)
            self._set_item(i, 6, period)

            fg, bg = STATUS_COLOURS.get(status, (_TEXT_MID, "#f3f4f6"))
            self.table.setCellWidget(i, 7, self._centre(_Badge(status, fg, bg)))
            self.table.setCellWidget(i, 8, self._action_widget(i))

        count = len(rows)
        self.showing_lbl.setText(
            f"Showing 1 to {min(10, count)} of {count} reports")

    def _set_item(self, row, col, text):
        it = QtWidgets.QTableWidgetItem(text)
        it.setFlags(it.flags() & ~Qt.ItemFlag.ItemIsEditable)
        self.table.setItem(row, col, it)

    @staticmethod
    def _centre(widget) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.addWidget(widget)
        hl.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        hl.setContentsMargins(6, 0, 0, 0)
        return w

    def _action_widget(self, row: int) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.setContentsMargins(4, 0, 4, 0); hl.setSpacing(4)
        for ico, tip, col, slot in [
            ("👁", "View",     "#64748b", lambda _, r=row: self._on_view(r)),
            ("⬇",  "Download", "#0d9488", lambda _, r=row: self._on_download(r)),
            ("🗑",  "Delete",   "#dc2626", lambda _, r=row: self._on_delete(r)),
        ]:
            b = QtWidgets.QPushButton(ico)
            b.setFixedSize(24, 24)
            b.setToolTip(tip)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{col}22; color:{col};
                    border:1px solid {col}44;
                    border-radius:5px; font-size:11px;
                }}
                QPushButton:hover {{ background:{col}44; }}
            """)
            b.clicked.connect(slot)
            hl.addWidget(b)
        hl.addStretch()
        return w

    # ──────────────────────────────────────────────────────────────────────────
    # SLOTS
    # ──────────────────────────────────────────────────────────────────────────
    def _apply_filters(self):
        text = self.search_edit.text().lower()
        type_f = self._type_combo.currentText()
        dept_f = self._dept_combo.currentText()
        status_f = self._status_combo.currentText()
        results = []
        for rec in self._reports:
            (num, name, rtype, dept_scope, generated_by, generated_on,
             period, status) = rec
            if type_f != "All Types" and rtype != type_f: continue
            if dept_f != "All Departments" and dept_scope != dept_f: continue
            if status_f != "All Statuses" and status != status_f: continue
            if text and not any(text in v.lower() for v in
                                (name, rtype, dept_scope, generated_by)):
                continue
            results.append(rec)
        self._populate_table(results)

    def _on_add(self):
        dlg = GenerateReportDialog(self)
        dlg.report_saved.connect(self._append_report)
        dlg.exec()

    def _append_report(self, data: dict):
        from datetime import datetime
        new_num = len(self._reports) + 1
        gen_on = datetime.now().strftime("%d %b %Y %I:%M %p")
        self._reports.insert(0, (
            new_num, data["name"], data["report_type"], data["dept_scope"],
            data["generated_by"], gen_on, data["period_covered"], data["status"]
        ))
        self._apply_filters()
        QtWidgets.QMessageBox.information(
            self, "Report Generated",
            f"✅  '{data['name']}' has been generated successfully."
        )

    def _on_view(self, row: int):
        if row >= len(self._reports): return
        r = self._reports[row]
        QtWidgets.QMessageBox.information(
            self, "Report Details",
            f"<b>{r[1]}</b><br>Type: {r[2]}<br>Department / Scope: {r[3]}<br>"
            f"Generated By: {r[4]}<br>Generated On: {r[5]}<br>"
            f"Period Covered: {r[6]}<br>Status: {r[7]}"
        )

    def _on_download(self, row: int):
        if row >= len(self._reports): return
        name = self._reports[row][1]
        QtWidgets.QMessageBox.information(
            self, "Download Report",
            f"⬇  '{name}' will be downloaded once connected to the database "
            f"in the next sprint."
        )

    def _on_delete(self, row: int):
        if row >= len(self._reports): return
        name = self._reports[row][1]
        reply = QtWidgets.QMessageBox.question(
            self, "Delete Report",
            f"Delete <b>{name}</b>? This cannot be undone.",
            QtWidgets.QMessageBox.StandardButton.Yes |
            QtWidgets.QMessageBox.StandardButton.No,
            QtWidgets.QMessageBox.StandardButton.No,
        )
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            self._reports.pop(row)
            self._apply_filters()

    def _on_filter_menu(self):
        QtWidgets.QMessageBox.information(
            self, "Advanced Filters",
            "Advanced filter panel will be available in the next sprint."
        )

    def _on_export(self):
        QtWidgets.QMessageBox.information(
            self, "Export",
            "Export functionality will be connected in the next sprint."
        )

    def _on_placeholder(self):
        QtWidgets.QMessageBox.information(
            self, "Coming Soon",
            "This feature will be available in the next sprint."
        )