# Form implementation generated from reading ui file 'Attendance_Page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
# Author: Wilkeans Bellamy
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt

# ── Shared palette ────────────────────────────────────────────────────────────
_NAVY      = "#0d1b3e"
_ACCENT    = "#5870ff"
_PURPLE    = "#7c5cfc"
_BG        = "#f0f2f5"
_WHITE     = "#ffffff"
_BORDER    = "#e5e7eb"
_TEXT_DARK = "#1a1a2e"
_TEXT_GREY = "#6b7280"
_TEXT_MID  = "#374151"

# ── Status colours ─────────────────────────────────────────────────────────────
STATUS_COLOURS = {
    "Present": ("#15803d", "#dcfce7"),
    "Late":    ("#d97706", "#fef3c7"),
    "Absent":  ("#b91c1c", "#fee2e2"),
    "On Leave":("#6b7280", "#f3f4f6"),
}

# ── Avatar colour palette (cycled per row) ─────────────────────────────────────
AVATAR_COLOURS = ["#5870ff", "#10b981", "#f59e0b", "#8b5cf6", "#ef4444",
                  "#0ea5e9", "#ec4899", "#14b8a6", "#f97316", "#6366f1"]

# ── Sample attendance data ───────────────────────────────────────────────────
# (num, name, reg_no, institution, department, supervisor, start_date, end_date,
#  check_in, check_out, total_hours, week_attendance, status, remarks)
SAMPLE_ATTENDANCE = [
    (1,  "John Kamau",     "REG/2025/001", "Kenyatta University",      "Information Technology", "David Mwangi",   "01 May 2025", "31 Jul 2025", "08:31 AM", "05:12 PM", "8h 41m", "5 / 5 days", "Present", "-"),
    (2,  "Grace Njeri",    "REG/2025/002", "Jomo Kenyatta Uni.",       "Marketing & Comms",      "Mary Wanjiku",   "01 May 2025", "31 Jul 2025", "08:15 AM", "05:05 PM", "8h 50m", "4 / 5 days", "Late",    "Traffic delay"),
    (3,  "David Mwangi",   "REG/2025/003", "University of Nairobi",    "Human Resources",        "Susan Akinyi",   "01 May 2025", "31 Jul 2025", "08:00 AM", "05:00 PM", "9h 00m", "5 / 5 days", "Present", "-"),
    (4,  "Susan Akinyi",   "REG/2025/004", "Strathmore University",    "Finance & Accounts",     "Peter Ochieng",  "01 May 2025", "31 Jul 2025", "09:05 AM", "05:10 PM", "8h 05m", "4 / 5 days", "Late",    "Slept in"),
    (5,  "Brian Otieno",   "REG/2025/005", "Kisii University",         "Operations",             "Lilian Moraa",   "01 May 2025", "31 Jul 2025", "08:02 AM", "05:00 PM", "8h 58m", "5 / 5 days", "Present", "-"),
    (6,  "Lilian Moraa",   "REG/2025/006", "Egerton University",       "Procurement",            "Kevin Odhiambo", "01 May 2025", "31 Jul 2025", "-",        "-",        "0h 00m", "3 / 5 days", "Absent",  "Sick leave"),
    (7,  "Peter Ochieng",  "REG/2025/007", "Maseno University",        "IT Support",             "David Mwangi",   "01 May 2025", "31 Jul 2025", "08:47 AM", "05:20 PM", "8h 33m", "5 / 5 days", "Present", "-"),
    (8,  "Aisha Hassan",   "REG/2025/008", "Technical University",     "Marketing & Comms",      "Mary Wanjiku",   "01 May 2025", "31 Jul 2025", "08:20 AM", "05:00 PM", "8h 40m", "5 / 5 days", "Present", "-"),
    (9,  "Kevin Odhiambo", "REG/2025/009", "KISAT",                    "Information Technology", "David Mwangi",   "01 May 2025", "31 Jul 2025", "08:05 AM", "05:02 PM", "8h 57m", "5 / 5 days", "Present", "-"),
    (10, "Mary Wanjiku",   "REG/2025/010", "Kenyatta University",      "Finance & Accounts",     "Peter Ochieng",  "01 May 2025", "31 Jul 2025", "-",        "-",        "0h 00m", "3 / 5 days", "Absent",  "Personal"),
]

DEPARTMENTS = [
    "All Departments", "Information Technology", "Marketing & Comms",
    "Finance & Accounts", "Human Resources", "Operations",
    "Procurement", "IT Support",
]

STATUSES = ["All Statuses", "Present", "Late", "Absent", "On Leave"]

# ── Today's Attendance Overview — donut data ─────────────────────────────────
OVERVIEW_SLICES = [
    ("Present",  56, "#10b981"),
    ("Late",      9, "#f59e0b"),
    ("Absent",    8, "#ef4444"),
    ("On Leave",  5, "#d1d5db"),
]

# ── Attendance Trend (This Week) — multi-line series ─────────────────────────
TREND_DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
TREND_SERIES = [
    ("Present", "#10b981", [65, 90, 70, 85, 75, 95, 80]),
    ("Absent",  "#ef4444", [20, 15, 22, 18, 20, 10, 15]),
    ("Late",    "#f59e0b", [10,  8, 12, 10, 15,  5, 18]),
]

# ── Attendance by Department — horizontal bar data ───────────────────────────
# (name, present_count, attendance_rate_pct, colour)
DEPT_BARS = [
    ("Information Technology", 18, 85.71, "#3b82f6"),
    ("Marketing & Comms",      14, 82.35, "#10b981"),
    ("Finance & Accounts",     11, 84.62, "#f59e0b"),
    ("Human Resources",         8, 72.73, "#8b5cf6"),
    ("Operations",              7, 87.50, "#06b6d4"),
    ("Procurement",             6, 75.00, "#ec4899"),
    ("IT Support",              5, 83.33, "#ef4444"),
]
DEPT_OVERALL_RATE = "83.33%"

# ── Punctuality (Late Arrivals) — donut data ─────────────────────────────────
PUNCTUALITY_SLICES = [
    ("< 15 mins",  4, "#ef4444"),
    ("15 - 30 mins", 3, "#f59e0b"),
    ("> 30 mins",  2, "#10b981"),
]

# ── Selected attachee shown by default in the right-hand Details panel ───────
DEFAULT_SELECTED_INDEX = 0


# ==============================================================================
# STYLE HELPERS
# ==============================================================================
def _card(parent=None) -> QtWidgets.QFrame:
    f = QtWidgets.QFrame(parent)
    f.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
    f.setStyleSheet(f"""
        QFrame {{
            background:{_WHITE};
            border:1px solid {_BORDER};
            border-radius:10px;
        }}
    """)
    return f


def _outline_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_WHITE}; color:{_TEXT_MID};
            border:1px solid {_BORDER}; border-radius:6px;
            padding:0 14px; font-size:12px;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#f9fafb; }}
    """)
    return btn


def _primary_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_ACCENT}; color:{_WHITE}; border:none;
            border-radius:6px; padding:0 16px;
            font-size:12px; font-weight:bold;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#4a60ee; }}
    """)
    return btn


def _link_label(text: str) -> QtWidgets.QLabel:
    lbl = QtWidgets.QLabel(text)
    lbl.setStyleSheet(f"color:{_ACCENT}; font-size:11px; font-weight:600;")
    lbl.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    return lbl


# ==============================================================================
# BADGE
# ==============================================================================
class _Badge(QtWidgets.QLabel):
    def __init__(self, text: str, fg: str, bg: str, parent=None):
        super().__init__(text, parent)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setFixedHeight(22)
        self.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                           QtWidgets.QSizePolicy.Policy.Fixed)
        self.setStyleSheet(f"""
            QLabel {{
                color:{fg}; background:{bg};
                border-radius:10px; padding:0 10px;
                font-size:10px; font-weight:700;
                font-family:'Segoe UI',Arial;
            }}
        """)


# ==============================================================================
# AVATAR CIRCLE
# ==============================================================================
class _AvatarCircle(QtWidgets.QLabel):
    def __init__(self, name: str, colour: str, size: int = 32, parent=None):
        parts = name.split()
        initials = (parts[0][0] + parts[-1][0]).upper() if len(parts) > 1 else name[:2].upper()
        super().__init__(initials, parent)
        self.setFixedSize(size, size)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setStyleSheet(f"""
            QLabel {{
                background-color:{colour};
                color:{_WHITE};
                border-radius:{size // 2}px;
                font-size:{max(10, size // 3)}px;
                font-weight:bold;
                font-family:'Segoe UI',Arial;
            }}
        """)


# ==============================================================================
# STAT CARD
# ==============================================================================
class _StatCard(QtWidgets.QFrame):
    def __init__(self, icon, icon_bg, label, value, sublabel, parent=None):
        super().__init__(parent)
        self.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.setStyleSheet(f"""
            QFrame {{
                background:{_WHITE};
                border:1px solid {_BORDER};
                border-radius:10px;
            }}
        """)
        hl = QtWidgets.QHBoxLayout(self)
        hl.setContentsMargins(16, 14, 16, 14)
        hl.setSpacing(12)

        il = QtWidgets.QLabel(icon)
        il.setFixedSize(46, 46)
        il.setAlignment(Qt.AlignmentFlag.AlignCenter)
        il.setStyleSheet(f"background:{icon_bg};border-radius:12px;font-size:20px;")

        vl = QtWidgets.QVBoxLayout(); vl.setSpacing(2)
        top = QtWidgets.QLabel(label)
        top.setStyleSheet(f"color:{_TEXT_MID};font-size:12px;font-weight:600;")
        val = QtWidgets.QLabel(value)
        val.setStyleSheet(f"color:{_TEXT_DARK};font-size:26px;font-weight:bold;"
                          "font-family:'Segoe UI',Arial;")
        sub = QtWidgets.QLabel(sublabel)
        sub.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
        vl.addWidget(top); vl.addWidget(val); vl.addWidget(sub)
        hl.addWidget(il); hl.addLayout(vl); hl.addStretch()


# ==============================================================================
# DONUT CHART  (reusable — takes any list of (label, value, colour) slices)
# ==============================================================================
class _DonutChart(QtWidgets.QWidget):
    def __init__(self, slices: list, centre_label: str = "Total", parent=None):
        super().__init__(parent)
        self.setMinimumSize(150, 150)
        self._slices = slices
        self._total = sum(s[1] for s in slices) or 1
        self._centre_label = centre_label

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        w, h = self.width(), self.height()
        size = min(w, h) - 14
        x = (w - size) // 2
        y = (h - size) // 2
        rect = QtCore.QRectF(x, y, size, size)
        start = 90 * 16
        for _, val, col in self._slices:
            span = int(round(val / self._total * 360 * 16))
            p.setBrush(QtGui.QColor(col))
            p.setPen(Qt.PenStyle.NoPen)
            p.drawPie(rect, start, -span)
            start -= span
        hole = size * 0.56
        hx = (w - hole) / 2
        hy = (h - hole) / 2
        p.setBrush(QtGui.QColor(_WHITE))
        p.drawEllipse(QtCore.QRectF(hx, hy, hole, hole))
        p.setPen(QtGui.QColor(_TEXT_DARK))
        p.setFont(QtGui.QFont("Segoe UI", 16, QtGui.QFont.Weight.Bold))
        p.drawText(QtCore.QRectF(hx, hy - 6, hole, hole / 2 + 6),
                   Qt.AlignmentFlag.AlignCenter, str(self._total))
        p.setFont(QtGui.QFont("Segoe UI", 8))
        p.setPen(QtGui.QColor(_TEXT_GREY))
        p.drawText(QtCore.QRectF(hx, hy + hole / 2 - 10, hole, 16),
                   Qt.AlignmentFlag.AlignCenter, self._centre_label)
        p.end()


# ==============================================================================
# MULTI-LINE CHART  (Attendance Trend — Present / Absent / Late)
# ==============================================================================
class _MultiLineChart(QtWidgets.QWidget):
    def __init__(self, x_labels: list, series: list, y_max: int = 100,
                 y_step: int = 20, parent=None):
        super().__init__(parent)
        self.setMinimumSize(240, 140)
        self._x_labels = x_labels
        self._series = series          # list of (name, colour, values)
        self._y_max = y_max
        self._y_step = y_step

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        w, h = self.width(), self.height()
        m_left, m_right, m_top, m_bottom = 26, 8, 8, 20
        plot_w = w - m_left - m_right
        plot_h = h - m_top - m_bottom

        steps = self._y_max // self._y_step
        font_sm = QtGui.QFont("Segoe UI", 8)
        p.setFont(font_sm)
        for i in range(steps + 1):
            val = i * self._y_step
            gy = m_top + plot_h - (val / self._y_max) * plot_h
            p.setPen(QtGui.QColor(_BORDER))
            p.drawLine(QtCore.QPointF(m_left, gy), QtCore.QPointF(w - m_right, gy))
            p.setPen(QtGui.QColor(_TEXT_GREY))
            p.drawText(QtCore.QRectF(0, gy - 7, m_left - 5, 14),
                       Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter, str(val))

        n = len(self._x_labels)
        if n < 2:
            p.end()
            return
        step_x = plot_w / (n - 1)

        def xy(i, val):
            gx = m_left + i * step_x
            gy = m_top + plot_h - (val / self._y_max) * plot_h
            return QtCore.QPointF(gx, gy)

        for _, colour, values in self._series:
            pts = [xy(i, v) for i, v in enumerate(values)]
            p.setPen(QtGui.QPen(QtGui.QColor(colour), 2))
            for i in range(len(pts) - 1):
                p.drawLine(pts[i], pts[i + 1])
            p.setBrush(QtGui.QColor(_WHITE))
            p.setPen(QtGui.QPen(QtGui.QColor(colour), 2))
            for pt in pts:
                p.drawEllipse(pt, 3, 3)

        p.setPen(QtGui.QColor(_TEXT_GREY))
        p.setFont(font_sm)
        for i, label in enumerate(self._x_labels):
            gx = m_left + i * step_x
            p.drawText(QtCore.QRectF(gx - 16, m_top + plot_h + 4, 32, 14),
                       Qt.AlignmentFlag.AlignCenter, label)
        p.end()


# ==============================================================================
# RECORD / EDIT ATTENDANCE DIALOG
# ==============================================================================
class RecordAttendanceDialog(QtWidgets.QDialog):
    attendance_saved = QtCore.pyqtSignal(dict)

    def __init__(self, parent=None, data: dict = None):
        super().__init__(parent)
        self._edit = data is not None
        self.setWindowTitle("Edit Attendance" if self._edit else "Record Attendance")
        self.setModal(True)
        self.setFixedSize(500, 560)
        self.setStyleSheet(f"""
            QDialog {{ background:{_WHITE}; font-family:'Segoe UI',Arial; }}
            QLabel#hdrTitle {{ color:{_TEXT_DARK}; font-size:15px; font-weight:bold; }}
            QLabel#hdrSub   {{ color:{_TEXT_GREY}; font-size:12px; }}
            QLabel#fldLbl   {{ color:{_TEXT_MID};  font-size:12px; font-weight:600; }}
            QLineEdit, QComboBox {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:7px 10px; font-size:12px;
                color:{_TEXT_DARK}; background:#f9fafb;
            }}
            QLineEdit:focus, QComboBox:focus {{
                border:1.5px solid {_ACCENT}; background:{_WHITE};
            }}
            QPushButton#cancelBtn {{
                background:{_WHITE}; border:1px solid {_BORDER};
                border-radius:6px; padding:8px 22px;
                font-size:12px; color:{_TEXT_MID};
            }}
            QPushButton#cancelBtn:hover {{ background:#f9fafb; }}
            QPushButton#saveBtn {{
                background:{_ACCENT}; border:none; border-radius:6px;
                padding:8px 26px; font-size:12px;
                font-weight:bold; color:{_WHITE};
            }}
            QPushButton#saveBtn:hover {{ background:#4a60ee; }}
            QFrame#div {{ border:none; border-top:1px solid {_BORDER}; }}
        """)

        root = QtWidgets.QVBoxLayout(self)
        root.setContentsMargins(26, 22, 26, 18)
        root.setSpacing(0)

        hhl = QtWidgets.QHBoxLayout()
        ico = QtWidgets.QLabel("🗓")
        ico.setFixedSize(40, 40)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:#ede9fe;border-radius:20px;font-size:18px;")
        hvl = QtWidgets.QVBoxLayout(); hvl.setSpacing(2)
        ht = QtWidgets.QLabel("Edit Attendance" if self._edit else "Record Attendance")
        ht.setObjectName("hdrTitle")
        hs = QtWidgets.QLabel("Update the attendance record below." if self._edit
                              else "Fill in the details to log a new attendance entry.")
        hs.setObjectName("hdrSub")
        hvl.addWidget(ht); hvl.addWidget(hs)
        hhl.addWidget(ico); hhl.addSpacing(10)
        hhl.addLayout(hvl); hhl.addStretch()
        root.addLayout(hhl); root.addSpacing(14)

        d0 = QtWidgets.QFrame(); d0.setObjectName("div"); d0.setFixedHeight(1)
        root.addWidget(d0); root.addSpacing(14)

        def lbl(t):
            l = QtWidgets.QLabel(t); l.setObjectName("fldLbl"); return l

        form = QtWidgets.QFormLayout()
        form.setVerticalSpacing(12); form.setHorizontalSpacing(14)
        form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft)

        self.name_edit = QtWidgets.QLineEdit()
        self.name_edit.setPlaceholderText("e.g. John Kamau")
        form.addRow(lbl("Attachee Name *"), self.name_edit)

        self.dept_combo = QtWidgets.QComboBox()
        self.dept_combo.addItem("— Select Department —")
        self.dept_combo.addItems(DEPARTMENTS[1:])
        form.addRow(lbl("Department *"), self.dept_combo)

        self.supervisor_edit = QtWidgets.QLineEdit()
        self.supervisor_edit.setPlaceholderText("e.g. David Mwangi")
        form.addRow(lbl("Supervisor"), self.supervisor_edit)

        self.checkin_edit = QtWidgets.QLineEdit()
        self.checkin_edit.setPlaceholderText("e.g. 08:30 AM")
        form.addRow(lbl("Check-In Time"), self.checkin_edit)

        self.checkout_edit = QtWidgets.QLineEdit()
        self.checkout_edit.setPlaceholderText("e.g. 05:00 PM")
        form.addRow(lbl("Check-Out Time"), self.checkout_edit)

        self.status_combo = QtWidgets.QComboBox()
        self.status_combo.addItems(STATUSES[1:])
        form.addRow(lbl("Status"), self.status_combo)

        self.remarks_edit = QtWidgets.QLineEdit()
        self.remarks_edit.setPlaceholderText("Optional remarks...")
        form.addRow(lbl("Remarks"), self.remarks_edit)

        root.addLayout(form)

        if self._edit and data:
            self.name_edit.setText(data.get("name", ""))
            idx = self.dept_combo.findText(data.get("department", ""))
            if idx >= 0: self.dept_combo.setCurrentIndex(idx)
            self.supervisor_edit.setText(data.get("supervisor", ""))
            self.checkin_edit.setText(data.get("check_in", ""))
            self.checkout_edit.setText(data.get("check_out", ""))
            idx = self.status_combo.findText(data.get("status", ""))
            if idx >= 0: self.status_combo.setCurrentIndex(idx)
            self.remarks_edit.setText(data.get("remarks", ""))

        root.addStretch()

        self.err_lbl = QtWidgets.QLabel("")
        self.err_lbl.setStyleSheet("color:#b91c1c;font-size:11px;")
        self.err_lbl.setVisible(False)
        root.addWidget(self.err_lbl); root.addSpacing(8)

        d1 = QtWidgets.QFrame(); d1.setObjectName("div"); d1.setFixedHeight(1)
        root.addWidget(d1); root.addSpacing(12)

        bhl = QtWidgets.QHBoxLayout(); bhl.addStretch()
        cb = QtWidgets.QPushButton("Cancel"); cb.setObjectName("cancelBtn")
        cb.setFixedHeight(36)
        cb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        cb.clicked.connect(self.reject)
        sb = QtWidgets.QPushButton(
            "💾  Save Changes" if self._edit else "✚  Record Attendance")
        sb.setObjectName("saveBtn"); sb.setFixedHeight(36)
        sb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        sb.clicked.connect(self._on_save)
        bhl.addWidget(cb); bhl.addSpacing(8); bhl.addWidget(sb)
        root.addLayout(bhl)

    def _on_save(self):
        name = self.name_edit.text().strip()
        dept = self.dept_combo.currentText()
        errs = []
        if not name: errs.append("Attachee Name is required.")
        if dept.startswith("—"): errs.append("Select a Department.")
        if errs:
            self.err_lbl.setText("⚠  " + "  •  ".join(errs))
            self.err_lbl.setVisible(True)
            return
        self.err_lbl.setVisible(False)
        self.attendance_saved.emit({
            "name": name, "department": dept,
            "supervisor": self.supervisor_edit.text().strip(),
            "check_in": self.checkin_edit.text().strip() or "-",
            "check_out": self.checkout_edit.text().strip() or "-",
            "status": self.status_combo.currentText(),
            "remarks": self.remarks_edit.text().strip() or "-",
        })
        self.accept()


# ==============================================================================
# ATTENDANCE PAGE
# ==============================================================================
class AttendancePage(QtWidgets.QWidget):
    """
    Full Attendance page — slots into the Industrial Attachment sub-tab stack
    (or stackedWidget_2 index 2).

    Layout
    ──────
    Left scroll area
      • Page header + breadcrumb
      • 5 stat cards (Total / Present / Late / Absent / Attendance Rate)
      • Filter row (Date / Department / Status / Search / Actions)
      • Attendance Records section: table + pagination
      • Bottom analytics row: overview donut | trend | dept bars | punctuality donut
    Right panel (fixed 280px)
      • Attachee Details card (selected row)
      • Quick Actions
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("Attendance_Page")
        self.setStyleSheet(f"background:{_BG};")
        self._records = list(SAMPLE_ATTENDANCE)
        self._build_ui()
        self._populate_table()
        if self._records:
            self._show_details(DEFAULT_SELECTED_INDEX)

    # ──────────────────────────────────────────────────────────────────────────
    def _build_ui(self):
        outer = QtWidgets.QHBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0); outer.setSpacing(0)

        # ════════════════════ LEFT SCROLL AREA ═══════════════════════════════
        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        scroll.setStyleSheet("background:transparent;border:none;")

        lc = QtWidgets.QWidget(); lc.setStyleSheet(f"background:{_BG};")
        lv = QtWidgets.QVBoxLayout(lc)
        lv.setContentsMargins(22, 18, 14, 18); lv.setSpacing(14)

        # ── Page header ───────────────────────────────────────────────
        hdr = QtWidgets.QHBoxLayout(); hdr.setSpacing(12)
        ico = QtWidgets.QLabel("🗓")
        ico.setFixedSize(52, 52)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:{_PURPLE};border-radius:14px;font-size:22px;")
        tvl = QtWidgets.QVBoxLayout(); tvl.setSpacing(2)
        pg_t = QtWidgets.QLabel("Attendance")
        pg_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:22px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        pg_s = QtWidgets.QLabel("Monitor and manage daily attendance for all industrial attachees.")
        pg_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        tvl.addWidget(pg_t); tvl.addWidget(pg_s)
        hdr.addWidget(ico); hdr.addLayout(tvl); hdr.addStretch()

        breadcrumb = QtWidgets.QLabel(
            f'<span style="color:{_TEXT_GREY};">Dashboard &nbsp;›&nbsp; '
            f'Industrial Attachments &nbsp;›&nbsp;</span> '
            f'<span style="color:{_TEXT_DARK};font-weight:600;">Attendance</span>'
        )
        breadcrumb.setStyleSheet("font-size:11px;")
        hdr.addWidget(breadcrumb)
        lv.addLayout(hdr)

        # ── Stat cards ────────────────────────────────────────────────
        cards_hl = QtWidgets.QHBoxLayout(); cards_hl.setSpacing(12)
        for icon, ibg, label, val, sub in [
            ("👥", "#ede9fe", "Total Attaches",  "78",     "All attachees"),
            ("✅", "#dcfce7", "Present Today",    "56",     "71.79% of total"),
            ("🕐", "#fef3c7", "Late Arrivals",    "9",      "11.54% of total"),
            ("⏳", "#fee2e2", "Absent",           "8",      "10.26% of total"),
            ("📅", "#dbeafe", "Attendance Rate",  "83.33%", "Overall today"),
        ]:
            cards_hl.addWidget(_StatCard(icon, ibg, label, val, sub))
        lv.addLayout(cards_hl)

        # ── Filter row ────────────────────────────────────────────────
        filter_hl = QtWidgets.QHBoxLayout(); filter_hl.setSpacing(12)

        date_vl = QtWidgets.QVBoxLayout(); date_vl.setSpacing(3)
        dl = QtWidgets.QLabel("Date")
        dl.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;font-weight:600;")
        self.date_btn = QtWidgets.QPushButton("📅  22 Jun 2025 (Today)")
        self.date_btn.setFixedHeight(36)
        self.date_btn.setMinimumWidth(180)
        self.date_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        self.date_btn.setStyleSheet(f"""
            QPushButton {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 10px; font-size:12px; text-align:left;
                color:{_TEXT_MID}; background:{_WHITE};
            }}
            QPushButton:hover {{ background:#f9fafb; }}
        """)
        date_vl.addWidget(dl); date_vl.addWidget(self.date_btn)
        filter_hl.addLayout(date_vl)

        for combo_lbl, items, attr in [
            ("Department", DEPARTMENTS, "_dept_combo"),
            ("Status",     STATUSES,    "_status_combo"),
        ]:
            combo = QtWidgets.QComboBox()
            combo.addItems(items)
            combo.setFixedHeight(36); combo.setMinimumWidth(150)
            combo.setStyleSheet(f"""
                QComboBox {{
                    border:1px solid {_BORDER}; border-radius:6px;
                    padding:0 10px; font-size:12px;
                    color:{_TEXT_MID}; background:{_WHITE};
                }}
                QComboBox:focus {{ border:1.5px solid {_ACCENT}; }}
                QComboBox::drop-down {{ border:none; width:20px; }}
            """)
            combo.currentIndexChanged.connect(self._apply_filters)
            setattr(self, attr, combo)
            lbl_vl = QtWidgets.QVBoxLayout(); lbl_vl.setSpacing(3)
            ll = QtWidgets.QLabel(combo_lbl)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;font-weight:600;")
            lbl_vl.addWidget(ll); lbl_vl.addWidget(combo)
            filter_hl.addLayout(lbl_vl)

        self.search_edit = QtWidgets.QLineEdit()
        self.search_edit.setPlaceholderText("🔍  Search attachees...")
        self.search_edit.setFixedHeight(36)
        self.search_edit.setMinimumWidth(190)
        self.search_edit.setStyleSheet(f"""
            QLineEdit {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 12px; font-size:12px;
                color:{_TEXT_MID}; background:{_WHITE};
            }}
            QLineEdit:focus {{ border:1.5px solid {_ACCENT}; }}
        """)
        self.search_edit.textChanged.connect(self._apply_filters)
        search_vl = QtWidgets.QVBoxLayout(); search_vl.setSpacing(3)
        search_vl.addSpacing(15)
        search_vl.addWidget(self.search_edit)
        filter_hl.addLayout(search_vl)
        filter_hl.addStretch()

        btn_vl = QtWidgets.QVBoxLayout(); btn_vl.setSpacing(3)
        btn_vl.addSpacing(15)
        btn_row = QtWidgets.QHBoxLayout(); btn_row.setSpacing(8)
        self.filter_btn = _outline_btn("▽  Filter")
        self.export_btn = _outline_btn("↓  Export")
        self.add_btn    = _primary_btn("＋  Record Attendance")
        self.filter_btn.setFixedHeight(36)
        self.export_btn.setFixedHeight(36)
        self.add_btn.setFixedHeight(36)
        self.filter_btn.clicked.connect(self._on_filter_menu)
        self.export_btn.clicked.connect(self._on_export)
        self.add_btn.clicked.connect(self._on_add)
        btn_row.addWidget(self.filter_btn)
        btn_row.addWidget(self.export_btn)
        btn_row.addWidget(self.add_btn)
        btn_vl.addLayout(btn_row)
        filter_hl.addLayout(btn_vl)
        lv.addLayout(filter_hl)

        # ── Section title ─────────────────────────────────────────────
        sec_vl = QtWidgets.QVBoxLayout(); sec_vl.setSpacing(2)
        sec_t = QtWidgets.QLabel("Attendance Records")
        sec_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:14px;font-weight:bold;"
                            "font-family:'Segoe UI',Arial;")
        sec_s = QtWidgets.QLabel("View and manage daily attendance records.")
        sec_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        sec_vl.addWidget(sec_t); sec_vl.addWidget(sec_s)
        lv.addLayout(sec_vl)

        # ── Table card ────────────────────────────────────────────────
        tcard = _card()
        tcvl = QtWidgets.QVBoxLayout(tcard)
        tcvl.setContentsMargins(0, 0, 0, 0); tcvl.setSpacing(0)

        self.table = QtWidgets.QTableWidget()
        self.table.setColumnCount(11)
        self.table.setHorizontalHeaderLabels([
            "#", "Attachee", "Reg. No.", "Department", "Supervisor",
            "Check-In", "Check-Out", "Total Hours", "Status", "Remarks", "Actions"
        ])
        self.table.setShowGrid(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.verticalHeader().setVisible(False)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)

        for i, w in enumerate([28, 140, 85, 140, 110, 75, 75, 75, 75, 90, 85]):
            self.table.setColumnWidth(i, w)
        self.table.horizontalHeader().setSectionResizeMode(
            1, QtWidgets.QHeaderView.ResizeMode.Stretch)

        self.table.setStyleSheet(f"""
            QTableWidget {{
                border:none; background:{_WHITE};
                alternate-background-color:#fafbfc;
                font-size:12px; color:{_TEXT_MID};
                font-family:'Segoe UI',Arial; outline:none;
            }}
            QTableWidget::item {{
                padding:4px 6px; border-bottom:1px solid #f3f4f6;
            }}
            QTableWidget::item:selected {{
                background:#eff6ff; color:{_TEXT_DARK};
            }}
            QHeaderView::section {{
                background:#f9fafb; color:{_TEXT_GREY};
                font-size:10px; font-weight:bold;
                border:none; border-bottom:1px solid {_BORDER}; padding:8px 6px;
            }}
            QScrollBar:vertical {{
                border:none; background:#f0f2f5;
                width:7px; border-radius:3px;
            }}
            QScrollBar::handle:vertical {{
                background:#d1d5db; border-radius:3px;
            }}
        """)
        self.table.cellClicked.connect(self._on_row_click)
        tcvl.addWidget(self.table)

        # Pagination bar
        pg_bar = QtWidgets.QWidget()
        pg_bar.setFixedHeight(46)
        pg_bar.setStyleSheet(f"""
            QWidget {{
                background:{_WHITE};
                border-top:1px solid {_BORDER};
                border-bottom-left-radius:10px;
                border-bottom-right-radius:10px;
            }}
        """)
        pg_hl = QtWidgets.QHBoxLayout(pg_bar)
        pg_hl.setContentsMargins(14, 0, 14, 0); pg_hl.setSpacing(4)
        self.showing_lbl = QtWidgets.QLabel("Showing 1 to 10 of 78 records")
        self.showing_lbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(self.showing_lbl); pg_hl.addStretch()

        for txt, act in [("«", False), ("‹", False), ("1", True), ("2", False),
                         ("3", False), ("4", False), ("5", False), ("…", None),
                         ("8", False), ("›", False), ("»", False)]:
            if act is None:
                dots = QtWidgets.QLabel(txt)
                dots.setFixedSize(26, 26)
                dots.setAlignment(Qt.AlignmentFlag.AlignCenter)
                dots.setStyleSheet(f"color:{_TEXT_GREY};font-size:12px;")
                pg_hl.addWidget(dots)
                continue
            b = QtWidgets.QPushButton(txt)
            b.setFixedSize(26, 26)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{"#1e3a6e" if act else _WHITE};
                    color:{"#fff" if act else _TEXT_MID};
                    border:1px solid {"#1e3a6e" if act else _BORDER};
                    border-radius:4px; font-size:11px;
                }}
                QPushButton:hover {{
                    background:{"#254d91" if act else "#f9fafb"};
                }}
            """)
            pg_hl.addWidget(b)

        pg_hl.addSpacing(10)
        pp = QtWidgets.QLabel("10 / page  ▾")
        pp.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(pp)
        tcvl.addWidget(pg_bar)
        lv.addWidget(tcard)

        # ── Bottom analytics row ──────────────────────────────────────
        bot = QtWidgets.QHBoxLayout(); bot.setSpacing(12)

        # Today's Attendance Overview (donut)
        ov = _card()
        ov_vl = QtWidgets.QVBoxLayout(ov)
        ov_vl.setContentsMargins(14, 14, 14, 12); ov_vl.setSpacing(8)
        ov_t = QtWidgets.QLabel("Today's Attendance Overview")
        ov_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        ov_t.setWordWrap(True)
        ov_vl.addWidget(ov_t)
        ov_row = QtWidgets.QHBoxLayout(); ov_row.setSpacing(10)
        ov_donut = _DonutChart(OVERVIEW_SLICES)
        ov_donut.setFixedSize(110, 110)
        ov_row.addWidget(ov_donut)
        ov_leg = QtWidgets.QVBoxLayout(); ov_leg.setSpacing(6)
        ov_leg.setAlignment(Qt.AlignmentFlag.AlignVCenter)
        total_ov = sum(v for _, v, _ in OVERVIEW_SLICES)
        for name, val, col in OVERVIEW_SLICES:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(5)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{col};font-size:10px;")
            dot.setFixedWidth(10)
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:9px;")
            vr = QtWidgets.QLabel(f"{val} ({val/total_ov*100:.2f}%)")
            vr.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            row.addWidget(dot); row.addWidget(nl); row.addStretch(); row.addWidget(vr)
            ov_leg.addLayout(row)
        ov_row.addLayout(ov_leg)
        ov_vl.addLayout(ov_row)
        bot.addWidget(ov, stretch=3)

        # Attendance Trend (This Week)
        trend = _card()
        tr_vl = QtWidgets.QVBoxLayout(trend)
        tr_vl.setContentsMargins(14, 14, 14, 12); tr_vl.setSpacing(6)
        tr_t = QtWidgets.QLabel("Attendance Trend (This Week)")
        tr_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        tr_vl.addWidget(tr_t)
        tr_leg = QtWidgets.QHBoxLayout(); tr_leg.setSpacing(12)
        for name, colour, _vals in TREND_SERIES:
            item_hl = QtWidgets.QHBoxLayout(); item_hl.setSpacing(4)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{colour};font-size:10px;")
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:9px;")
            item_hl.addWidget(dot); item_hl.addWidget(nl)
            tr_leg.addLayout(item_hl)
        tr_leg.addStretch()
        tr_vl.addLayout(tr_leg)
        tr_vl.addWidget(_MultiLineChart(TREND_DAYS, TREND_SERIES), stretch=1)
        bot.addWidget(trend, stretch=4)

        # Attendance by Department (horizontal bars)
        dept = _card()
        dp_vl = QtWidgets.QVBoxLayout(dept)
        dp_vl.setContentsMargins(14, 14, 14, 12); dp_vl.setSpacing(6)
        dp_t = QtWidgets.QLabel("Attendance by Department")
        dp_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        dp_vl.addWidget(dp_t)
        for name, count, pct, col in DEPT_BARS:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            nl = QtWidgets.QLabel(name)
            nl.setFixedWidth(118)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:9px;")
            bar_bg = QtWidgets.QFrame()
            bar_bg.setFixedHeight(9)
            bar_bg.setStyleSheet("background:#f3f4f6;border-radius:4px;")
            bar_hl = QtWidgets.QHBoxLayout(bar_bg)
            bar_hl.setContentsMargins(0, 0, 0, 0); bar_hl.setSpacing(0)
            fill = QtWidgets.QFrame()
            fill.setFixedHeight(9)
            fill.setStyleSheet(f"background:{col};border-radius:4px;")
            pctf = int(round(pct))
            bar_hl.addWidget(fill, stretch=pctf)
            bar_hl.addStretch(100 - pctf)
            vlbl = QtWidgets.QLabel(f"{count} ({pct:.2f}%)")
            vlbl.setFixedWidth(78)
            vlbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            vlbl.setAlignment(Qt.AlignmentFlag.AlignRight)
            row.addWidget(nl); row.addWidget(bar_bg, stretch=1); row.addWidget(vlbl)
            dp_vl.addLayout(row)
        dp_vl.addSpacing(2)
        overall_row = QtWidgets.QHBoxLayout()
        overall_lbl = QtWidgets.QLabel("Overall")
        overall_lbl.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:bold;")
        overall_val = QtWidgets.QLabel(DEPT_OVERALL_RATE)
        overall_val.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:bold;")
        overall_val.setAlignment(Qt.AlignmentFlag.AlignRight)
        overall_row.addWidget(overall_lbl); overall_row.addStretch(); overall_row.addWidget(overall_val)
        dp_vl.addLayout(overall_row)
        bot.addWidget(dept, stretch=4)

        # Punctuality (Late Arrivals)
        punc = _card()
        pu_vl = QtWidgets.QVBoxLayout(punc)
        pu_vl.setContentsMargins(14, 14, 14, 12); pu_vl.setSpacing(8)
        pu_t = QtWidgets.QLabel("Punctuality (Late Arrivals)")
        pu_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        pu_vl.addWidget(pu_t)
        pu_row = QtWidgets.QHBoxLayout(); pu_row.setSpacing(10)
        pu_donut = _DonutChart(PUNCTUALITY_SLICES, centre_label="Late")
        pu_donut.setFixedSize(110, 110)
        pu_row.addWidget(pu_donut)
        pu_leg = QtWidgets.QVBoxLayout(); pu_leg.setSpacing(6)
        pu_leg.setAlignment(Qt.AlignmentFlag.AlignVCenter)
        total_pu = sum(v for _, v, _ in PUNCTUALITY_SLICES)
        for name, val, col in PUNCTUALITY_SLICES:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(5)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{col};font-size:10px;")
            dot.setFixedWidth(10)
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:9px;")
            vr = QtWidgets.QLabel(f"{val} ({val/total_pu*100:.2f}%)")
            vr.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            row.addWidget(dot); row.addWidget(nl); row.addStretch(); row.addWidget(vr)
            pu_leg.addLayout(row)
        pu_row.addLayout(pu_leg)
        pu_vl.addLayout(pu_row)
        bot.addWidget(punc, stretch=3)

        lv.addLayout(bot)
        lv.addStretch()
        scroll.setWidget(lc)
        outer.addWidget(scroll, stretch=1)

        # ════════════════════ RIGHT PANEL ════════════════════════════════════
        rp = QtWidgets.QWidget()
        rp.setFixedWidth(280)
        rp.setStyleSheet(f"background:{_BG};border-left:1px solid {_BORDER};")

        rp_scroll = QtWidgets.QScrollArea()
        rp_scroll.setWidgetResizable(True)
        rp_scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        rp_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        rp_scroll.setStyleSheet("background:transparent;border:none;")

        ri = QtWidgets.QWidget(); ri.setStyleSheet(f"background:{_BG};")
        rv = QtWidgets.QVBoxLayout(ri)
        rv.setContentsMargins(12, 16, 12, 16); rv.setSpacing(12)

        # ── Attachee Details card ─────────────────────────────────────
        dd_card = _card()
        self._dd_vl = QtWidgets.QVBoxLayout(dd_card)
        self._dd_vl.setContentsMargins(14, 14, 14, 14); self._dd_vl.setSpacing(10)
        rv.addWidget(dd_card)

        # ── Quick Actions ─────────────────────────────────────────────
        qa = _card()
        qa_vl = QtWidgets.QVBoxLayout(qa)
        qa_vl.setContentsMargins(14, 14, 14, 10); qa_vl.setSpacing(6)
        qa_t = QtWidgets.QLabel("Quick Actions")
        qa_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        qa_vl.addWidget(qa_t)

        for qico, qlabel, qslot in [
            ("＋", "Record Attendance",     self._on_add),
            ("✏",  "Edit Attendance",       self._on_edit_selected),
            ("🕐", "Attendance History",    self._on_placeholder),
            ("⬇",  "Export to Excel",       self._on_placeholder),
            ("⬇",  "Export to PDF",         self._on_placeholder),
            ("🖨",  "Print Attendance Register", self._on_placeholder),
        ]:
            btn = QtWidgets.QPushButton(f"  {qico}   {qlabel}")
            btn.setFixedHeight(34)
            btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            btn.setStyleSheet(f"""
                QPushButton {{
                    background:transparent; color:{_ACCENT};
                    border:none; text-align:left;
                    font-size:11px; font-weight:600;
                    font-family:'Segoe UI',Arial;
                    border-bottom:1px solid {_BORDER};
                }}
                QPushButton:hover {{ background:#f9fafb; }}
            """)
            btn.clicked.connect(qslot)
            qa_vl.addWidget(btn)
        rv.addWidget(qa)
        rv.addStretch()

        rp_scroll.setWidget(ri)
        rp_vl = QtWidgets.QVBoxLayout(rp)
        rp_vl.setContentsMargins(0, 0, 0, 0)
        rp_vl.addWidget(rp_scroll)
        outer.addWidget(rp)

    # ──────────────────────────────────────────────────────────────────────────
    # TABLE POPULATION
    # ──────────────────────────────────────────────────────────────────────────
    def _populate_table(self, data: list = None):
        rows = data if data is not None else self._records
        self.table.setRowCount(0)
        for i, rec in enumerate(rows):
            (num, name, reg_no, institution, dept, supervisor, start_date, end_date,
             check_in, check_out, total_hours, week_att, status, remarks) = rec
            self.table.insertRow(i)
            self.table.setRowHeight(i, 48)

            self._set_item(i, 0, str(i + 1))

            att_w = QtWidgets.QWidget()
            aw_hl = QtWidgets.QHBoxLayout(att_w)
            aw_hl.setContentsMargins(6, 0, 6, 0); aw_hl.setSpacing(8)
            colour = AVATAR_COLOURS[i % len(AVATAR_COLOURS)]
            aw_hl.addWidget(_AvatarCircle(name, colour))
            name_lbl = QtWidgets.QLabel(name)
            name_lbl.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:600;")
            aw_hl.addWidget(name_lbl)
            aw_hl.addStretch()
            self.table.setCellWidget(i, 1, att_w)

            self._set_item(i, 2, reg_no)
            self._set_item(i, 3, dept)
            self._set_item(i, 4, supervisor)
            self._set_item(i, 5, check_in)
            self._set_item(i, 6, check_out)
            self._set_item(i, 7, total_hours)

            fg, bg = STATUS_COLOURS.get(status, (_TEXT_MID, "#f3f4f6"))
            self.table.setCellWidget(i, 8, self._centre(_Badge(status, fg, bg)))
            self._set_item(i, 9, remarks)
            self.table.setCellWidget(i, 10, self._action_widget(i))

        count = len(rows)
        self.showing_lbl.setText(
            f"Showing 1 to {min(10, count)} of {count} records")

    def _set_item(self, row, col, text):
        it = QtWidgets.QTableWidgetItem(text)
        it.setFlags(it.flags() & ~Qt.ItemFlag.ItemIsEditable)
        self.table.setItem(row, col, it)

    @staticmethod
    def _centre(widget) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.addWidget(widget)
        hl.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        hl.setContentsMargins(6, 0, 0, 0)
        return w

    def _action_widget(self, row: int) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.setContentsMargins(4, 0, 4, 0); hl.setSpacing(4)
        for ico, tip, col, slot in [
            ("👁", "View",   "#64748b", lambda _, r=row: self._show_details(r)),
            ("✏",  "Edit",   "#2563eb", lambda _, r=row: self._on_edit(r)),
            ("🗑",  "Delete", "#dc2626", lambda _, r=row: self._on_delete(r)),
        ]:
            b = QtWidgets.QPushButton(ico)
            b.setFixedSize(22, 22)
            b.setToolTip(tip)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{col}22; color:{col};
                    border:1px solid {col}44;
                    border-radius:5px; font-size:10px;
                }}
                QPushButton:hover {{ background:{col}44; }}
            """)
            b.clicked.connect(slot)
            hl.addWidget(b)
        hl.addStretch()
        return w

    # ──────────────────────────────────────────────────────────────────────────
    # RIGHT PANEL — ATTACHEE DETAILS
    # ──────────────────────────────────────────────────────────────────────────
    def _show_details(self, row: int):
        if row >= len(self._records):
            return
        (num, name, reg_no, institution, dept, supervisor, start_date, end_date,
         check_in, check_out, total_hours, week_att, status, remarks) = self._records[row]
        self._selected_row = row

        while self._dd_vl.count():
            item = self._dd_vl.takeAt(0)
            if item.widget():
                item.widget().deleteLater()

        hdr_lbl = QtWidgets.QLabel("Attachee Details")
        hdr_lbl.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                              "font-family:'Segoe UI',Arial;")
        self._dd_vl.addWidget(hdr_lbl)

        colour = AVATAR_COLOURS[row % len(AVATAR_COLOURS)]
        ico_row = QtWidgets.QHBoxLayout()
        ico_row.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico_row.addWidget(_AvatarCircle(name, colour, size=64))
        self._dd_vl.addLayout(ico_row)

        tl = QtWidgets.QLabel(name)
        tl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        tl.setWordWrap(True)
        tl.setStyleSheet(f"color:{_TEXT_DARK};font-size:14px;font-weight:bold;"
                         "font-family:'Segoe UI',Arial;")
        self._dd_vl.addWidget(tl)

        sfg, sbg = STATUS_COLOURS.get(status, (_TEXT_MID, "#f3f4f6"))
        st_badge = _Badge(status, sfg, sbg)
        st_row = QtWidgets.QHBoxLayout()
        st_row.setAlignment(Qt.AlignmentFlag.AlignCenter)
        st_row.addWidget(st_badge)
        self._dd_vl.addLayout(st_row)

        dv = QtWidgets.QFrame()
        dv.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        dv.setStyleSheet(f"color:{_BORDER};")
        self._dd_vl.addWidget(dv)

        details = [
            ("Registration No.", reg_no),
            ("Institution",      institution),
            ("Department",       dept),
            ("Supervisor",       supervisor),
            ("Start Date",       start_date),
            ("End Date",         end_date),
            ("Check-In Time",    check_in),
            ("Check-Out Time",   check_out),
            ("Total Hours Today", total_hours),
            ("Week Attendance",  week_att),
        ]
        for d_lbl, d_val in details:
            row_hl = QtWidgets.QHBoxLayout(); row_hl.setSpacing(6)
            ll = QtWidgets.QLabel(d_lbl)
            ll.setFixedWidth(115)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
            vw = QtWidgets.QLabel(d_val)
            vw.setWordWrap(True)
            vw.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:600;")
            row_hl.addWidget(ll); row_hl.addWidget(vw, stretch=1)
            self._dd_vl.addLayout(row_hl)

        st_row2 = QtWidgets.QHBoxLayout(); st_row2.setSpacing(6)
        st_lbl = QtWidgets.QLabel("Status Today")
        st_lbl.setFixedWidth(115)
        st_lbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
        st_val = _Badge(status, sfg, sbg)
        st_row2.addWidget(st_lbl); st_row2.addWidget(st_val); st_row2.addStretch()
        self._dd_vl.addLayout(st_row2)

        rm_row = QtWidgets.QHBoxLayout(); rm_row.setSpacing(6)
        rm_lbl = QtWidgets.QLabel("Remarks")
        rm_lbl.setFixedWidth(115)
        rm_lbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
        rm_val = QtWidgets.QLabel(remarks)
        rm_val.setWordWrap(True)
        rm_val.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:600;")
        rm_row.addWidget(rm_lbl); rm_row.addWidget(rm_val, stretch=1)
        self._dd_vl.addLayout(rm_row)

        vfp_btn = QtWidgets.QPushButton("View Full Profile")
        vfp_btn.setFixedHeight(34)
        vfp_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        vfp_btn.setStyleSheet(f"""
            QPushButton {{
                background:{_ACCENT}; color:{_WHITE}; border:none;
                border-radius:6px; font-size:12px; font-weight:bold;
            }}
            QPushButton:hover {{ background:#4a60ee; }}
        """)
        vfp_btn.clicked.connect(lambda _, r=row: self._on_view(r))
        self._dd_vl.addSpacing(4)
        self._dd_vl.addWidget(vfp_btn)

    # ──────────────────────────────────────────────────────────────────────────
    # SLOTS
    # ──────────────────────────────────────────────────────────────────────────
    def _apply_filters(self):
        text = self.search_edit.text().lower()
        dept_f = self._dept_combo.currentText()
        status_f = self._status_combo.currentText()
        results = []
        for rec in self._records:
            (num, name, reg_no, institution, dept, supervisor, start_date, end_date,
             check_in, check_out, total_hours, week_att, status, remarks) = rec
            if dept_f != "All Departments" and dept != dept_f: continue
            if status_f != "All Statuses" and status != status_f: continue
            if text and not any(text in v.lower() for v in
                                (name, reg_no, dept, supervisor)):
                continue
            results.append(rec)
        self._populate_table(results)

    def _on_row_click(self, row, col):
        self._show_details(row)

    def _on_add(self):
        dlg = RecordAttendanceDialog(self)
        dlg.attendance_saved.connect(self._append_record)
        dlg.exec()

    def _append_record(self, data: dict):
        from datetime import date
        new_num = len(self._records) + 1
        reg_no = f"REG/2025/{new_num:03d}"
        self._records.insert(0, (
            new_num, data["name"], reg_no, "—", data["department"],
            data["supervisor"], date.today().strftime("%d %b %Y"), "—",
            data["check_in"], data["check_out"], "0h 00m", "1 / 1 days",
            data["status"], data["remarks"]
        ))
        self._apply_filters()
        QtWidgets.QMessageBox.information(
            self, "Attendance Recorded",
            f"✅  Attendance for '{data['name']}' has been recorded successfully."
        )

    def _on_view(self, row: int):
        if row >= len(self._records): return
        r = self._records[row]
        QtWidgets.QMessageBox.information(
            self, "Attachee Full Profile",
            f"<b>{r[1]}</b><br>Reg. No: {r[2]}<br>Institution: {r[3]}<br>"
            f"Department: {r[4]}<br>Supervisor: {r[5]}<br>"
            f"Start: {r[6]}  •  End: {r[7]}<br>"
            f"Check-In: {r[8]}  •  Check-Out: {r[9]}<br>"
            f"Total Hours: {r[10]}<br>Week Attendance: {r[11]}<br>"
            f"Status: {r[12]}<br>Remarks: {r[13]}"
        )

    def _on_edit(self, row: int):
        if row >= len(self._records): return
        r = self._records[row]
        dlg = RecordAttendanceDialog(self, data={
            "name": r[1], "department": r[4], "supervisor": r[5],
            "check_in": r[8], "check_out": r[9], "status": r[12], "remarks": r[13],
        })
        dlg.attendance_saved.connect(lambda d, rr=row: self._save_edit(rr, d))
        dlg.exec()

    def _on_edit_selected(self):
        row = getattr(self, "_selected_row", DEFAULT_SELECTED_INDEX)
        self._on_edit(row)

    def _save_edit(self, row: int, data: dict):
        old = self._records[row]
        self._records[row] = (
            old[0], data["name"], old[2], old[3], data["department"],
            data["supervisor"], old[6], old[7], data["check_in"], data["check_out"],
            old[10], old[11], data["status"], data["remarks"]
        )
        self._apply_filters()
        self._show_details(row)

    def _on_delete(self, row: int):
        if row >= len(self._records): return
        name = self._records[row][1]
        reply = QtWidgets.QMessageBox.question(
            self, "Delete Record",
            f"Delete the attendance record for <b>{name}</b>? This cannot be undone.",
            QtWidgets.QMessageBox.StandardButton.Yes |
            QtWidgets.QMessageBox.StandardButton.No,
            QtWidgets.QMessageBox.StandardButton.No,
        )
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            self._records.pop(row)
            self._apply_filters()

    def _on_filter_menu(self):
        QtWidgets.QMessageBox.information(
            self, "Advanced Filters",
            "Advanced filter panel will be available in the next sprint."
        )

    def _on_export(self):
        QtWidgets.QMessageBox.information(
            self, "Export",
            "Export functionality will be connected in the next sprint."
        )

    def _on_placeholder(self):
        QtWidgets.QMessageBox.information(
            self, "Coming Soon",
            "This feature will be available in the next sprint."
        )