# Form implementation generated from reading ui file 'Clearances_Page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
# Author: Wilkeans Bellamy
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt

# ── Shared palette ────────────────────────────────────────────────────────────
_NAVY      = "#0d1b3e"
_ACCENT    = "#5870ff"
_PURPLE    = "#7c5cfc"
_BG        = "#f0f2f5"
_WHITE     = "#ffffff"
_BORDER    = "#e5e7eb"
_TEXT_DARK = "#1a1a2e"
_TEXT_GREY = "#6b7280"
_TEXT_MID  = "#374151"

# ── Status colours ─────────────────────────────────────────────────────────────
STATUS_COLOURS = {
    "Cleared":     ("#15803d", "#dcfce7"),
    "In Progress": ("#d97706", "#fef3c7"),
    "Pending":     ("#1d4ed8", "#dbeafe"),
    "Not Cleared": ("#b91c1c", "#fee2e2"),
}

# ── Avatar colour palette (cycled per row) ─────────────────────────────────────
AVATAR_COLOURS = ["#5870ff", "#10b981", "#f59e0b", "#8b5cf6", "#ef4444",
                  "#0ea5e9", "#ec4899", "#14b8a6", "#f97316", "#6366f1"]

# ── Sample clearance data ─────────────────────────────────────────────────────
# (num, name, reg_no, department, clearance_type, requested_on, status, cleared_on)
SAMPLE_CLEARANCES = [
    (1,  "John Kamau",     "REG/2025/001", "Information Technology", "Exit Clearance",    "18 Jun 2025", "Cleared",     "21 Jun 2025"),
    (2,  "Grace Njeri",    "REG/2025/002", "Marketing & Comms",      "Exit Clearance",    "20 Jun 2025", "In Progress", "-"),
    (3,  "David Mwangi",   "REG/2025/003", "Human Resources",        "Exit Clearance",    "19 Jun 2025", "Pending",     "-"),
    (4,  "Susan Akinyi",   "REG/2025/004", "Finance & Accounts",     "Exit Clearance",    "17 Jun 2025", "Cleared",     "20 Jun 2025"),
    (5,  "Brian Otieno",   "REG/2025/005", "Operations",             "Asset Clearance",   "15 Jun 2025", "Cleared",     "19 Jun 2025"),
    (6,  "Lilian Moraa",   "REG/2025/006", "Procurement",            "Library Clearance", "16 Jun 2025", "In Progress", "-"),
    (7,  "Peter Ochieng",  "REG/2025/007", "IT Support",             "Exit Clearance",    "14 Jun 2025", "Not Cleared", "-"),
    (8,  "Aisha Hassan",   "REG/2025/008", "Marketing & Comms",      "Exit Clearance",    "13 Jun 2025", "Cleared",     "18 Jun 2025"),
    (9,  "Kevin Odhiambo", "REG/2025/009", "Information Technology", "Asset Clearance",   "12 Jun 2025", "Pending",     "-"),
    (10, "Mary Wanjiku",   "REG/2025/010", "Finance & Accounts",     "Library Clearance", "11 Jun 2025", "Not Cleared", "-"),
]

DEPARTMENTS = [
    "All Departments", "Information Technology", "Marketing & Comms",
    "Finance & Accounts", "Human Resources", "Operations",
    "Procurement", "IT Support",
]

CLEARANCE_TYPES = ["All Types", "Exit Clearance", "Asset Clearance",
                   "Library Clearance", "ICT Clearance"]

STATUSES = ["All Statuses", "Cleared", "In Progress", "Pending", "Not Cleared"]

# ── Clearances by Department — horizontal bar data ───────────────────────────
DEPT_BARS = [
    ("Information Technology", 18, "#3b82f6"),
    ("Marketing & Comms",      14, "#10b981"),
    ("Finance & Accounts",     12, "#f59e0b"),
    ("Human Resources",        10, "#8b5cf6"),
    ("Operations",              8, "#06b6d4"),
    ("Procurement",             8, "#ec4899"),
    ("IT Support",              8, "#ef4444"),
]
DEPT_TOTAL = sum(v for _, v, _ in DEPT_BARS)

# ── Clearance Status Trend (This Month) — multi-line series ─────────────────
TREND_DAYS = ["1 Jun", "7 Jun", "14 Jun", "21 Jun", "22 Jun"]
TREND_SERIES = [
    ("Cleared",     "#10b981", [10, 14, 17, 20, 23]),
    ("In Progress", "#f59e0b", [6,  9,  8, 11, 10]),
    ("Pending",     "#3b82f6", [4,  5,  7,  6,  8]),
    ("Not Cleared", "#ef4444", [2,  3,  2,  4,  3]),
]

# ── Average Clearance Time ────────────────────────────────────────────────────
AVG_CLEARANCE_DAYS = "4.2 Days"
AVG_CLEARANCE_TREND = "↓ 1.1 days from last month"

# ── Clearance Completion Rate ────────────────────────────────────────────────
COMPLETION_PCT = 58.97
COMPLETION_CLEARED = 46
COMPLETION_NOT_CLEARED = 32
COMPLETION_TREND = "↑ 8.45% from last month"

# ── Clearance Overview (right panel) — donut data ────────────────────────────
OVERVIEW_SLICES = [
    ("Cleared",     46, "#10b981"),
    ("In Progress", 18, "#f59e0b"),
    ("Pending",      9, "#3b82f6"),
    ("Not Cleared",  5, "#ef4444"),
]

# ── Clearance Types (right panel) ────────────────────────────────────────────
# (label, icon, count, pct)
CLEARANCE_TYPE_BREAKDOWN = [
    ("Exit Clearance",    "🚪", 52, "66.67%"),
    ("Asset Clearance",   "💼", 12, "15.38%"),
    ("Library Clearance", "📚",  8, "10.26%"),
    ("ICT Clearance",     "💻",  6, "7.69%"),
]
CLEARANCE_TYPE_TOTAL = sum(v for _, _, v, _ in CLEARANCE_TYPE_BREAKDOWN)


# ==============================================================================
# STYLE HELPERS
# ==============================================================================
def _card(parent=None) -> QtWidgets.QFrame:
    f = QtWidgets.QFrame(parent)
    f.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
    f.setStyleSheet(f"""
        QFrame {{
            background:{_WHITE};
            border:1px solid {_BORDER};
            border-radius:10px;
        }}
    """)
    return f


def _outline_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_WHITE}; color:{_TEXT_MID};
            border:1px solid {_BORDER}; border-radius:6px;
            padding:0 14px; font-size:12px;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#f9fafb; }}
    """)
    return btn


def _primary_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_ACCENT}; color:{_WHITE}; border:none;
            border-radius:6px; padding:0 16px;
            font-size:12px; font-weight:bold;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#4a60ee; }}
    """)
    return btn


# ==============================================================================
# BADGE
# ==============================================================================
class _Badge(QtWidgets.QLabel):
    def __init__(self, text: str, fg: str, bg: str, parent=None):
        super().__init__(text, parent)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setFixedHeight(22)
        self.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                           QtWidgets.QSizePolicy.Policy.Fixed)
        self.setStyleSheet(f"""
            QLabel {{
                color:{fg}; background:{bg};
                border-radius:10px; padding:0 10px;
                font-size:10px; font-weight:700;
                font-family:'Segoe UI',Arial;
            }}
        """)


# ==============================================================================
# AVATAR CIRCLE
# ==============================================================================
class _AvatarCircle(QtWidgets.QLabel):
    def __init__(self, name: str, colour: str, size: int = 32, parent=None):
        parts = name.split()
        initials = (parts[0][0] + parts[-1][0]).upper() if len(parts) > 1 else name[:2].upper()
        super().__init__(initials, parent)
        self.setFixedSize(size, size)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setStyleSheet(f"""
            QLabel {{
                background-color:{colour};
                color:{_WHITE};
                border-radius:{size // 2}px;
                font-size:{max(10, size // 3)}px;
                font-weight:bold;
                font-family:'Segoe UI',Arial;
            }}
        """)


# ==============================================================================
# STAT CARD
# ==============================================================================
class _StatCard(QtWidgets.QFrame):
    def __init__(self, icon, icon_bg, label, value, sublabel, parent=None):
        super().__init__(parent)
        self.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.setStyleSheet(f"""
            QFrame {{
                background:{_WHITE};
                border:1px solid {_BORDER};
                border-radius:10px;
            }}
        """)
        hl = QtWidgets.QHBoxLayout(self)
        hl.setContentsMargins(16, 14, 16, 14)
        hl.setSpacing(12)

        il = QtWidgets.QLabel(icon)
        il.setFixedSize(46, 46)
        il.setAlignment(Qt.AlignmentFlag.AlignCenter)
        il.setStyleSheet(f"background:{icon_bg};border-radius:12px;font-size:20px;")

        vl = QtWidgets.QVBoxLayout(); vl.setSpacing(2)
        top = QtWidgets.QLabel(label)
        top.setStyleSheet(f"color:{_TEXT_MID};font-size:12px;font-weight:600;")
        val = QtWidgets.QLabel(value)
        val.setStyleSheet(f"color:{_TEXT_DARK};font-size:26px;font-weight:bold;"
                          "font-family:'Segoe UI',Arial;")
        sub = QtWidgets.QLabel(sublabel)
        sub.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
        vl.addWidget(top); vl.addWidget(val); vl.addWidget(sub)
        hl.addWidget(il); hl.addLayout(vl); hl.addStretch()


# ==============================================================================
# DONUT CHART  (reusable — takes any list of (label, value, colour) slices)
# ==============================================================================
class _DonutChart(QtWidgets.QWidget):
    def __init__(self, slices: list, centre_label: str = "Total", parent=None):
        super().__init__(parent)
        self.setMinimumSize(150, 150)
        self._slices = slices
        self._total = sum(s[1] for s in slices) or 1
        self._centre_label = centre_label

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        w, h = self.width(), self.height()
        size = min(w, h) - 14
        x = (w - size) // 2
        y = (h - size) // 2
        rect = QtCore.QRectF(x, y, size, size)
        start = 90 * 16
        for _, val, col in self._slices:
            span = int(round(val / self._total * 360 * 16))
            p.setBrush(QtGui.QColor(col))
            p.setPen(Qt.PenStyle.NoPen)
            p.drawPie(rect, start, -span)
            start -= span
        hole = size * 0.56
        hx = (w - hole) / 2
        hy = (h - hole) / 2
        p.setBrush(QtGui.QColor(_WHITE))
        p.drawEllipse(QtCore.QRectF(hx, hy, hole, hole))
        p.setPen(QtGui.QColor(_TEXT_DARK))
        p.setFont(QtGui.QFont("Segoe UI", 16, QtGui.QFont.Weight.Bold))
        p.drawText(QtCore.QRectF(hx, hy - 6, hole, hole / 2 + 6),
                   Qt.AlignmentFlag.AlignCenter, str(self._total))
        p.setFont(QtGui.QFont("Segoe UI", 8))
        p.setPen(QtGui.QColor(_TEXT_GREY))
        p.drawText(QtCore.QRectF(hx, hy + hole / 2 - 10, hole, 16),
                   Qt.AlignmentFlag.AlignCenter, self._centre_label)
        p.end()


# ==============================================================================
# GAUGE PERCENT  (Clearance Completion Rate — progress-ring style donut)
# ==============================================================================
class _GaugePercent(QtWidgets.QWidget):
    def __init__(self, percent: float, colour: str, label: str = "Completed",
                 track_colour: str = "#e5e7eb", parent=None):
        super().__init__(parent)
        self.setMinimumSize(140, 140)
        self._pct = max(0.0, min(100.0, percent))
        self._colour = colour
        self._track = track_colour
        self._label = label

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        w, h = self.width(), self.height()
        size = min(w, h) - 14
        x = (w - size) // 2
        y = (h - size) // 2
        rect = QtCore.QRectF(x, y, size, size)

        p.setPen(Qt.PenStyle.NoPen)
        p.setBrush(QtGui.QColor(self._track))
        p.drawPie(rect, 0, 360 * 16)

        span = int(round(self._pct / 100 * 360 * 16))
        p.setBrush(QtGui.QColor(self._colour))
        p.drawPie(rect, 90 * 16, -span)

        hole = size * 0.62
        hx = (w - hole) / 2
        hy = (h - hole) / 2
        p.setBrush(QtGui.QColor(_WHITE))
        p.drawEllipse(QtCore.QRectF(hx, hy, hole, hole))

        p.setPen(QtGui.QColor(_TEXT_DARK))
        p.setFont(QtGui.QFont("Segoe UI", 17, QtGui.QFont.Weight.Bold))
        p.drawText(QtCore.QRectF(hx, hy - 6, hole, hole / 2 + 6),
                   Qt.AlignmentFlag.AlignCenter, f"{self._pct:.2f}%")
        p.setFont(QtGui.QFont("Segoe UI", 8))
        p.setPen(QtGui.QColor(_TEXT_GREY))
        p.drawText(QtCore.QRectF(hx, hy + hole / 2 - 10, hole, 16),
                   Qt.AlignmentFlag.AlignCenter, self._label)
        p.end()


# ==============================================================================
# MULTI-LINE CHART  (Clearance Status Trend)
# ==============================================================================
class _MultiLineChart(QtWidgets.QWidget):
    def __init__(self, x_labels: list, series: list, y_max: int = 25,
                 y_step: int = 5, parent=None):
        super().__init__(parent)
        self.setMinimumSize(240, 150)
        self._x_labels = x_labels
        self._series = series          # list of (name, colour, values)
        self._y_max = y_max
        self._y_step = y_step

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        w, h = self.width(), self.height()
        m_left, m_right, m_top, m_bottom = 22, 8, 8, 20
        plot_w = w - m_left - m_right
        plot_h = h - m_top - m_bottom

        steps = self._y_max // self._y_step
        font_sm = QtGui.QFont("Segoe UI", 8)
        p.setFont(font_sm)
        for i in range(steps + 1):
            val = i * self._y_step
            gy = m_top + plot_h - (val / self._y_max) * plot_h
            p.setPen(QtGui.QColor(_BORDER))
            p.drawLine(QtCore.QPointF(m_left, gy), QtCore.QPointF(w - m_right, gy))
            p.setPen(QtGui.QColor(_TEXT_GREY))
            p.drawText(QtCore.QRectF(0, gy - 7, m_left - 4, 14),
                       Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter, str(val))

        n = len(self._x_labels)
        if n < 2:
            p.end()
            return
        step_x = plot_w / (n - 1)

        def xy(i, val):
            gx = m_left + i * step_x
            gy = m_top + plot_h - (val / self._y_max) * plot_h
            return QtCore.QPointF(gx, gy)

        for _, colour, values in self._series:
            pts = [xy(i, v) for i, v in enumerate(values)]
            p.setPen(QtGui.QPen(QtGui.QColor(colour), 2))
            for i in range(len(pts) - 1):
                p.drawLine(pts[i], pts[i + 1])
            p.setBrush(QtGui.QColor(_WHITE))
            p.setPen(QtGui.QPen(QtGui.QColor(colour), 2))
            for pt in pts:
                p.drawEllipse(pt, 3, 3)

        p.setPen(QtGui.QColor(_TEXT_GREY))
        p.setFont(font_sm)
        for i, label in enumerate(self._x_labels):
            gx = m_left + i * step_x
            p.drawText(QtCore.QRectF(gx - 18, m_top + plot_h + 4, 36, 14),
                       Qt.AlignmentFlag.AlignCenter, label)
        p.end()


# ==============================================================================
# NEW / EDIT CLEARANCE DIALOG
# ==============================================================================
class NewClearanceDialog(QtWidgets.QDialog):
    clearance_saved = QtCore.pyqtSignal(dict)

    def __init__(self, parent=None, data: dict = None):
        super().__init__(parent)
        self._edit = data is not None
        self.setWindowTitle("Edit Clearance" if self._edit else "New Clearance")
        self.setModal(True)
        self.setFixedSize(500, 540)
        self.setStyleSheet(f"""
            QDialog {{ background:{_WHITE}; font-family:'Segoe UI',Arial; }}
            QLabel#hdrTitle {{ color:{_TEXT_DARK}; font-size:15px; font-weight:bold; }}
            QLabel#hdrSub   {{ color:{_TEXT_GREY}; font-size:12px; }}
            QLabel#fldLbl   {{ color:{_TEXT_MID};  font-size:12px; font-weight:600; }}
            QLineEdit, QComboBox {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:7px 10px; font-size:12px;
                color:{_TEXT_DARK}; background:#f9fafb;
            }}
            QLineEdit:focus, QComboBox:focus {{
                border:1.5px solid {_ACCENT}; background:{_WHITE};
            }}
            QPushButton#cancelBtn {{
                background:{_WHITE}; border:1px solid {_BORDER};
                border-radius:6px; padding:8px 22px;
                font-size:12px; color:{_TEXT_MID};
            }}
            QPushButton#cancelBtn:hover {{ background:#f9fafb; }}
            QPushButton#saveBtn {{
                background:{_ACCENT}; border:none; border-radius:6px;
                padding:8px 26px; font-size:12px;
                font-weight:bold; color:{_WHITE};
            }}
            QPushButton#saveBtn:hover {{ background:#4a60ee; }}
            QFrame#div {{ border:none; border-top:1px solid {_BORDER}; }}
        """)

        root = QtWidgets.QVBoxLayout(self)
        root.setContentsMargins(26, 22, 26, 18)
        root.setSpacing(0)

        hhl = QtWidgets.QHBoxLayout()
        ico = QtWidgets.QLabel("🛡️")
        ico.setFixedSize(40, 40)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:#ede9fe;border-radius:20px;font-size:18px;")
        hvl = QtWidgets.QVBoxLayout(); hvl.setSpacing(2)
        ht = QtWidgets.QLabel("Edit Clearance" if self._edit else "New Clearance")
        ht.setObjectName("hdrTitle")
        hs = QtWidgets.QLabel("Update clearance details below." if self._edit
                              else "Fill in the details to initiate a new clearance.")
        hs.setObjectName("hdrSub")
        hvl.addWidget(ht); hvl.addWidget(hs)
        hhl.addWidget(ico); hhl.addSpacing(10)
        hhl.addLayout(hvl); hhl.addStretch()
        root.addLayout(hhl); root.addSpacing(14)

        d0 = QtWidgets.QFrame(); d0.setObjectName("div"); d0.setFixedHeight(1)
        root.addWidget(d0); root.addSpacing(14)

        def lbl(t):
            l = QtWidgets.QLabel(t); l.setObjectName("fldLbl"); return l

        form = QtWidgets.QFormLayout()
        form.setVerticalSpacing(12); form.setHorizontalSpacing(14)
        form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft)

        self.name_edit = QtWidgets.QLineEdit()
        self.name_edit.setPlaceholderText("e.g. John Kamau")
        form.addRow(lbl("Attachee Name *"), self.name_edit)

        self.dept_combo = QtWidgets.QComboBox()
        self.dept_combo.addItem("— Select Department —")
        self.dept_combo.addItems(DEPARTMENTS[1:])
        form.addRow(lbl("Department *"), self.dept_combo)

        self.type_combo = QtWidgets.QComboBox()
        self.type_combo.addItems(CLEARANCE_TYPES[1:])
        form.addRow(lbl("Clearance Type *"), self.type_combo)

        self.status_combo = QtWidgets.QComboBox()
        self.status_combo.addItems(STATUSES[1:])
        form.addRow(lbl("Status"), self.status_combo)

        self.cleared_on_edit = QtWidgets.QLineEdit()
        self.cleared_on_edit.setPlaceholderText("e.g. 25 Jun 2025  (leave blank if not cleared)")
        form.addRow(lbl("Cleared On"), self.cleared_on_edit)

        root.addLayout(form)

        if self._edit and data:
            self.name_edit.setText(data.get("name", ""))
            idx = self.dept_combo.findText(data.get("department", ""))
            if idx >= 0: self.dept_combo.setCurrentIndex(idx)
            idx = self.type_combo.findText(data.get("clearance_type", ""))
            if idx >= 0: self.type_combo.setCurrentIndex(idx)
            idx = self.status_combo.findText(data.get("status", ""))
            if idx >= 0: self.status_combo.setCurrentIndex(idx)
            cleared = data.get("cleared_on", "")
            self.cleared_on_edit.setText("" if cleared == "-" else cleared)

        root.addStretch()

        self.err_lbl = QtWidgets.QLabel("")
        self.err_lbl.setStyleSheet("color:#b91c1c;font-size:11px;")
        self.err_lbl.setVisible(False)
        root.addWidget(self.err_lbl); root.addSpacing(8)

        d1 = QtWidgets.QFrame(); d1.setObjectName("div"); d1.setFixedHeight(1)
        root.addWidget(d1); root.addSpacing(12)

        bhl = QtWidgets.QHBoxLayout(); bhl.addStretch()
        cb = QtWidgets.QPushButton("Cancel"); cb.setObjectName("cancelBtn")
        cb.setFixedHeight(36)
        cb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        cb.clicked.connect(self.reject)
        sb = QtWidgets.QPushButton(
            "💾  Save Changes" if self._edit else "✚  Initiate Clearance")
        sb.setObjectName("saveBtn"); sb.setFixedHeight(36)
        sb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        sb.clicked.connect(self._on_save)
        bhl.addWidget(cb); bhl.addSpacing(8); bhl.addWidget(sb)
        root.addLayout(bhl)

    def _on_save(self):
        name = self.name_edit.text().strip()
        dept = self.dept_combo.currentText()
        errs = []
        if not name: errs.append("Attachee Name is required.")
        if dept.startswith("—"): errs.append("Select a Department.")
        if errs:
            self.err_lbl.setText("⚠  " + "  •  ".join(errs))
            self.err_lbl.setVisible(True)
            return
        self.err_lbl.setVisible(False)
        self.clearance_saved.emit({
            "name": name, "department": dept,
            "clearance_type": self.type_combo.currentText(),
            "status": self.status_combo.currentText(),
            "cleared_on": self.cleared_on_edit.text().strip() or "-",
        })
        self.accept()


# ==============================================================================
# CLEARANCES PAGE
# ==============================================================================
class ClearancesPage(QtWidgets.QWidget):
    """
    Full Clearances page — slots into the Industrial Attachment sub-tab stack
    (or stackedWidget_2 index 6).

    Layout
    ──────
    Left scroll area
      • Page header + breadcrumb
      • 5 stat cards (Total / Cleared / In Progress / Pending / Not Cleared)
      • Filter row (Status / Department / Type / Date Range / Search / Actions)
      • Clearances List section: table + pagination
      • Bottom analytics row: dept bars | status trend | avg time | completion gauge
    Right panel (fixed 280px)
      • Clearance Overview donut
      • Clearance Types breakdown
      • Quick Actions
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("Clearances_Page")
        self.setStyleSheet(f"background:{_BG};")
        self._clearances = list(SAMPLE_CLEARANCES)
        self._build_ui()
        self._populate_table()

    # ──────────────────────────────────────────────────────────────────────────
    def _build_ui(self):
        outer = QtWidgets.QHBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0); outer.setSpacing(0)

        # ════════════════════ LEFT SCROLL AREA ═══════════════════════════════
        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        scroll.setStyleSheet("background:transparent;border:none;")

        lc = QtWidgets.QWidget(); lc.setStyleSheet(f"background:{_BG};")
        lv = QtWidgets.QVBoxLayout(lc)
        lv.setContentsMargins(22, 18, 14, 18); lv.setSpacing(14)

        # ── Page header ───────────────────────────────────────────────
        hdr = QtWidgets.QHBoxLayout(); hdr.setSpacing(12)
        ico = QtWidgets.QLabel("🛡️")
        ico.setFixedSize(52, 52)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:{_PURPLE};border-radius:14px;font-size:22px;")
        tvl = QtWidgets.QVBoxLayout(); tvl.setSpacing(2)
        pg_t = QtWidgets.QLabel("Clearances")
        pg_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:22px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        pg_s = QtWidgets.QLabel("Manage and monitor industrial attachee clearance process.")
        pg_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        tvl.addWidget(pg_t); tvl.addWidget(pg_s)
        hdr.addWidget(ico); hdr.addLayout(tvl); hdr.addStretch()

        breadcrumb = QtWidgets.QLabel(
            f'<span style="color:{_TEXT_GREY};">Dashboard &nbsp;›&nbsp; '
            f'Industrial Attachments &nbsp;›&nbsp;</span> '
            f'<span style="color:{_TEXT_DARK};font-weight:600;">Clearances</span>'
        )
        breadcrumb.setStyleSheet("font-size:11px;")
        hdr.addWidget(breadcrumb)
        lv.addLayout(hdr)

        # ── Stat cards ────────────────────────────────────────────────
        cards_hl = QtWidgets.QHBoxLayout(); cards_hl.setSpacing(12)
        for icon, ibg, label, val, sub in [
            ("👥", "#ede9fe", "Total Attachees", "78", "All time"),
            ("✅", "#dcfce7", "Cleared",          "46", "58.97% of total"),
            ("🕐", "#fef3c7", "In Progress",      "18", "23.08% of total"),
            ("⚠️", "#fee2e2", "Pending",          "9",  "11.54% of total"),
            ("❌", "#dbeafe", "Not Cleared",      "5",  "6.41% of total"),
        ]:
            cards_hl.addWidget(_StatCard(icon, ibg, label, val, sub))
        lv.addLayout(cards_hl)

        # ── Filter row ────────────────────────────────────────────────
        filter_hl = QtWidgets.QHBoxLayout(); filter_hl.setSpacing(12)

        for combo_lbl, items, attr in [
            ("Clearance Status", STATUSES,        "_status_combo"),
            ("Department",       DEPARTMENTS,     "_dept_combo"),
            ("Clearance Type",   CLEARANCE_TYPES, "_type_combo"),
        ]:
            combo = QtWidgets.QComboBox()
            combo.addItems(items)
            combo.setFixedHeight(36); combo.setMinimumWidth(150)
            combo.setStyleSheet(f"""
                QComboBox {{
                    border:1px solid {_BORDER}; border-radius:6px;
                    padding:0 10px; font-size:12px;
                    color:{_TEXT_MID}; background:{_WHITE};
                }}
                QComboBox:focus {{ border:1.5px solid {_ACCENT}; }}
                QComboBox::drop-down {{ border:none; width:20px; }}
            """)
            combo.currentIndexChanged.connect(self._apply_filters)
            setattr(self, attr, combo)
            lbl_vl = QtWidgets.QVBoxLayout(); lbl_vl.setSpacing(3)
            ll = QtWidgets.QLabel(combo_lbl)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;font-weight:600;")
            lbl_vl.addWidget(ll); lbl_vl.addWidget(combo)
            filter_hl.addLayout(lbl_vl)

        date_vl = QtWidgets.QVBoxLayout(); date_vl.setSpacing(3)
        dl = QtWidgets.QLabel("Date Range")
        dl.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;font-weight:600;")
        self.date_range_btn = QtWidgets.QPushButton("📅  01 Jan 2025 - 22 Jun 2025")
        self.date_range_btn.setFixedHeight(36)
        self.date_range_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        self.date_range_btn.setStyleSheet(f"""
            QPushButton {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 10px; font-size:12px; text-align:left;
                color:{_TEXT_MID}; background:{_WHITE};
            }}
            QPushButton:hover {{ background:#f9fafb; }}
        """)
        date_vl.addWidget(dl); date_vl.addWidget(self.date_range_btn)
        filter_hl.addLayout(date_vl)

        self.search_edit = QtWidgets.QLineEdit()
        self.search_edit.setPlaceholderText("🔍  Search attachees...")
        self.search_edit.setFixedHeight(36)
        self.search_edit.setMinimumWidth(180)
        self.search_edit.setStyleSheet(f"""
            QLineEdit {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 12px; font-size:12px;
                color:{_TEXT_MID}; background:{_WHITE};
            }}
            QLineEdit:focus {{ border:1.5px solid {_ACCENT}; }}
        """)
        self.search_edit.textChanged.connect(self._apply_filters)
        search_vl = QtWidgets.QVBoxLayout(); search_vl.setSpacing(3)
        search_vl.addSpacing(15)
        search_vl.addWidget(self.search_edit)
        filter_hl.addLayout(search_vl)
        filter_hl.addStretch()

        btn_vl = QtWidgets.QVBoxLayout(); btn_vl.setSpacing(3)
        btn_vl.addSpacing(15)
        btn_row = QtWidgets.QHBoxLayout(); btn_row.setSpacing(8)
        self.filter_btn = _outline_btn("▽  Filter")
        self.export_btn = _outline_btn("↓  Export")
        self.add_btn    = _primary_btn("＋  New Clearance")
        self.filter_btn.setFixedHeight(36)
        self.export_btn.setFixedHeight(36)
        self.add_btn.setFixedHeight(36)
        self.filter_btn.clicked.connect(self._on_filter_menu)
        self.export_btn.clicked.connect(self._on_export)
        self.add_btn.clicked.connect(self._on_add)
        btn_row.addWidget(self.filter_btn)
        btn_row.addWidget(self.export_btn)
        btn_row.addWidget(self.add_btn)
        btn_vl.addLayout(btn_row)
        filter_hl.addLayout(btn_vl)
        lv.addLayout(filter_hl)

        # ── Section title ─────────────────────────────────────────────
        sec_vl = QtWidgets.QVBoxLayout(); sec_vl.setSpacing(2)
        sec_t = QtWidgets.QLabel("Clearances List")
        sec_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:14px;font-weight:bold;"
                            "font-family:'Segoe UI',Arial;")
        sec_s = QtWidgets.QLabel("View and manage all industrial attachee clearances.")
        sec_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        sec_vl.addWidget(sec_t); sec_vl.addWidget(sec_s)
        lv.addLayout(sec_vl)

        # ── Table card ────────────────────────────────────────────────
        tcard = _card()
        tcvl = QtWidgets.QVBoxLayout(tcard)
        tcvl.setContentsMargins(0, 0, 0, 0); tcvl.setSpacing(0)

        self.table = QtWidgets.QTableWidget()
        self.table.setColumnCount(9)
        self.table.setHorizontalHeaderLabels([
            "#", "Attachee", "Reg. No.", "Department", "Clearance Type",
            "Requested On", "Status", "Cleared On", "Actions"
        ])
        self.table.setShowGrid(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.verticalHeader().setVisible(False)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)

        for i, w in enumerate([28, 145, 90, 150, 130, 100, 95, 95, 110]):
            self.table.setColumnWidth(i, w)
        self.table.horizontalHeader().setSectionResizeMode(
            1, QtWidgets.QHeaderView.ResizeMode.Stretch)

        self.table.setStyleSheet(f"""
            QTableWidget {{
                border:none; background:{_WHITE};
                alternate-background-color:#fafbfc;
                font-size:12px; color:{_TEXT_MID};
                font-family:'Segoe UI',Arial; outline:none;
            }}
            QTableWidget::item {{
                padding:4px 6px; border-bottom:1px solid #f3f4f6;
            }}
            QTableWidget::item:selected {{
                background:#eff6ff; color:{_TEXT_DARK};
            }}
            QHeaderView::section {{
                background:#f9fafb; color:{_TEXT_GREY};
                font-size:10px; font-weight:bold;
                border:none; border-bottom:1px solid {_BORDER}; padding:8px 6px;
            }}
            QScrollBar:vertical {{
                border:none; background:#f0f2f5;
                width:7px; border-radius:3px;
            }}
            QScrollBar::handle:vertical {{
                background:#d1d5db; border-radius:3px;
            }}
        """)
        tcvl.addWidget(self.table)

        # Pagination bar
        pg_bar = QtWidgets.QWidget()
        pg_bar.setFixedHeight(46)
        pg_bar.setStyleSheet(f"""
            QWidget {{
                background:{_WHITE};
                border-top:1px solid {_BORDER};
                border-bottom-left-radius:10px;
                border-bottom-right-radius:10px;
            }}
        """)
        pg_hl = QtWidgets.QHBoxLayout(pg_bar)
        pg_hl.setContentsMargins(14, 0, 14, 0); pg_hl.setSpacing(4)
        self.showing_lbl = QtWidgets.QLabel("Showing 1 to 10 of 78 clearances")
        self.showing_lbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(self.showing_lbl); pg_hl.addStretch()

        for txt, act in [("«", False), ("‹", False), ("1", True), ("2", False),
                         ("3", False), ("4", False), ("5", False), ("…", None),
                         ("8", False), ("›", False), ("»", False)]:
            if act is None:
                dots = QtWidgets.QLabel(txt)
                dots.setFixedSize(26, 26)
                dots.setAlignment(Qt.AlignmentFlag.AlignCenter)
                dots.setStyleSheet(f"color:{_TEXT_GREY};font-size:12px;")
                pg_hl.addWidget(dots)
                continue
            b = QtWidgets.QPushButton(txt)
            b.setFixedSize(26, 26)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{"#1e3a6e" if act else _WHITE};
                    color:{"#fff" if act else _TEXT_MID};
                    border:1px solid {"#1e3a6e" if act else _BORDER};
                    border-radius:4px; font-size:11px;
                }}
                QPushButton:hover {{
                    background:{"#254d91" if act else "#f9fafb"};
                }}
            """)
            pg_hl.addWidget(b)

        pg_hl.addSpacing(10)
        pp = QtWidgets.QLabel("10 / page  ▾")
        pp.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(pp)
        tcvl.addWidget(pg_bar)
        lv.addWidget(tcard)

        # ── Bottom analytics row ──────────────────────────────────────
        bot = QtWidgets.QHBoxLayout(); bot.setSpacing(12)

        # Clearances by Department (horizontal bars)
        dept = _card()
        dp_vl = QtWidgets.QVBoxLayout(dept)
        dp_vl.setContentsMargins(14, 14, 14, 12); dp_vl.setSpacing(6)
        dp_t = QtWidgets.QLabel("Clearances by Department")
        dp_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        dp_vl.addWidget(dp_t)
        max_dept = max(v for _, v, _ in DEPT_BARS)
        for name, val, col in DEPT_BARS:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            nl = QtWidgets.QLabel(name)
            nl.setFixedWidth(118)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:9px;")
            bar_bg = QtWidgets.QFrame()
            bar_bg.setFixedHeight(9)
            bar_bg.setStyleSheet("background:#f3f4f6;border-radius:4px;")
            bar_hl = QtWidgets.QHBoxLayout(bar_bg)
            bar_hl.setContentsMargins(0, 0, 0, 0); bar_hl.setSpacing(0)
            fill = QtWidgets.QFrame()
            fill.setFixedHeight(9)
            fill.setStyleSheet(f"background:{col};border-radius:4px;")
            pct = int(val / max_dept * 100)
            bar_hl.addWidget(fill, stretch=pct)
            bar_hl.addStretch(100 - pct)
            vlbl = QtWidgets.QLabel(f"{val} ({val/DEPT_TOTAL*100:.2f}%)")
            vlbl.setFixedWidth(74)
            vlbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            vlbl.setAlignment(Qt.AlignmentFlag.AlignRight)
            row.addWidget(nl); row.addWidget(bar_bg, stretch=1); row.addWidget(vlbl)
            dp_vl.addLayout(row)
        dp_vl.addSpacing(2)
        total_row = QtWidgets.QHBoxLayout()
        total_lbl = QtWidgets.QLabel("Total")
        total_lbl.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:bold;")
        total_val = QtWidgets.QLabel(f"{DEPT_TOTAL} (100%)")
        total_val.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:bold;")
        total_val.setAlignment(Qt.AlignmentFlag.AlignRight)
        total_row.addWidget(total_lbl); total_row.addStretch(); total_row.addWidget(total_val)
        dp_vl.addLayout(total_row)
        bot.addWidget(dept, stretch=4)

        # Clearance Status Trend (This Month)
        trend = _card()
        tr_vl = QtWidgets.QVBoxLayout(trend)
        tr_vl.setContentsMargins(14, 14, 14, 12); tr_vl.setSpacing(6)
        tr_t = QtWidgets.QLabel("Clearance Status Trend (This Month)")
        tr_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        tr_t.setWordWrap(True)
        tr_vl.addWidget(tr_t)
        tr_leg = QtWidgets.QHBoxLayout(); tr_leg.setSpacing(10)
        for name, colour, _vals in TREND_SERIES:
            item_hl = QtWidgets.QHBoxLayout(); item_hl.setSpacing(4)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{colour};font-size:9px;")
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:8px;")
            item_hl.addWidget(dot); item_hl.addWidget(nl)
            tr_leg.addLayout(item_hl)
        tr_leg.addStretch()
        tr_vl.addLayout(tr_leg)
        tr_vl.addWidget(_MultiLineChart(TREND_DAYS, TREND_SERIES), stretch=1)
        bot.addWidget(trend, stretch=4)

        # Average Clearance Time
        avg = _card()
        avg_vl = QtWidgets.QVBoxLayout(avg)
        avg_vl.setContentsMargins(14, 14, 14, 14); avg_vl.setSpacing(8)
        avg_t = QtWidgets.QLabel("Average Clearance Time")
        avg_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                            "font-family:'Segoe UI',Arial;")
        avg_vl.addWidget(avg_t)
        avg_vl.addStretch()
        avg_ico = QtWidgets.QLabel("🕐")
        avg_ico.setFixedSize(56, 56)
        avg_ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        avg_ico.setStyleSheet("background:#e0f2fe;border-radius:28px;font-size:24px;")
        avg_ico_row = QtWidgets.QHBoxLayout()
        avg_ico_row.setAlignment(Qt.AlignmentFlag.AlignCenter)
        avg_ico_row.addWidget(avg_ico)
        avg_vl.addLayout(avg_ico_row)
        avg_val = QtWidgets.QLabel(AVG_CLEARANCE_DAYS)
        avg_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        avg_val.setStyleSheet(f"color:{_TEXT_DARK};font-size:22px;font-weight:bold;"
                              "font-family:'Segoe UI',Arial;")
        avg_vl.addWidget(avg_val)
        avg_sub = QtWidgets.QLabel("Average time to complete clearance")
        avg_sub.setAlignment(Qt.AlignmentFlag.AlignCenter)
        avg_sub.setWordWrap(True)
        avg_sub.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
        avg_vl.addWidget(avg_sub)
        avg_trend = QtWidgets.QLabel(AVG_CLEARANCE_TREND)
        avg_trend.setAlignment(Qt.AlignmentFlag.AlignCenter)
        avg_trend.setStyleSheet("color:#15803d;font-size:9px;font-weight:600;")
        avg_vl.addWidget(avg_trend)
        avg_vl.addStretch()
        bot.addWidget(avg, stretch=2)

        # Clearance Completion Rate
        comp = _card()
        cp_vl = QtWidgets.QVBoxLayout(comp)
        cp_vl.setContentsMargins(14, 14, 14, 12); cp_vl.setSpacing(8)
        cp_t = QtWidgets.QLabel("Clearance Completion Rate")
        cp_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        cp_t.setWordWrap(True)
        cp_vl.addWidget(cp_t)
        cp_gauge_row = QtWidgets.QHBoxLayout()
        cp_gauge_row.setAlignment(Qt.AlignmentFlag.AlignCenter)
        cp_gauge = _GaugePercent(COMPLETION_PCT, "#10b981", "Completed")
        cp_gauge.setFixedSize(120, 120)
        cp_gauge_row.addWidget(cp_gauge)
        cp_vl.addLayout(cp_gauge_row)
        cp_stats = QtWidgets.QHBoxLayout(); cp_stats.setSpacing(10)
        cs1 = QtWidgets.QLabel(f"● {COMPLETION_CLEARED} Cleared")
        cs1.setStyleSheet("color:#10b981;font-size:9px;font-weight:600;")
        cs2 = QtWidgets.QLabel(f"● {COMPLETION_NOT_CLEARED} Not Cleared")
        cs2.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;font-weight:600;")
        cp_stats.addWidget(cs1); cp_stats.addWidget(cs2); cp_stats.addStretch()
        cp_vl.addLayout(cp_stats)
        cp_trend = QtWidgets.QLabel(COMPLETION_TREND)
        cp_trend.setStyleSheet("color:#15803d;font-size:9px;font-weight:600;")
        cp_vl.addWidget(cp_trend)
        bot.addWidget(comp, stretch=3)

        lv.addLayout(bot)
        lv.addStretch()
        scroll.setWidget(lc)
        outer.addWidget(scroll, stretch=1)

        # ════════════════════ RIGHT PANEL ════════════════════════════════════
        rp = QtWidgets.QWidget()
        rp.setFixedWidth(280)
        rp.setStyleSheet(f"background:{_BG};border-left:1px solid {_BORDER};")

        rp_scroll = QtWidgets.QScrollArea()
        rp_scroll.setWidgetResizable(True)
        rp_scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        rp_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        rp_scroll.setStyleSheet("background:transparent;border:none;")

        ri = QtWidgets.QWidget(); ri.setStyleSheet(f"background:{_BG};")
        rv = QtWidgets.QVBoxLayout(ri)
        rv.setContentsMargins(12, 16, 12, 16); rv.setSpacing(12)

        # ── Clearance Overview donut ──────────────────────────────────
        ov = _card()
        ov_vl = QtWidgets.QVBoxLayout(ov)
        ov_vl.setContentsMargins(14, 14, 14, 14); ov_vl.setSpacing(10)
        ov_t = QtWidgets.QLabel("Clearance Overview")
        ov_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        ov_vl.addWidget(ov_t)

        ov_row = QtWidgets.QHBoxLayout(); ov_row.setSpacing(12)
        ov_donut = _DonutChart(OVERVIEW_SLICES)
        ov_donut.setFixedSize(120, 120)
        ov_row.addWidget(ov_donut)

        leg_vl = QtWidgets.QVBoxLayout(); leg_vl.setSpacing(7)
        leg_vl.setAlignment(Qt.AlignmentFlag.AlignVCenter)
        total_ov = sum(v for _, v, _ in OVERVIEW_SLICES)
        for name, val, col in OVERVIEW_SLICES:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            dot = QtWidgets.QLabel("●")
            dot.setStyleSheet(f"color:{col};font-size:11px;")
            dot.setFixedWidth(12)
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_MID};font-size:10px;")
            pct = f"{val} ({val/total_ov*100:.2f}%)"
            vr = QtWidgets.QLabel(pct)
            vr.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            row.addWidget(dot); row.addWidget(nl); row.addStretch(); row.addWidget(vr)
            leg_vl.addLayout(row)
        ov_row.addLayout(leg_vl)
        ov_vl.addLayout(ov_row)
        rv.addWidget(ov)

        # ── Clearance Types breakdown ─────────────────────────────────
        ct = _card()
        ct_vl = QtWidgets.QVBoxLayout(ct)
        ct_vl.setContentsMargins(14, 14, 14, 14); ct_vl.setSpacing(10)
        ct_t = QtWidgets.QLabel("Clearance Types")
        ct_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        ct_vl.addWidget(ct_t)

        type_bg = ["#eff0ff", "#dcfce7", "#fef3c7", "#dbeafe"]
        for i, (name, icon, val, pct) in enumerate(CLEARANCE_TYPE_BREAKDOWN):
            row = QtWidgets.QHBoxLayout(); row.setSpacing(8)
            il = QtWidgets.QLabel(icon)
            il.setFixedSize(28, 28)
            il.setAlignment(Qt.AlignmentFlag.AlignCenter)
            il.setStyleSheet(f"background:{type_bg[i % len(type_bg)]};"
                             "border-radius:7px;font-size:13px;")
            nl = QtWidgets.QLabel(name)
            nl.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:600;")
            vr = QtWidgets.QLabel(f"{val} ({pct})")
            vr.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            vr.setAlignment(Qt.AlignmentFlag.AlignRight)
            row.addWidget(il); row.addWidget(nl, stretch=1); row.addWidget(vr)
            ct_vl.addLayout(row)

        ct_vl.addSpacing(4)
        ct_div = QtWidgets.QFrame()
        ct_div.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        ct_div.setStyleSheet(f"color:{_BORDER};")
        ct_vl.addWidget(ct_div)
        ct_total_row = QtWidgets.QHBoxLayout()
        ct_total_lbl = QtWidgets.QLabel("Total")
        ct_total_lbl.setStyleSheet(f"color:{_TEXT_DARK};font-size:11px;font-weight:bold;")
        ct_total_val = QtWidgets.QLabel(f"{CLEARANCE_TYPE_TOTAL} (100%)")
        ct_total_val.setStyleSheet(f"color:{_TEXT_DARK};font-size:11px;font-weight:bold;")
        ct_total_val.setAlignment(Qt.AlignmentFlag.AlignRight)
        ct_total_row.addWidget(ct_total_lbl); ct_total_row.addStretch(); ct_total_row.addWidget(ct_total_val)
        ct_vl.addLayout(ct_total_row)
        rv.addWidget(ct)

        # ── Quick Actions ─────────────────────────────────────────────
        qa = _card()
        qa_vl = QtWidgets.QVBoxLayout(qa)
        qa_vl.setContentsMargins(14, 14, 14, 10); qa_vl.setSpacing(6)
        qa_t = QtWidgets.QLabel("Quick Actions")
        qa_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        qa_vl.addWidget(qa_t)

        for qico, qlabel, qslot in [
            ("＋", "Initiate New Clearance",  self._on_add),
            ("📋", "Clearance Checklist",     self._on_placeholder),
            ("📄", "Clearance Templates",     self._on_placeholder),
            ("📅", "Clearance Calendar",      self._on_placeholder),
            ("📊", "Generate Clearance Report", self._on_placeholder),
            ("⬇",  "Export Clearances",       self._on_export),
        ]:
            btn = QtWidgets.QPushButton(f"  {qico}   {qlabel}")
            btn.setFixedHeight(34)
            btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            btn.setStyleSheet(f"""
                QPushButton {{
                    background:transparent; color:{_ACCENT};
                    border:none; text-align:left;
                    font-size:11px; font-weight:600;
                    font-family:'Segoe UI',Arial;
                    border-bottom:1px solid {_BORDER};
                }}
                QPushButton:hover {{ background:#f9fafb; }}
            """)
            btn.clicked.connect(qslot)
            qa_vl.addWidget(btn)
        rv.addWidget(qa)
        rv.addStretch()

        rp_scroll.setWidget(ri)
        rp_vl = QtWidgets.QVBoxLayout(rp)
        rp_vl.setContentsMargins(0, 0, 0, 0)
        rp_vl.addWidget(rp_scroll)
        outer.addWidget(rp)

    # ──────────────────────────────────────────────────────────────────────────
    # TABLE POPULATION
    # ──────────────────────────────────────────────────────────────────────────
    def _populate_table(self, data: list = None):
        rows = data if data is not None else self._clearances
        self.table.setRowCount(0)
        for i, rec in enumerate(rows):
            num, name, reg_no, dept, ctype, requested_on, status, cleared_on = rec
            self.table.insertRow(i)
            self.table.setRowHeight(i, 48)

            self._set_item(i, 0, str(i + 1))

            att_w = QtWidgets.QWidget()
            aw_hl = QtWidgets.QHBoxLayout(att_w)
            aw_hl.setContentsMargins(6, 0, 6, 0); aw_hl.setSpacing(8)
            colour = AVATAR_COLOURS[i % len(AVATAR_COLOURS)]
            aw_hl.addWidget(_AvatarCircle(name, colour))
            name_lbl = QtWidgets.QLabel(name)
            name_lbl.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:600;")
            aw_hl.addWidget(name_lbl)
            aw_hl.addStretch()
            self.table.setCellWidget(i, 1, att_w)

            self._set_item(i, 2, reg_no)
            self._set_item(i, 3, dept)
            self._set_item(i, 4, ctype)
            self._set_item(i, 5, requested_on)

            fg, bg = STATUS_COLOURS.get(status, (_TEXT_MID, "#f3f4f6"))
            self.table.setCellWidget(i, 6, self._centre(_Badge(status, fg, bg)))
            self._set_item(i, 7, cleared_on)
            self.table.setCellWidget(i, 8, self._action_widget(i))

        count = len(rows)
        self.showing_lbl.setText(
            f"Showing 1 to {min(10, count)} of {count} clearances")

    def _set_item(self, row, col, text):
        it = QtWidgets.QTableWidgetItem(text)
        it.setFlags(it.flags() & ~Qt.ItemFlag.ItemIsEditable)
        self.table.setItem(row, col, it)

    @staticmethod
    def _centre(widget) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.addWidget(widget)
        hl.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        hl.setContentsMargins(6, 0, 0, 0)
        return w

    def _action_widget(self, row: int) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.setContentsMargins(4, 0, 4, 0); hl.setSpacing(3)
        for ico, tip, col, slot in [
            ("👁", "View",     "#64748b", lambda _, r=row: self._on_view(r)),
            ("✏",  "Edit",     "#2563eb", lambda _, r=row: self._on_edit(r)),
            ("⬇",  "Download", "#0d9488", lambda _, r=row: self._on_download(r)),
            ("🗑",  "Delete",   "#dc2626", lambda _, r=row: self._on_delete(r)),
        ]:
            b = QtWidgets.QPushButton(ico)
            b.setFixedSize(21, 21)
            b.setToolTip(tip)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{col}22; color:{col};
                    border:1px solid {col}44;
                    border-radius:5px; font-size:9px;
                }}
                QPushButton:hover {{ background:{col}44; }}
            """)
            b.clicked.connect(slot)
            hl.addWidget(b)
        hl.addStretch()
        return w

    # ──────────────────────────────────────────────────────────────────────────
    # SLOTS
    # ──────────────────────────────────────────────────────────────────────────
    def _apply_filters(self):
        text = self.search_edit.text().lower()
        status_f = self._status_combo.currentText()
        dept_f = self._dept_combo.currentText()
        type_f = self._type_combo.currentText()
        results = []
        for rec in self._clearances:
            num, name, reg_no, dept, ctype, requested_on, status, cleared_on = rec
            if status_f != "All Statuses" and status != status_f: continue
            if dept_f != "All Departments" and dept != dept_f: continue
            if type_f != "All Types" and ctype != type_f: continue
            if text and not any(text in v.lower() for v in
                                (name, reg_no, dept, ctype)):
                continue
            results.append(rec)
        self._populate_table(results)

    def _on_add(self):
        dlg = NewClearanceDialog(self)
        dlg.clearance_saved.connect(self._append_clearance)
        dlg.exec()

    def _append_clearance(self, data: dict):
        from datetime import date
        new_num = len(self._clearances) + 1
        reg_no = f"REG/2025/{new_num:03d}"
        self._clearances.insert(0, (
            new_num, data["name"], reg_no, data["department"],
            data["clearance_type"], date.today().strftime("%d %b %Y"),
            data["status"], data["cleared_on"]
        ))
        self._apply_filters()
        QtWidgets.QMessageBox.information(
            self, "Clearance Initiated",
            f"✅  Clearance for '{data['name']}' has been initiated successfully."
        )

    def _on_view(self, row: int):
        if row >= len(self._clearances): return
        r = self._clearances[row]
        QtWidgets.QMessageBox.information(
            self, "Clearance Details",
            f"<b>{r[1]}</b><br>Reg. No: {r[2]}<br>Department: {r[3]}<br>"
            f"Clearance Type: {r[4]}<br>Requested On: {r[5]}<br>"
            f"Status: {r[6]}<br>Cleared On: {r[7]}"
        )

    def _on_edit(self, row: int):
        if row >= len(self._clearances): return
        r = self._clearances[row]
        dlg = NewClearanceDialog(self, data={
            "name": r[1], "department": r[3], "clearance_type": r[4],
            "status": r[6], "cleared_on": r[7],
        })
        dlg.clearance_saved.connect(lambda d, rr=row: self._save_edit(rr, d))
        dlg.exec()

    def _save_edit(self, row: int, data: dict):
        old = self._clearances[row]
        self._clearances[row] = (
            old[0], data["name"], old[2], data["department"],
            data["clearance_type"], old[5], data["status"], data["cleared_on"]
        )
        self._apply_filters()

    def _on_download(self, row: int):
        if row >= len(self._clearances): return
        name = self._clearances[row][1]
        QtWidgets.QMessageBox.information(
            self, "Download Clearance Form",
            f"⬇  Clearance form for '{name}' will be downloaded once connected "
            f"to the database in the next sprint."
        )

    def _on_delete(self, row: int):
        if row >= len(self._clearances): return
        name = self._clearances[row][1]
        reply = QtWidgets.QMessageBox.question(
            self, "Delete Clearance",
            f"Delete the clearance record for <b>{name}</b>? This cannot be undone.",
            QtWidgets.QMessageBox.StandardButton.Yes |
            QtWidgets.QMessageBox.StandardButton.No,
            QtWidgets.QMessageBox.StandardButton.No,
        )
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            self._clearances.pop(row)
            self._apply_filters()

    def _on_filter_menu(self):
        QtWidgets.QMessageBox.information(
            self, "Advanced Filters",
            "Advanced filter panel will be available in the next sprint."
        )

    def _on_export(self):
        QtWidgets.QMessageBox.information(
            self, "Export",
            "Export functionality will be connected in the next sprint."
        )

    def _on_placeholder(self):
        QtWidgets.QMessageBox.information(
            self, "Coming Soon",
            "This feature will be available in the next sprint."
        )