# Form implementation generated from reading ui file 'Dashboard_Page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt

# ── Shared palette (matches the rest of the app) ────────────────────────────
_NAVY      = "#0d1b3e"
_ACCENT    = "#5870ff"
_BG        = "#f0f2f5"
_WHITE     = "#ffffff"
_BORDER    = "#e5e7eb"
_TEXT_DARK = "#1a1a2e"
_TEXT_GREY = "#6b7280"
_TEXT_MID  = "#374151"
_GREEN     = "#16a34a"
_RED       = "#dc2626"


def _card(parent=None) -> QtWidgets.QFrame:
    f = QtWidgets.QFrame(parent)
    f.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
    f.setStyleSheet(f"""
        QFrame {{
            background:{_WHITE};
            border:1px solid {_BORDER};
            border-radius:10px;
        }}
    """)
    return f


def _card_header(title: str, right_text: str = None) -> QtWidgets.QHBoxLayout:
    hl = QtWidgets.QHBoxLayout()
    t = QtWidgets.QLabel(title)
    t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                    "font-family:'Segoe UI',Arial;border:none;background:transparent;")
    hl.addWidget(t); hl.addStretch()
    if right_text:
        r = QtWidgets.QPushButton(right_text)
        r.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        r.setFlat(True)
        r.setStyleSheet(f"""
            QPushButton {{
                color:{_ACCENT}; background:transparent; border:none;
                font-size:11px; font-weight:600;
            }}
            QPushButton:hover {{ text-decoration:underline; }}
        """)
        hl.addWidget(r)
    return hl


# ==============================================================================
# STAT CARD (with trend line / link)
# ==============================================================================
class _DashStatCard(QtWidgets.QFrame):
    def __init__(self, icon, icon_bg, label, value, trend_text, trend_color,
                 parent=None):
        super().__init__(parent)
        self.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.setStyleSheet(f"""
            QFrame {{
                background:{_WHITE};
                border:1px solid {_BORDER};
                border-radius:10px;
            }}
        """)
        hl = QtWidgets.QHBoxLayout(self)
        hl.setContentsMargins(14, 12, 14, 12); hl.setSpacing(10)

        il = QtWidgets.QLabel(icon)
        il.setFixedSize(42, 42)
        il.setAlignment(Qt.AlignmentFlag.AlignCenter)
        il.setStyleSheet(f"background:{icon_bg};border-radius:21px;font-size:18px;"
                         "border:none;")

        vl = QtWidgets.QVBoxLayout(); vl.setSpacing(2)
        top = QtWidgets.QLabel(label)
        top.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;border:none;background:transparent;")
        val = QtWidgets.QLabel(value)
        val.setStyleSheet(f"color:{_TEXT_DARK};font-size:22px;font-weight:bold;"
                          "font-family:'Segoe UI',Arial;border:none;background:transparent;")
        trend = QtWidgets.QLabel(trend_text)
        trend.setStyleSheet(f"color:{trend_color};font-size:10px;font-weight:600;"
                            "border:none;background:transparent;")
        vl.addWidget(top); vl.addWidget(val); vl.addWidget(trend)
        hl.addWidget(il); hl.addLayout(vl); hl.addStretch()


# ==============================================================================
# BAR CHART — Department Performance
# ==============================================================================
class _BarChart(QtWidgets.QWidget):
    def __init__(self, data, parent=None):
        """data: list of (label, pct)"""
        super().__init__(parent)
        self._data = data
        self.setMinimumHeight(240)

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)

        w, h = self.width(), self.height()
        m_left, m_right, m_top, m_bottom = 32, 8, 24, 36
        chart_w = w - m_left - m_right
        chart_h = h - m_top - m_bottom
        max_val = 100

        # Gridlines + axis labels
        axis_font = QtGui.QFont("Segoe UI", 8)
        p.setFont(axis_font)
        for i in range(6):
            val = i * 20
            y = m_top + chart_h - (val / max_val) * chart_h
            p.setPen(QtGui.QPen(QtGui.QColor("#eef0f4"), 1))
            p.drawLine(QtCore.QPointF(m_left, y), QtCore.QPointF(w - m_right, y))
            p.setPen(QtGui.QPen(QtGui.QColor(_TEXT_GREY)))
            p.drawText(QtCore.QRectF(0, y - 8, m_left - 6, 16),
                       Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter,
                       str(val))

        n = len(self._data)
        if n == 0:
            p.end(); return
        slot_w = chart_w / n
        bar_w = min(slot_w * 0.42, 46)

        for i, (label, pct) in enumerate(self._data):
            bar_h = (pct / max_val) * chart_h
            x = m_left + i * slot_w + (slot_w - bar_w) / 2
            y = m_top + chart_h - bar_h

            grad = QtGui.QLinearGradient(0, y, 0, m_top + chart_h)
            grad.setColorAt(0, QtGui.QColor("#6d84ff"))
            grad.setColorAt(1, QtGui.QColor("#3648c9"))
            p.setPen(Qt.PenStyle.NoPen)
            p.setBrush(QtGui.QBrush(grad))
            p.drawRoundedRect(QtCore.QRectF(x, y, bar_w, bar_h), 4, 4)

            p.setPen(QtGui.QPen(QtGui.QColor(_TEXT_DARK)))
            p.setFont(QtGui.QFont("Segoe UI", 9, QtGui.QFont.Weight.Bold))
            p.drawText(QtCore.QRectF(x - 12, y - 18, bar_w + 24, 16),
                       Qt.AlignmentFlag.AlignCenter, f"{pct}%")

            p.setPen(QtGui.QPen(QtGui.QColor(_TEXT_GREY)))
            p.setFont(QtGui.QFont("Segoe UI", 8))
            label_rect = QtCore.QRectF(m_left + i * slot_w - 14, m_top + chart_h + 6,
                                       slot_w + 28, 28)
            p.drawText(label_rect,
                       int(Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignTop |
                           Qt.TextFlag.TextWordWrap),
                       label)
        p.end()


# ==============================================================================
# DONUT CHART — Task Status Overview
# ==============================================================================
class _DonutChart(QtWidgets.QWidget):
    def __init__(self, data, center_value, center_label, parent=None):
        """data: list of (label, value, color)"""
        super().__init__(parent)
        self._data = data
        self._center_value = center_value
        self._center_label = center_label
        self.setMinimumSize(170, 170)

    def paintEvent(self, event):
        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)

        side = min(self.width(), self.height()) - 12
        rect = QtCore.QRectF((self.width() - side) / 2, (self.height() - side) / 2,
                             side, side)
        thickness = side * 0.24
        inner = rect.adjusted(thickness / 2, thickness / 2,
                              -thickness / 2, -thickness / 2)

        total = sum(v for _, v, _ in self._data) or 1
        start_angle = 90 * 16
        for label, val, color in self._data:
            span = -(val / total) * 360 * 16
            pen = QtGui.QPen(QtGui.QColor(color), thickness)
            pen.setCapStyle(Qt.PenCapStyle.FlatCap)
            p.setPen(pen)
            p.drawArc(inner, int(start_angle), int(span))
            start_angle += span

        cx, cy = rect.center().x(), rect.center().y()
        p.setPen(QtGui.QColor(_TEXT_DARK))
        p.setFont(QtGui.QFont("Segoe UI", 21, QtGui.QFont.Weight.Bold))
        p.drawText(QtCore.QRectF(rect.x(), cy - 22, rect.width(), 28),
                   Qt.AlignmentFlag.AlignCenter, str(self._center_value))
        p.setPen(QtGui.QColor(_TEXT_GREY))
        p.setFont(QtGui.QFont("Segoe UI", 9))
        p.drawText(QtCore.QRectF(rect.x(), cy + 6, rect.width(), 18),
                   Qt.AlignmentFlag.AlignCenter, self._center_label)
        p.end()


def _legend_row(color, label, value, pct) -> QtWidgets.QWidget:
    w = QtWidgets.QWidget()
    hl = QtWidgets.QHBoxLayout(w)
    hl.setContentsMargins(0, 4, 0, 4); hl.setSpacing(8)

    dot = QtWidgets.QLabel()
    dot.setFixedSize(10, 10)
    dot.setStyleSheet(f"background:{color};border-radius:5px;")
    hl.addWidget(dot)

    lbl = QtWidgets.QLabel(label)
    lbl.setStyleSheet(f"color:{_TEXT_MID};font-size:12px;font-weight:600;border:none;background:transparent;")
    hl.addWidget(lbl); hl.addStretch()

    val = QtWidgets.QLabel(f"{value} ({pct}%)")
    val.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;border:none;background:transparent;")
    hl.addWidget(val)
    return w


# ==============================================================================
# LIST ROW HELPERS
# ==============================================================================
def _activity_row(icon, icon_bg, title, subtitle, time_text) -> QtWidgets.QWidget:
    w = QtWidgets.QWidget()
    hl = QtWidgets.QHBoxLayout(w)
    hl.setContentsMargins(0, 6, 0, 6); hl.setSpacing(10)

    il = QtWidgets.QLabel(icon)
    il.setFixedSize(34, 34)
    il.setAlignment(Qt.AlignmentFlag.AlignCenter)
    il.setStyleSheet(f"background:{icon_bg};border-radius:17px;font-size:14px;border:none;")
    hl.addWidget(il)

    vl = QtWidgets.QVBoxLayout(); vl.setSpacing(1)
    t = QtWidgets.QLabel(title)
    t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:600;border:none;background:transparent;")
    s = QtWidgets.QLabel(subtitle)
    s.setStyleSheet(f"color:{_TEXT_GREY};font-size:10.5px;border:none;background:transparent;")
    vl.addWidget(t); vl.addWidget(s)
    hl.addLayout(vl, 1)

    tm = QtWidgets.QLabel(time_text)
    tm.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;border:none;background:transparent;")
    tm.setAlignment(Qt.AlignmentFlag.AlignTop | Qt.AlignmentFlag.AlignRight)
    hl.addWidget(tm)
    return w


def _announcement_card(icon, bg, title, date_text, body) -> QtWidgets.QFrame:
    f = QtWidgets.QFrame()
    f.setStyleSheet(f"QFrame {{ background:{bg}; border-radius:8px; }}")
    hl = QtWidgets.QHBoxLayout(f)
    hl.setContentsMargins(10, 10, 10, 10); hl.setSpacing(10)

    il = QtWidgets.QLabel(icon)
    il.setFixedSize(30, 30)
    il.setAlignment(Qt.AlignmentFlag.AlignCenter)
    il.setStyleSheet("background:rgba(255,255,255,0.65);border-radius:15px;font-size:13px;border:none;")
    hl.addWidget(il, alignment=Qt.AlignmentFlag.AlignTop)

    vl = QtWidgets.QVBoxLayout(); vl.setSpacing(2)
    trow = QtWidgets.QHBoxLayout()
    t = QtWidgets.QLabel(title)
    t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;border:none;background:transparent;")
    d = QtWidgets.QLabel(date_text)
    d.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;border:none;background:transparent;")
    trow.addWidget(t); trow.addStretch(); trow.addWidget(d)
    b = QtWidgets.QLabel(body)
    b.setWordWrap(True)
    b.setStyleSheet(f"color:{_TEXT_MID};font-size:10.5px;border:none;background:transparent;")
    vl.addLayout(trow); vl.addWidget(b)
    hl.addLayout(vl, 1)
    return f


def _report_row(icon, icon_bg, title, subtitle, badge_text, badge_fg, badge_bg) -> QtWidgets.QWidget:
    w = QtWidgets.QWidget()
    hl = QtWidgets.QHBoxLayout(w)
    hl.setContentsMargins(0, 6, 0, 6); hl.setSpacing(10)

    il = QtWidgets.QLabel(icon)
    il.setFixedSize(32, 32)
    il.setAlignment(Qt.AlignmentFlag.AlignCenter)
    il.setStyleSheet(f"background:{icon_bg};border-radius:8px;font-size:13px;border:none;")
    hl.addWidget(il)

    vl = QtWidgets.QVBoxLayout(); vl.setSpacing(1)
    t = QtWidgets.QLabel(title)
    t.setStyleSheet(f"color:{_TEXT_DARK};font-size:11.5px;font-weight:600;border:none;background:transparent;")
    s = QtWidgets.QLabel(subtitle)
    s.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;border:none;background:transparent;")
    vl.addWidget(t); vl.addWidget(s)
    hl.addLayout(vl, 1)

    badge = QtWidgets.QLabel(badge_text)
    badge.setFixedSize(42, 20)
    badge.setAlignment(Qt.AlignmentFlag.AlignCenter)
    badge.setStyleSheet(f"color:{badge_fg};background:{badge_bg};border-radius:5px;"
                        "font-size:9px;font-weight:bold;border:none;")
    hl.addWidget(badge)

    dl = QtWidgets.QPushButton("⬇")
    dl.setFixedSize(26, 26)
    dl.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    dl.setStyleSheet(f"""
        QPushButton {{
            background:{_WHITE}; border:1px solid {_BORDER}; border-radius:5px;
            color:{_TEXT_MID}; font-size:11px;
        }}
        QPushButton:hover {{ background:#f9fafb; }}
    """)
    hl.addWidget(dl)
    return w


def _quick_action_btn(icon, icon_bg, label) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton()
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setFixedHeight(52)
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_WHITE}; border:1px solid {_BORDER};
            border-radius:8px; text-align:left; padding-left:10px;
        }}
        QPushButton:hover {{ background:#f9fafb; border-color:{_ACCENT}; }}
    """)
    hl = QtWidgets.QHBoxLayout(btn)
    hl.setContentsMargins(4, 4, 8, 4); hl.setSpacing(8)
    il = QtWidgets.QLabel(icon)
    il.setFixedSize(32, 32)
    il.setAlignment(Qt.AlignmentFlag.AlignCenter)
    il.setStyleSheet(f"background:{icon_bg};border-radius:7px;font-size:14px;border:none;")
    tl = QtWidgets.QLabel(label)
    tl.setStyleSheet(f"color:{_TEXT_DARK};font-size:11.5px;font-weight:600;border:none;background:transparent;")
    tl.setWordWrap(True)
    hl.addWidget(il); hl.addWidget(tl, 1)
    return btn


# ==============================================================================
# DASHBOARD PAGE
# ==============================================================================
class DashboardPage(QtWidgets.QWidget):
    """
    CEO Dashboard — slots into stackedWidget index 0.

    Sections
    ────────
      • Header: greeting + today's date pill
      • 6 stat cards (Users, Departments, Pending Tasks, Meetings, Visitors, Attaches)
      • Department Performance bar chart  |  Task Status Overview donut chart
      • Recent Activities | Announcements | Latest Reports
      • Quick Actions row
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("Dashboard_Page")
        self.setStyleSheet(f"background:{_BG};")
        self._build_ui()

    # ──────────────────────────────────────────────────────────────────────
    def _build_ui(self):
        outer = QtWidgets.QVBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0)

        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        scroll.setStyleSheet("background:transparent;border:none;")

        body = QtWidgets.QWidget(); body.setStyleSheet(f"background:{_BG};")
        lv = QtWidgets.QVBoxLayout(body)
        lv.setContentsMargins(22, 18, 22, 22); lv.setSpacing(14)

        # ── Header ───────────────────────────────────────────────
        hdr = QtWidgets.QHBoxLayout()
        tvl = QtWidgets.QVBoxLayout(); tvl.setSpacing(2)
        pg_t = QtWidgets.QLabel("CEO Dashboard")
        pg_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:22px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        pg_s = QtWidgets.QLabel("Welcome back, CEO! Here's what's happening in your organization.")
        pg_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11.5px;")
        tvl.addWidget(pg_t); tvl.addWidget(pg_s)
        hdr.addLayout(tvl); hdr.addStretch()

        today = QtCore.QDate.currentDate().toString("dddd, d MMMM yyyy")
        date_pill = QtWidgets.QPushButton(f"📅  {today}")
        date_pill.setFixedHeight(36)
        date_pill.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        date_pill.setStyleSheet(f"""
            QPushButton {{
                background:{_WHITE}; border:1px solid {_BORDER}; border-radius:7px;
                padding:0 14px; font-size:12px; font-weight:600; color:{_TEXT_MID};
            }}
        """)
        hdr.addWidget(date_pill, alignment=Qt.AlignmentFlag.AlignTop)
        lv.addLayout(hdr)

        # ── Stat cards ───────────────────────────────────────────
        cards_hl = QtWidgets.QHBoxLayout(); cards_hl.setSpacing(10)
        stat_defs = [
            ("👥", "#dbeafe", "Total Users",      "148", "↑ 12% from last month", _GREEN),
            ("📋", "#dcfce7", "Departments",       "12",  "No change",             _TEXT_GREY),
            ("📝", "#fef3c7", "Pending Tasks",     "37",  "↑ 8% from yesterday",   _GREEN),
            ("📅", "#ede9fe", "Meetings Today",    "6",   "View schedule",         _ACCENT),
            ("🧑‍🤝‍🧑", "#e0f7fa", "Visitors Today", "23",  "↑ 15% from yesterday",  _GREEN),
            ("🪪", "#fee2e2", "Active Attaches",   "18",  "No change",             _TEXT_GREY),
        ]
        for icon, ibg, label, val, trend, tcolor in stat_defs:
            cards_hl.addWidget(_DashStatCard(icon, ibg, label, val, trend, tcolor))
        lv.addLayout(cards_hl)

        # ── Charts row ───────────────────────────────────────────
        charts_hl = QtWidgets.QHBoxLayout(); charts_hl.setSpacing(14)

        perf_card = _card()
        perf_vl = QtWidgets.QVBoxLayout(perf_card)
        perf_vl.setContentsMargins(16, 14, 16, 12); perf_vl.setSpacing(8)
        perf_hl = _card_header("Department Performance")
        perf_hl.addSpacing(4)
        month_btn = QtWidgets.QPushButton("This Month  ▾")
        month_btn.setFixedHeight(28)
        month_btn.setStyleSheet(f"""
            QPushButton {{
                background:{_WHITE}; border:1px solid {_BORDER}; border-radius:6px;
                padding:0 10px; font-size:11px; color:{_TEXT_MID};
            }}
        """)
        perf_hl.addWidget(month_btn)
        perf_vl.addLayout(perf_hl)
        bar_data = [
            ("Executive Office", 92), ("Operations", 88), ("IT Department", 76),
            ("Human Resources", 85), ("Finance", 90), ("Marketing", 78),
        ]
        perf_vl.addWidget(_BarChart(bar_data))
        charts_hl.addWidget(perf_card, stretch=6)

        task_card = _card()
        task_vl = QtWidgets.QVBoxLayout(task_card)
        task_vl.setContentsMargins(16, 14, 16, 14); task_vl.setSpacing(8)
        task_hl = _card_header("Task Status Overview")
        week_btn = QtWidgets.QPushButton("This Week  ▾")
        week_btn.setFixedHeight(28)
        week_btn.setStyleSheet(f"""
            QPushButton {{
                background:{_WHITE}; border:1px solid {_BORDER}; border-radius:6px;
                padding:0 10px; font-size:11px; color:{_TEXT_MID};
            }}
        """)
        task_hl.addWidget(week_btn)
        task_vl.addLayout(task_hl)

        donut_hl = QtWidgets.QHBoxLayout(); donut_hl.setSpacing(6)
        donut_data = [
            ("Completed",   18, "#22c55e"),
            ("In Progress", 10, "#3b82f6"),
            ("Pending",     6,  "#f97316"),
            ("Overdue",     3,  "#ef4444"),
        ]
        donut_hl.addWidget(_DonutChart(donut_data, 37, "Total Tasks"), stretch=1)

        legend_vl = QtWidgets.QVBoxLayout(); legend_vl.setSpacing(0)
        total = sum(v for _, v, _ in donut_data)
        for label, val, color in donut_data:
            pct = round(val / total * 100, 1)
            legend_vl.addWidget(_legend_row(color, label, val, pct))
        legend_vl.addStretch()
        donut_hl.addLayout(legend_vl, stretch=1)
        task_vl.addLayout(donut_hl)
        charts_hl.addWidget(task_card, stretch=4)

        lv.addLayout(charts_hl)

        # ── Activities / Announcements / Reports row ─────────────
        row3 = QtWidgets.QHBoxLayout(); row3.setSpacing(14)

        # Recent Activities
        act_card = _card()
        act_vl = QtWidgets.QVBoxLayout(act_card)
        act_vl.setContentsMargins(16, 14, 16, 10); act_vl.setSpacing(2)
        act_vl.addLayout(_card_header("Recent Activities", "View All"))
        for icon, ibg, title, sub, time_text in [
            ("👤", "#dbeafe", "New user account created", "John Kamau was added by Admin", "10:30 AM"),
            ("📅", "#ede9fe", "Meeting scheduled", "Operations Review Meeting", "09:15 AM"),
            ("📄", "#dcfce7", "Report generated", "Monthly Performance Report", "Yesterday"),
            ("🧑", "#e0f7fa", "Visitor check-in", "James Mwangi checked in", "Yesterday"),
            ("✅", "#fef3c7", "Task completed", "Server Maintenance Completed", "Yesterday"),
        ]:
            act_vl.addWidget(_activity_row(icon, ibg, title, sub, time_text))
        act_vl.addStretch()
        row3.addWidget(act_card, stretch=1)

        # Announcements
        ann_card = _card()
        ann_vl = QtWidgets.QVBoxLayout(ann_card)
        ann_vl.setContentsMargins(16, 14, 16, 14); ann_vl.setSpacing(10)
        ann_vl.addLayout(_card_header("Announcements", "View All"))
        ann_vl.addWidget(_announcement_card(
            "📢", "#fef3c7", "System Maintenance", "21 Jun 2025",
            "Scheduled maintenance on 25th June 2025 from 10:00 PM to 2:00 AM."))
        ann_vl.addWidget(_announcement_card(
            "🛡️", "#dbeafe", "New Policy Update", "20 Jun 2025",
            "Please review the updated data security policy in the system."))
        ann_vl.addWidget(_announcement_card(
            "📗", "#dcfce7", "Quarterly Review", "19 Jun 2025",
            "Q2 Performance review meetings begin 1st July 2025."))
        ann_vl.addStretch()
        row3.addWidget(ann_card, stretch=1)

        # Latest Reports
        rep_card = _card()
        rep_vl = QtWidgets.QVBoxLayout(rep_card)
        rep_vl.setContentsMargins(16, 14, 16, 10); rep_vl.setSpacing(2)
        rep_vl.addLayout(_card_header("Latest Reports", "View All"))
        for icon, ibg, title, sub, badge, bfg, bbg in [
            ("📘", "#dbeafe", "Monthly Performance Report", "Generated on 22 Jun 2025 08:30 AM",
             "PDF", "#b91c1c", "#fee2e2"),
            ("📘", "#dbeafe", "User Activity Report", "Generated on 22 Jun 2025 07:45 AM",
             "PDF", "#b91c1c", "#fee2e2"),
            ("📗", "#dcfce7", "Department Summary Report", "Generated on 21 Jun 2025 05:20 PM",
             "XLSX", "#15803d", "#dcfce7"),
            ("📘", "#dbeafe", "Visitor Summary Report", "Generated on 21 Jun 2025 04:10 PM",
             "PDF", "#b91c1c", "#fee2e2"),
            ("📗", "#dcfce7", "Task Status Report", "Generated on 21 Jun 2025 03:15 PM",
             "XLSX", "#15803d", "#dcfce7"),
        ]:
            rep_vl.addWidget(_report_row(icon, ibg, title, sub, badge, bfg, bbg))
        rep_vl.addStretch()
        row3.addWidget(rep_card, stretch=1)

        lv.addLayout(row3)

        # ── Quick Actions ──────────────────────────────────────────
        qa_card = _card()
        qa_vl = QtWidgets.QVBoxLayout(qa_card)
        qa_vl.setContentsMargins(16, 14, 16, 16); qa_vl.setSpacing(10)
        qa_vl.addLayout(_card_header("Quick Actions"))

        qa_grid = QtWidgets.QHBoxLayout(); qa_grid.setSpacing(10)
        for icon, ibg, label, slot_name in [
            ("👤", "#dbeafe", "Add New User",     "add_user"),
            ("📅", "#ede9fe", "Schedule Meeting", "schedule_meeting"),
            ("📗", "#dcfce7", "Generate Report",  "generate_report"),
            ("📝", "#fef3c7", "View Tasks",       "view_tasks"),
            ("🧑‍🤝‍🧑", "#e0f7fa", "Manage Visitors", "manage_visitors"),
            ("⚙️", "#e5e7eb", "System Settings",  "system_settings"),
        ]:
            btn = _quick_action_btn(icon, ibg, label)
            btn.clicked.connect(lambda _, n=label: self._on_quick_action(n))
            qa_grid.addWidget(btn)
        qa_vl.addLayout(qa_grid)
        lv.addWidget(qa_card)

        scroll.setWidget(body)
        outer.addWidget(scroll)

    # ──────────────────────────────────────────────────────────────────────
    def _on_quick_action(self, name: str):
        QtWidgets.QMessageBox.information(
            self, name, f"'{name}' will be wired up to its target page next."
        )
