# Form implementation generated from reading ui file 'Departments_Page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt

# ── Shared palette (matches the rest of the app) ────────────────────────────
_NAVY      = "#0d1b3e"
_ACCENT    = "#5870ff"
_BG        = "#f0f2f5"
_WHITE     = "#ffffff"
_BORDER    = "#e5e7eb"
_TEXT_DARK = "#1a1a2e"
_TEXT_GREY = "#6b7280"
_TEXT_MID  = "#374151"

# ── Status colours ───────────────────────────────────────────────────────────
STATUS_COLOURS = {
    "Active":   ("#15803d", "#dcfce7"),
    "Inactive": ("#b91c1c", "#fee2e2"),
}

# ── Sample department data ───────────────────────────────────────────────────
# (dept_id, name, code, head, employees, status,
#  email, phone, location, created_on, description)
SAMPLE_DEPARTMENTS = [
    (1,  "Executive Office",        "EXE", "John Kamau",     8,  "Active",
     "john.kamau@company.com",     "+254 711 200 100", "Head Office, 5th Floor", "10 Jan 2024",
     "Provides overall strategic direction and executive oversight for the organization."),
    (2,  "Operations Department",   "OPS", "Mary Wanjiku",   32, "Active",
     "mary.wanjiku@company.com",   "+254 712 300 200", "Head Office, 2nd Floor", "10 Jan 2024",
     "Oversees the day-to-day operational activities and process efficiency across the company."),
    (3,  "IT Department",           "ITD", "David Mwangi",   18, "Active",
     "david.mwangi@company.com",   "+254 712 345 678", "Head Office, 3rd Floor", "15 Jan 2024",
     "Responsible for all technology related services including system administration, "
     "network management, software development and technical support."),
    (4,  "Human Resources",         "HRD", "Grace Njeri",    12, "Active",
     "grace.njeri@company.com",    "+254 713 400 300", "Head Office, 1st Floor", "15 Jan 2024",
     "Manages recruitment, employee relations, training and organizational development."),
    (5,  "Finance Department",      "FIN", "Peter Ochieng",  15, "Active",
     "peter.ochieng@company.com",  "+254 714 500 400", "Head Office, 2nd Floor", "18 Jan 2024",
     "Handles budgeting, financial reporting, payroll and accounts for the organization."),
    (6,  "Marketing Department",    "MKT", "Susan Akinyi",   14, "Active",
     "susan.akinyi@company.com",   "+254 715 600 500", "Head Office, 4th Floor", "20 Jan 2024",
     "Drives brand strategy, campaigns, communications and market research."),
    (7,  "Procurement Department",  "PRC", "James Mutua",    9,  "Active",
     "james.mutua@company.com",    "+254 716 700 600", "Annex Building, Ground Floor", "22 Jan 2024",
     "Manages vendor relationships, purchasing and supply chain logistics."),
    (8,  "Maintenance Department",  "MNT", "Joseph Kiprono", 11, "Active",
     "joseph.kiprono@company.com", "+254 717 800 700", "Annex Building, Basement", "25 Jan 2024",
     "Handles facility upkeep, equipment servicing and maintenance requests."),
    (9,  "Quality Assurance",       "QA",  "Ann Wairimu",    6,  "Active",
     "ann.wairimu@company.com",    "+254 718 900 800", "Head Office, 3rd Floor", "28 Jan 2024",
     "Ensures product and service quality through testing, audits and process reviews."),
    (10, "Legal Department",        "LEG", "Brian Otieno",   7,  "Active",
     "brian.otieno@company.com",   "+254 719 000 900", "Head Office, 5th Floor", "01 Feb 2024",
     "Provides legal counsel, contract review and regulatory compliance oversight."),
    (11, "Customer Service",        "CUS", "Lilian Moraa",   10, "Active",
     "lilian.moraa@company.com",   "+254 710 111 000", "Head Office, Ground Floor", "05 Feb 2024",
     "Manages customer inquiries, support tickets and client relationship follow-up."),
    (12, "Research & Development",  "RND", "Samson Onyango", 6,  "Inactive",
     "samson.onyango@company.com", "+254 711 222 111", "Annex Building, 2nd Floor", "10 Feb 2024",
     "Explores new products, technologies and process innovations. Currently paused pending "
     "budget review."),
]

# ==============================================================================
# BADGE helper
# ==============================================================================
class _Badge(QtWidgets.QLabel):
    def __init__(self, text: str, fg: str, bg: str, parent=None):
        super().__init__(text, parent)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setFixedHeight(20)
        self.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                           QtWidgets.QSizePolicy.Policy.Fixed)
        self.setStyleSheet(f"""
            QLabel {{
                color:{fg}; background:{bg};
                border-radius:9px; padding:0 9px;
                font-size:10px; font-weight:700;
                font-family:'Segoe UI',Arial;
            }}
        """)


def _card(parent=None) -> QtWidgets.QFrame:
    f = QtWidgets.QFrame(parent)
    f.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
    f.setStyleSheet(f"""
        QFrame {{
            background:{_WHITE};
            border:1px solid {_BORDER};
            border-radius:10px;
        }}
    """)
    return f


def _outline_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_WHITE}; color:{_TEXT_MID};
            border:1px solid {_BORDER}; border-radius:6px;
            padding:0 14px; font-size:12px;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#f9fafb; }}
    """)
    return btn


def _primary_btn(text: str) -> QtWidgets.QPushButton:
    btn = QtWidgets.QPushButton(text)
    btn.setFixedHeight(34)
    btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
    btn.setStyleSheet(f"""
        QPushButton {{
            background:{_ACCENT}; color:{_WHITE}; border:none;
            border-radius:6px; padding:0 16px;
            font-size:12px; font-weight:bold;
            font-family:'Segoe UI',Arial;
        }}
        QPushButton:hover {{ background:#4a60ee; }}
    """)
    return btn


# ==============================================================================
# STAT CARD
# ==============================================================================
class _StatCard(QtWidgets.QFrame):
    def __init__(self, icon, icon_bg, label, value, sublabel, parent=None):
        super().__init__(parent)
        self.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.setStyleSheet(f"""
            QFrame {{
                background:{_WHITE};
                border:1px solid {_BORDER};
                border-radius:10px;
            }}
        """)
        hl = QtWidgets.QHBoxLayout(self)
        hl.setContentsMargins(14, 12, 14, 12); hl.setSpacing(12)

        il = QtWidgets.QLabel(icon)
        il.setFixedSize(40, 40)
        il.setAlignment(Qt.AlignmentFlag.AlignCenter)
        il.setStyleSheet(f"background:{icon_bg};border-radius:20px;font-size:18px;")

        vl = QtWidgets.QVBoxLayout(); vl.setSpacing(2)
        top = QtWidgets.QLabel(label)
        top.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        val = QtWidgets.QLabel(value)
        val.setStyleSheet(f"color:{_TEXT_DARK};font-size:24px;font-weight:bold;"
                          "font-family:'Segoe UI',Arial;")
        sub = QtWidgets.QLabel(sublabel)
        sub.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
        vl.addWidget(top); vl.addWidget(val); vl.addWidget(sub)
        hl.addWidget(il); hl.addLayout(vl); hl.addStretch()


# ==============================================================================
# NEW / EDIT DEPARTMENT DIALOG
# ==============================================================================
class NewDepartmentDialog(QtWidgets.QDialog):
    department_saved = QtCore.pyqtSignal(dict)

    def __init__(self, parent=None, data: dict = None):
        super().__init__(parent)
        self._edit = data is not None
        self.setWindowTitle("Edit Department" if self._edit else "New Department")
        self.setModal(True); self.setFixedSize(520, 620)
        self.setStyleSheet(f"""
            QDialog {{ background:{_WHITE}; font-family:'Segoe UI',Arial; }}
            QLabel#hdrTitle {{ color:{_TEXT_DARK}; font-size:15px; font-weight:bold; }}
            QLabel#hdrSub   {{ color:{_TEXT_GREY}; font-size:12px; }}
            QLabel#fldLbl   {{ color:{_TEXT_MID};  font-size:12px; font-weight:600; }}
            QLineEdit, QComboBox, QTextEdit {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:7px 10px; font-size:12px;
                color:{_TEXT_DARK}; background:#f9fafb;
            }}
            QLineEdit:focus, QComboBox:focus, QTextEdit:focus {{
                border:1.5px solid {_ACCENT}; background:{_WHITE};
            }}
            QPushButton#cancelBtn {{
                background:{_WHITE}; border:1px solid {_BORDER};
                border-radius:6px; padding:8px 22px;
                font-size:12px; color:{_TEXT_MID};
            }}
            QPushButton#cancelBtn:hover {{ background:#f9fafb; }}
            QPushButton#saveBtn {{
                background:{_ACCENT}; border:none; border-radius:6px;
                padding:8px 26px; font-size:12px;
                font-weight:bold; color:{_WHITE};
            }}
            QPushButton#saveBtn:hover {{ background:#4a60ee; }}
            QFrame#div {{ border:none; border-top:1px solid {_BORDER}; }}
        """)

        root = QtWidgets.QVBoxLayout(self)
        root.setContentsMargins(26, 22, 26, 18); root.setSpacing(0)

        hhl = QtWidgets.QHBoxLayout()
        ico = QtWidgets.QLabel("🏢")
        ico.setFixedSize(40, 40); ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet("background:#eff0ff;border-radius:20px;font-size:18px;")
        hvl = QtWidgets.QVBoxLayout(); hvl.setSpacing(2)
        ht = QtWidgets.QLabel("Edit Department" if self._edit else "New Department")
        ht.setObjectName("hdrTitle")
        hs = QtWidgets.QLabel("Update department details." if self._edit
                              else "Fill in the details to add a new department.")
        hs.setObjectName("hdrSub")
        hvl.addWidget(ht); hvl.addWidget(hs)
        hhl.addWidget(ico); hhl.addSpacing(10); hhl.addLayout(hvl); hhl.addStretch()
        root.addLayout(hhl); root.addSpacing(14)

        d0 = QtWidgets.QFrame(); d0.setObjectName("div"); d0.setFixedHeight(1)
        root.addWidget(d0); root.addSpacing(14)

        def lbl(t):
            l = QtWidgets.QLabel(t); l.setObjectName("fldLbl"); return l

        form = QtWidgets.QFormLayout()
        form.setVerticalSpacing(12); form.setHorizontalSpacing(14)
        form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft)

        self.name_edit = QtWidgets.QLineEdit()
        self.name_edit.setPlaceholderText("e.g. IT Department")
        form.addRow(lbl("Department Name *"), self.name_edit)

        self.code_edit = QtWidgets.QLineEdit()
        self.code_edit.setPlaceholderText("e.g. ITD")
        self.code_edit.setMaxLength(6)
        form.addRow(lbl("Department Code *"), self.code_edit)

        self.head_edit = QtWidgets.QLineEdit()
        self.head_edit.setPlaceholderText("e.g. David Mwangi")
        form.addRow(lbl("Head of Department *"), self.head_edit)

        self.email_edit = QtWidgets.QLineEdit()
        self.email_edit.setPlaceholderText("e.g. david.mwangi@company.com")
        form.addRow(lbl("Email Address"), self.email_edit)

        self.phone_edit = QtWidgets.QLineEdit()
        self.phone_edit.setPlaceholderText("e.g. +254 712 345 678")
        form.addRow(lbl("Phone Number"), self.phone_edit)

        self.location_edit = QtWidgets.QLineEdit()
        self.location_edit.setPlaceholderText("e.g. Head Office, 3rd Floor")
        form.addRow(lbl("Location"), self.location_edit)

        self.employees_spin = QtWidgets.QSpinBox()
        self.employees_spin.setRange(0, 999)
        self.employees_spin.setFixedHeight(34)
        form.addRow(lbl("Number of Employees"), self.employees_spin)

        self.status_combo = QtWidgets.QComboBox()
        self.status_combo.addItems(["Active", "Inactive"])
        form.addRow(lbl("Status"), self.status_combo)

        self.desc_edit = QtWidgets.QTextEdit()
        self.desc_edit.setPlaceholderText("Briefly describe this department's function...")
        self.desc_edit.setFixedHeight(80)
        form.addRow(lbl("Description"), self.desc_edit)

        root.addLayout(form)

        if self._edit and data:
            self.name_edit.setText(data.get("name", ""))
            self.code_edit.setText(data.get("code", ""))
            self.head_edit.setText(data.get("head", ""))
            self.email_edit.setText(data.get("email", ""))
            self.phone_edit.setText(data.get("phone", ""))
            self.location_edit.setText(data.get("location", ""))
            self.employees_spin.setValue(data.get("employees", 0))
            idx = self.status_combo.findText(data.get("status", "Active"))
            if idx >= 0: self.status_combo.setCurrentIndex(idx)
            self.desc_edit.setPlainText(data.get("description", ""))

        root.addStretch()

        self.err_lbl = QtWidgets.QLabel("")
        self.err_lbl.setStyleSheet("color:#b91c1c;font-size:11px;")
        self.err_lbl.setVisible(False)
        root.addWidget(self.err_lbl); root.addSpacing(8)

        d1 = QtWidgets.QFrame(); d1.setObjectName("div"); d1.setFixedHeight(1)
        root.addWidget(d1); root.addSpacing(12)

        bhl = QtWidgets.QHBoxLayout(); bhl.addStretch()
        cb = QtWidgets.QPushButton("Cancel"); cb.setObjectName("cancelBtn")
        cb.setFixedHeight(36)
        cb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        cb.clicked.connect(self.reject)
        sb = QtWidgets.QPushButton(
            "💾  Save Changes" if self._edit else "✚  Add Department")
        sb.setObjectName("saveBtn"); sb.setFixedHeight(36)
        sb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        sb.clicked.connect(self._on_save)
        bhl.addWidget(cb); bhl.addSpacing(8); bhl.addWidget(sb)
        root.addLayout(bhl)

    def _on_save(self):
        name  = self.name_edit.text().strip()
        code  = self.code_edit.text().strip().upper()
        head  = self.head_edit.text().strip()
        email = self.email_edit.text().strip()
        errs  = []
        if not name: errs.append("Department Name required.")
        if not code: errs.append("Department Code required.")
        if not head: errs.append("Head of Department required.")
        if email and "@" not in email: errs.append("Email looks invalid.")
        if errs:
            self.err_lbl.setText("⚠  " + "  •  ".join(errs))
            self.err_lbl.setVisible(True); return
        self.err_lbl.setVisible(False)
        self.department_saved.emit({
            "name": name, "code": code, "head": head,
            "email": email, "phone": self.phone_edit.text().strip(),
            "location": self.location_edit.text().strip(),
            "employees": self.employees_spin.value(),
            "status": self.status_combo.currentText(),
            "description": self.desc_edit.toPlainText().strip(),
        })
        self.accept()


# ==============================================================================
# DEPARTMENTS PAGE
# ==============================================================================
class DepartmentsPage(QtWidgets.QWidget):
    """
    Full Departments page — slots into stackedWidget index 2.

    Layout
    ──────
    Left area (scroll)
      • Page header + Add Department button
      • 5 stat cards
      • Departments List section: search / filter / export / add + table + pagination
    Right panel (fixed 268px)
      • Department Details card for the selected department
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("Departments_Page")
        self.setStyleSheet(f"background:{_BG};")
        self._departments = list(SAMPLE_DEPARTMENTS)
        self._build_ui()
        self._populate_table()
        if self._departments:
            self._show_details(2 if len(self._departments) > 2 else 0)

    # ──────────────────────────────────────────────────────────────────────────
    def _build_ui(self):
        outer = QtWidgets.QHBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0); outer.setSpacing(0)

        # ════════════════════ LEFT SCROLL AREA ═══════════════════════════════
        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        scroll.setStyleSheet("background:transparent;border:none;")

        lc = QtWidgets.QWidget(); lc.setStyleSheet(f"background:{_BG};")
        lv = QtWidgets.QVBoxLayout(lc)
        lv.setContentsMargins(22, 18, 14, 18); lv.setSpacing(14)

        # ── Page header ───────────────────────────────────────────────
        hdr = QtWidgets.QHBoxLayout(); hdr.setSpacing(12)
        ico = QtWidgets.QLabel("📋")
        ico.setFixedSize(44, 44); ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:{_ACCENT};border-radius:22px;font-size:20px;")
        tvl = QtWidgets.QVBoxLayout(); tvl.setSpacing(2)
        pg_t = QtWidgets.QLabel("Departments")
        pg_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:20px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        pg_s = QtWidgets.QLabel("Manage and organize all departments in the organization.")
        pg_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        tvl.addWidget(pg_t); tvl.addWidget(pg_s)
        hdr.addWidget(ico); hdr.addLayout(tvl); hdr.addStretch()

        breadcrumb = QtWidgets.QLabel("Dashboard  ›  Departments")
        breadcrumb.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        hdr.addWidget(breadcrumb)
        lv.addLayout(hdr)

        # ── Stat cards ────────────────────────────────────────────────
        cards_hl = QtWidgets.QHBoxLayout(); cards_hl.setSpacing(10)
        for icon, ibg, label, val, sub in [
            ("🏢","#eff0ff","Total Departments",   "12", "All departments"),
            ("✅","#dcfce7","Active Departments",  "11", "Currently operational"),
            ("⏸️","#fef3c7","Inactive Departments","1",  "Not operational"),
            ("👥","#ede9fe","Total Employees",     "148","Across all departments"),
            ("🎖️","#e0f7fa","Department Heads",    "12", "Assigned heads"),
        ]:
            cards_hl.addWidget(_StatCard(icon, ibg, label, val, sub))
        lv.addLayout(cards_hl)

        # ── Section header row (title + filter bar) ─────────────────────
        sec_hl = QtWidgets.QHBoxLayout(); sec_hl.setSpacing(10)
        sec_vl = QtWidgets.QVBoxLayout(); sec_vl.setSpacing(2)
        sec_t = QtWidgets.QLabel("Departments List")
        sec_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:14px;font-weight:bold;"
                            "font-family:'Segoe UI',Arial;")
        sec_s = QtWidgets.QLabel("View, search and manage all departments")
        sec_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        sec_vl.addWidget(sec_t); sec_vl.addWidget(sec_s)
        sec_hl.addLayout(sec_vl); sec_hl.addStretch()

        self.search_edit = QtWidgets.QLineEdit()
        self.search_edit.setPlaceholderText("🔍  Search departments...")
        self.search_edit.setFixedHeight(34)
        self.search_edit.setMinimumWidth(220)
        self.search_edit.setStyleSheet(f"""
            QLineEdit {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 12px; font-size:12px;
                color:{_TEXT_MID}; background:{_WHITE};
            }}
            QLineEdit:focus {{ border:1.5px solid {_ACCENT}; }}
        """)
        self.search_edit.textChanged.connect(self._apply_filters)

        self.filter_btn = _outline_btn("▽  Filter")
        self.export_btn = _outline_btn("↓  Export")
        self.add_btn    = _primary_btn("＋  Add Department")
        self.filter_btn.clicked.connect(self._on_filter_menu)
        self.export_btn.clicked.connect(self._on_export)
        self.add_btn.clicked.connect(self._on_add_department)

        sec_hl.addWidget(self.search_edit)
        sec_hl.addWidget(self.filter_btn)
        sec_hl.addWidget(self.export_btn)
        sec_hl.addWidget(self.add_btn)
        lv.addLayout(sec_hl)

        # ── Table card ────────────────────────────────────────────────
        tcard = _card()
        tc_vl = QtWidgets.QVBoxLayout(tcard)
        tc_vl.setContentsMargins(0, 0, 0, 0); tc_vl.setSpacing(0)

        self.table = QtWidgets.QTableWidget()
        self.table.setColumnCount(7)
        self.table.setHorizontalHeaderLabels([
            "#","Department Name","Department Code","Head of Department",
            "Employees","Status","Actions"
        ])
        self.table.setShowGrid(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.verticalHeader().setVisible(False)
        self.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)

        for i, w in enumerate([34, 210, 130, 170, 95, 90, 110]):
            self.table.setColumnWidth(i, w)
        self.table.horizontalHeader().setSectionResizeMode(
            1, QtWidgets.QHeaderView.ResizeMode.Stretch)

        self.table.setStyleSheet(f"""
            QTableWidget {{
                border:none; background:{_WHITE};
                alternate-background-color:#fafbfc;
                font-size:12px; color:{_TEXT_MID};
                font-family:'Segoe UI',Arial; outline:none;
            }}
            QTableWidget::item {{
                padding:4px 6px; border-bottom:1px solid #f3f4f6;
            }}
            QTableWidget::item:selected {{
                background:#eff6ff; color:{_TEXT_DARK};
            }}
            QHeaderView::section {{
                background:#f9fafb; color:{_TEXT_GREY};
                font-size:10px; font-weight:bold;
                border:none; border-bottom:1px solid {_BORDER}; padding:7px;
            }}
            QScrollBar:vertical {{
                border:none; background:#f0f2f5;
                width:7px; border-radius:3px;
            }}
            QScrollBar::handle:vertical {{
                background:#d1d5db; border-radius:3px;
            }}
        """)
        self.table.cellClicked.connect(self._on_row_click)
        tc_vl.addWidget(self.table)

        # Pagination
        pg = QtWidgets.QWidget(); pg.setFixedHeight(44)
        pg.setStyleSheet(f"""
            QWidget {{
                background:{_WHITE};
                border-top:1px solid {_BORDER};
                border-bottom-left-radius:10px;
                border-bottom-right-radius:10px;
            }}
        """)
        pg_hl = QtWidgets.QHBoxLayout(pg)
        pg_hl.setContentsMargins(14, 0, 14, 0); pg_hl.setSpacing(4)
        self.showing_lbl = QtWidgets.QLabel("Showing 1 to 12 of 12 departments")
        self.showing_lbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(self.showing_lbl); pg_hl.addStretch()
        for txt, act in [("«",False),("‹",False),("1",True),("›",False),("»",False)]:
            b = QtWidgets.QPushButton(txt); b.setFixedSize(26, 26)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{"#1e3a6e" if act else _WHITE};
                    color:{"#fff" if act else _TEXT_MID};
                    border:1px solid {"#1e3a6e" if act else _BORDER};
                    border-radius:4px; font-size:11px;
                }}
                QPushButton:hover {{
                    background:{"#254d91" if act else "#f9fafb"};
                }}
            """)
            pg_hl.addWidget(b)
        pg_hl.addSpacing(10)
        pp = QtWidgets.QLabel("10 / page  ▾")
        pp.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        pg_hl.addWidget(pp)
        tc_vl.addWidget(pg)
        lv.addWidget(tcard)
        lv.addStretch()

        scroll.setWidget(lc)
        outer.addWidget(scroll, stretch=1)

        # ════════════════════ RIGHT PANEL ════════════════════════════════════
        rp = QtWidgets.QWidget()
        rp.setFixedWidth(268)
        rp.setStyleSheet(f"background:{_BG};border-left:1px solid {_BORDER};")

        rp_scroll = QtWidgets.QScrollArea()
        rp_scroll.setWidgetResizable(True)
        rp_scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        rp_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        rp_scroll.setStyleSheet("background:transparent;border:none;")

        ri = QtWidgets.QWidget(); ri.setStyleSheet(f"background:{_BG};")
        rv = QtWidgets.QVBoxLayout(ri)
        rv.setContentsMargins(10, 16, 10, 16); rv.setSpacing(12)

        # ── Department Details card ───────────────────────────────────
        dd_card = _card()
        self._dd_vl = QtWidgets.QVBoxLayout(dd_card)
        self._dd_vl.setContentsMargins(14, 14, 14, 14); self._dd_vl.setSpacing(10)
        rv.addWidget(dd_card)
        rv.addStretch()

        rp_scroll.setWidget(ri)
        rp_vl = QtWidgets.QVBoxLayout(rp)
        rp_vl.setContentsMargins(0, 0, 0, 0)
        rp_vl.addWidget(rp_scroll)
        outer.addWidget(rp)

    # ──────────────────────────────────────────────────────────────────────────
    # TABLE POPULATION
    # ──────────────────────────────────────────────────────────────────────────
    def _populate_table(self, data: list = None):
        rows = data if data is not None else self._departments
        self.table.setRowCount(0)
        for i, dept in enumerate(rows):
            dept_id, name, code, head, employees, status = dept[0:6]
            self.table.insertRow(i)
            self.table.setRowHeight(i, 46)

            self._set_item(i, 0, str(i + 1))

            name_item = QtWidgets.QTableWidgetItem(name)
            name_item.setFlags(name_item.flags() & ~Qt.ItemFlag.ItemIsEditable)
            name_item.setFont(QtGui.QFont("Segoe UI", 11, QtGui.QFont.Weight.Bold))
            self.table.setItem(i, 1, name_item)

            self._set_item(i, 2, code)
            self._set_item(i, 3, head)
            self._set_item(i, 4, str(employees))

            fg, bg = STATUS_COLOURS.get(status, (_TEXT_MID, "#f3f4f6"))
            self.table.setCellWidget(i, 5, self._centre(_Badge(status, fg, bg)))
            self.table.setCellWidget(i, 6, self._action_widget(i))

        count = len(rows)
        self.showing_lbl.setText(
            f"Showing 1 to {count} of {count} departments")

    def _set_item(self, row, col, text):
        it = QtWidgets.QTableWidgetItem(text)
        it.setFlags(it.flags() & ~Qt.ItemFlag.ItemIsEditable)
        self.table.setItem(row, col, it)

    @staticmethod
    def _centre(widget) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.addWidget(widget)
        hl.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        hl.setContentsMargins(6, 0, 0, 0)
        return w

    def _action_widget(self, row: int) -> QtWidgets.QWidget:
        w = QtWidgets.QWidget()
        hl = QtWidgets.QHBoxLayout(w)
        hl.setContentsMargins(4, 0, 4, 0); hl.setSpacing(4)
        for ico, tip, col, slot in [
            ("👁","View",  "#64748b", lambda _, r=row: self._show_details(r)),
            ("✏","Edit",  "#2563eb", lambda _, r=row: self._on_edit(r)),
            ("🗑","Delete","#dc2626", lambda _, r=row: self._on_delete(r)),
        ]:
            b = QtWidgets.QPushButton(ico); b.setFixedSize(26, 26)
            b.setToolTip(tip)
            b.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
            b.setStyleSheet(f"""
                QPushButton {{
                    background:{col}22; color:{col};
                    border:1px solid {col}44;
                    border-radius:5px; font-size:12px;
                }}
                QPushButton:hover {{ background:{col}44; }}
            """)
            b.clicked.connect(slot); hl.addWidget(b)
        hl.addStretch()
        return w

    # ──────────────────────────────────────────────────────────────────────────
    # RIGHT PANEL — DEPARTMENT DETAILS
    # ──────────────────────────────────────────────────────────────────────────
    def _show_details(self, row: int):
        if row >= len(self._departments):
            return
        (dept_id, name, code, head, employees, status,
         email, phone, location, created_on, description) = self._departments[row]

        while self._dd_vl.count():
            item = self._dd_vl.takeAt(0)
            if item.widget():
                item.widget().deleteLater()

        hdr_lbl = QtWidgets.QLabel("ℹ️  Department Details")
        hdr_lbl.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                              "font-family:'Segoe UI',Arial;")
        self._dd_vl.addWidget(hdr_lbl)

        ico = QtWidgets.QLabel("👥")
        ico.setFixedSize(56, 56)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet(f"background:{_ACCENT};color:{_WHITE};"
                          "border-radius:28px;font-size:24px;")
        self._dd_vl.addWidget(ico, alignment=Qt.AlignmentFlag.AlignCenter)

        tl = QtWidgets.QLabel(name)
        tl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        tl.setWordWrap(True)
        tl.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                         "font-family:'Segoe UI',Arial;")
        self._dd_vl.addWidget(tl)

        sfg, sbg = STATUS_COLOURS.get(status, (_TEXT_MID, "#f3f4f6"))
        st_badge = _Badge(status, sfg, sbg)
        st_row = QtWidgets.QHBoxLayout()
        st_row.setAlignment(Qt.AlignmentFlag.AlignCenter)
        st_row.addWidget(st_badge)
        self._dd_vl.addLayout(st_row)

        dv = QtWidgets.QFrame()
        dv.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        dv.setStyleSheet(f"color:{_BORDER};")
        self._dd_vl.addWidget(dv)

        details = [
            ("📄", "Department Code", code),
            ("👤", "Head of Department", head),
            ("✉️", "Email", email),
            ("📞", "Phone", phone),
            ("📍", "Location", location),
            ("👥", "Employees", str(employees)),
            ("📅", "Created On", created_on),
        ]
        for d_ico, d_lbl, d_val in details:
            row_hl = QtWidgets.QHBoxLayout(); row_hl.setSpacing(6)
            il = QtWidgets.QLabel(d_ico); il.setFixedWidth(18)
            il.setStyleSheet("font-size:11px;")
            vlyt = QtWidgets.QVBoxLayout(); vlyt.setSpacing(0)
            ll = QtWidgets.QLabel(d_lbl)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
            vw = QtWidgets.QLabel(d_val)
            vw.setWordWrap(True)
            vw.setStyleSheet(f"color:{_TEXT_DARK};font-size:11px;font-weight:600;")
            vlyt.addWidget(ll); vlyt.addWidget(vw)
            row_hl.addWidget(il); row_hl.addLayout(vlyt, 1)
            self._dd_vl.addLayout(row_hl)

        desc_lbl = QtWidgets.QLabel("📄  Description")
        desc_lbl.setStyleSheet(f"color:{_TEXT_GREY};font-size:9px;")
        desc_txt = QtWidgets.QLabel(description)
        desc_txt.setWordWrap(True)
        desc_txt.setStyleSheet(f"color:{_TEXT_MID};font-size:10px;"
                               "background:#f9fafb;border-radius:5px;padding:6px;")
        self._dd_vl.addWidget(desc_lbl)
        self._dd_vl.addWidget(desc_txt)

        vfd_btn = QtWidgets.QPushButton("View Full Details")
        vfd_btn.setFixedHeight(34)
        vfd_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        vfd_btn.setStyleSheet(f"""
            QPushButton {{
                background:{_ACCENT}; color:{_WHITE}; border:none;
                border-radius:6px; font-size:12px; font-weight:bold;
            }}
            QPushButton:hover {{ background:#4a60ee; }}
        """)
        vfd_btn.clicked.connect(lambda _, r=row: self._on_view(r))
        self._dd_vl.addWidget(vfd_btn)

    # ──────────────────────────────────────────────────────────────────────────
    # SLOTS
    # ──────────────────────────────────────────────────────────────────────────
    def _apply_filters(self):
        text = self.search_edit.text().lower()
        results = []
        for dept in self._departments:
            dept_id, name, code, head, employees, status = dept[0:6]
            if text and not any(text in v.lower() for v in (name, code, head, status)):
                continue
            results.append(dept)
        self._populate_table(results)

    def _on_row_click(self, row, col):
        self._show_details(row)

    def _on_add_department(self):
        dlg = NewDepartmentDialog(self)
        dlg.department_saved.connect(self._append_department)
        dlg.exec()

    def _append_department(self, data: dict):
        from datetime import date
        new_id = len(self._departments) + 1
        self._departments.insert(0, (
            new_id, data["name"], data["code"], data["head"],
            data["employees"], data["status"], data["email"], data["phone"],
            data["location"], date.today().strftime("%d %b %Y"),
            data["description"] or "No description provided."
        ))
        self._apply_filters()
        QtWidgets.QMessageBox.information(
            self, "Department Added",
            f"✅  '{data['name']}' has been added successfully."
        )

    def _on_view(self, row):
        if row >= len(self._departments): return
        d = self._departments[row]
        QtWidgets.QMessageBox.information(
            self, "Department Details",
            f"<b>{d[1]}</b> ({d[2]})<br>Head: {d[3]}<br>Employees: {d[4]}<br>"
            f"Status: {d[5]}<br>Email: {d[6]}<br>Phone: {d[7]}<br>"
            f"Location: {d[8]}<br>Created: {d[9]}<br><br>{d[10]}"
        )

    def _on_edit(self, row):
        if row >= len(self._departments): return
        d = self._departments[row]
        dlg = NewDepartmentDialog(self, data={
            "name": d[1], "code": d[2], "head": d[3], "employees": d[4],
            "status": d[5], "email": d[6], "phone": d[7],
            "location": d[8], "description": d[10],
        })
        dlg.department_saved.connect(lambda data, r=row: self._save_edit(r, data))
        dlg.exec()

    def _save_edit(self, row, data):
        old = self._departments[row]
        self._departments[row] = (
            old[0], data["name"], data["code"], data["head"],
            data["employees"], data["status"], data["email"], data["phone"],
            data["location"], old[9], data["description"] or old[10]
        )
        self._apply_filters()
        self._show_details(row)

    def _on_delete(self, row):
        if row >= len(self._departments): return
        name = self._departments[row][1]
        reply = QtWidgets.QMessageBox.question(
            self, "Delete Department",
            f"Delete <b>{name}</b>? This cannot be undone.",
            QtWidgets.QMessageBox.StandardButton.Yes |
            QtWidgets.QMessageBox.StandardButton.No,
            QtWidgets.QMessageBox.StandardButton.No,
        )
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            self._departments.pop(row)
            self._apply_filters()

    def _on_filter_menu(self):
        QtWidgets.QMessageBox.information(
            self, "Advanced Filters",
            "Advanced filter panel will be available in the next sprint."
        )

    def _on_export(self):
        QtWidgets.QMessageBox.information(
            self, "Export",
            "Export functionality will be connected in the next sprint."
        )
