# Form implementation generated from reading ui file 'Settings_Page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt

# ── Shared palette ─────────────────────────────────────────────────────────
_NAVY      = "#0d1b3e"
_ACCENT    = "#5870ff"
_BG        = "#f0f2f5"
_WHITE     = "#ffffff"
_BORDER    = "#e5e7eb"
_TEXT_DARK = "#1a1a2e"
_TEXT_GREY = "#6b7280"
_TEXT_MID  = "#374151"


# ── Reusable style helpers ──────────────────────────────────────────────────
def _field_style() -> str:
    return f"""
        QLineEdit, QComboBox, QSpinBox, QDateEdit {{
            border: 1px solid {_BORDER};
            border-radius: 6px;
            padding: 7px 10px;
            font-size: 12px;
            color: {_TEXT_DARK};
            background: #f9fafb;
            font-family: 'Segoe UI', Arial;
        }}
        QLineEdit:focus, QComboBox:focus, QSpinBox:focus {{
            border: 1.5px solid {_ACCENT};
            background: {_WHITE};
        }}
        QLineEdit:read-only {{
            background: #f3f4f6;
            color: {_TEXT_GREY};
        }}
        QComboBox::drop-down {{
            border: none; width: 22px;
        }}
        QSpinBox::up-button, QSpinBox::down-button {{
            width: 16px;
        }}
    """


def _section_title(text: str, icon: str = "") -> QtWidgets.QLabel:
    lbl = QtWidgets.QLabel(f"{icon}  {text}" if icon else text)
    lbl.setStyleSheet(f"""
        color: {_TEXT_DARK};
        font-size: 14px;
        font-weight: bold;
        font-family: 'Segoe UI', Arial;
    """)
    return lbl


def _field_label(text: str) -> QtWidgets.QLabel:
    lbl = QtWidgets.QLabel(text)
    lbl.setStyleSheet(f"color: {_TEXT_GREY}; font-size: 11px;")
    return lbl


def _card(parent=None) -> QtWidgets.QFrame:
    f = QtWidgets.QFrame(parent)
    f.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
    f.setStyleSheet(f"""
        QFrame {{
            background: {_WHITE};
            border: 1px solid {_BORDER};
            border-radius: 10px;
        }}
    """)
    return f


def _badge(text: str, fg: str, bg: str) -> QtWidgets.QLabel:
    lbl = QtWidgets.QLabel(text)
    lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
    lbl.setFixedHeight(20)
    lbl.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                      QtWidgets.QSizePolicy.Policy.Fixed)
    lbl.setStyleSheet(f"""
        QLabel {{
            color: {fg}; background: {bg};
            border-radius: 9px; padding: 0 9px;
            font-size: 10px; font-weight: 700;
            font-family: 'Segoe UI', Arial;
        }}
    """)
    return lbl


# ==============================================================================
# QUICK-NAV CATEGORY CARD  (top row)
# ==============================================================================
class _CategoryCard(QtWidgets.QFrame):
    def __init__(self, icon: str, icon_bg: str, title: str,
                 subtitle: str, parent=None):
        super().__init__(parent)
        self.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        self.setStyleSheet(f"""
            QFrame {{
                background: {_WHITE};
                border: 1px solid {_BORDER};
                border-radius: 10px;
            }}
            QFrame:hover {{
                border: 1.5px solid {_ACCENT};
                background: #fafbff;
            }}
        """)
        hl = QtWidgets.QHBoxLayout(self)
        hl.setContentsMargins(14, 12, 14, 12); hl.setSpacing(12)

        il = QtWidgets.QLabel(icon)
        il.setFixedSize(38, 38)
        il.setAlignment(Qt.AlignmentFlag.AlignCenter)
        il.setStyleSheet(f"background:{icon_bg};border-radius:19px;font-size:16px;")

        vl = QtWidgets.QVBoxLayout(); vl.setSpacing(2)
        t = QtWidgets.QLabel(title)
        t.setStyleSheet(f"color:{_TEXT_DARK};font-size:12px;font-weight:bold;"
                        "font-family:'Segoe UI',Arial;")
        s = QtWidgets.QLabel(subtitle)
        s.setWordWrap(True)
        s.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
        vl.addWidget(t); vl.addWidget(s)

        hl.addWidget(il); hl.addLayout(vl)


# ==============================================================================
# SETTINGS PAGE
# ==============================================================================
class SettingsPage(QtWidgets.QWidget):
    """
    Full Settings page — slots into stackedWidget index 11.

    Layout
    ──────
    Left scroll area
      • Page header
      • 5 quick-nav category cards
      • General Settings section (org name, tagline, date format,
                                   time format, language, timezone)
      • System Appearance section (theme, primary colour, sidebar style)
      • Email Settings section (SMTP host/port/encryption, email/user/password)
      • Other Settings section  (checkboxes + spinboxes)
      • Reset / Cancel / Save Changes buttons
    Right panel (fixed 268px)
      • System Information card
      • Security Summary card
      • System Backup card
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("Settings_Page")
        self.setStyleSheet(f"background:{_BG};")
        self._build_ui()

    # ──────────────────────────────────────────────────────────────────────────
    def _build_ui(self):
        outer = QtWidgets.QHBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0); outer.setSpacing(0)

        # ════════════════════ LEFT SCROLL AREA ═══════════════════════════════
        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        scroll.setStyleSheet("background:transparent;border:none;")

        lc = QtWidgets.QWidget(); lc.setStyleSheet(f"background:{_BG};")
        lv = QtWidgets.QVBoxLayout(lc)
        lv.setContentsMargins(22, 18, 14, 20); lv.setSpacing(16)

        # ── Page header ───────────────────────────────────────────────
        hdr = QtWidgets.QHBoxLayout(); hdr.setSpacing(12)
        ico = QtWidgets.QLabel("⚙️")
        ico.setFixedSize(44, 44)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet("background:#eff0ff;border-radius:22px;font-size:20px;")
        tvl = QtWidgets.QVBoxLayout(); tvl.setSpacing(2)
        pg_t = QtWidgets.QLabel("Settings")
        pg_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:20px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        pg_s = QtWidgets.QLabel("Configure system preferences and manage application settings.")
        pg_s.setStyleSheet(f"color:{_TEXT_GREY};font-size:11px;")
        tvl.addWidget(pg_t); tvl.addWidget(pg_s)
        hdr.addWidget(ico); hdr.addLayout(tvl); hdr.addStretch()
        lv.addLayout(hdr)

        # ── Category cards (top row) ──────────────────────────────────
        cats_hl = QtWidgets.QHBoxLayout(); cats_hl.setSpacing(10)
        for icon, ibg, title, sub in [
            ("⚙️","#eff0ff","System Settings",      "Configure general\nsystem preferences"),
            ("👤","#ede9fe","User Preferences",     "Manage your personal\npreferences"),
            ("🔒","#dcfce7","Security Settings",    "Manage security and\naccess control"),
            ("🔔","#fef3c7","Notification Settings","Configure system\nnotifications"),
            ("☁️","#e0f2fe","Backup & Restore",     "Manage backups and\nsystem restore"),
        ]:
            cats_hl.addWidget(_CategoryCard(icon, ibg, title, sub))
        lv.addLayout(cats_hl)

        # ── General Settings ──────────────────────────────────────────
        gen = _card(); gen.setStyleSheet(gen.styleSheet())
        gen_vl = QtWidgets.QVBoxLayout(gen)
        gen_vl.setContentsMargins(20, 16, 20, 18); gen_vl.setSpacing(14)
        gen_vl.addWidget(_section_title("General Settings", "⚙️"))

        self.setStyleSheet(self.styleSheet() + _field_style())

        # Row 1 — org name | time format
        r1 = QtWidgets.QHBoxLayout(); r1.setSpacing(20)
        c1 = self._field_col("Organization Name")
        self.org_name = QtWidgets.QLineEdit("Operations Management System")
        c1.addWidget(self.org_name)
        c2 = self._field_col("Time Format")
        self.time_fmt = QtWidgets.QComboBox()
        self.time_fmt.addItems(["12 Hour (02:30 PM)", "24 Hour (14:30)"])
        c2.addWidget(self.time_fmt)
        r1.addLayout(c1); r1.addLayout(c2)
        gen_vl.addLayout(r1)

        # Row 2 — org tagline | language
        r2 = QtWidgets.QHBoxLayout(); r2.setSpacing(20)
        c3 = self._field_col("Organization Tagline")
        self.org_tagline = QtWidgets.QLineEdit("Excellence in Operations and Management")
        c3.addWidget(self.org_tagline)
        c4 = self._field_col("Language")
        self.language = QtWidgets.QComboBox()
        self.language.addItems(["English (United States)", "English (United Kingdom)",
                                "Swahili (Kenya)", "French"])
        c4.addWidget(self.language)
        r2.addLayout(c3); r2.addLayout(c4)
        gen_vl.addLayout(r2)

        # Row 3 — date format | timezone
        r3 = QtWidgets.QHBoxLayout(); r3.setSpacing(20)
        c5 = self._field_col("Date Format")
        self.date_fmt = QtWidgets.QComboBox()
        self.date_fmt.addItems(["DD MMM YYYY (22 Jun 2025)",
                                "MM/DD/YYYY", "YYYY-MM-DD",
                                "DD/MM/YYYY"])
        c5.addWidget(self.date_fmt)
        c6 = self._field_col("Timezone")
        self.timezone = QtWidgets.QComboBox()
        self.timezone.addItems(["(GMT +03:00) Nairobi, Kenya",
                                "(GMT +00:00) UTC",
                                "(GMT +01:00) Lagos, Nigeria",
                                "(GMT +02:00) Cairo, Egypt"])
        c6.addWidget(self.timezone)
        r3.addLayout(c5); r3.addLayout(c6)
        gen_vl.addLayout(r3)
        lv.addWidget(gen)

        # ── System Appearance ─────────────────────────────────────────
        app_card = _card()
        app_vl = QtWidgets.QVBoxLayout(app_card)
        app_vl.setContentsMargins(20, 16, 20, 18); app_vl.setSpacing(14)
        app_vl.addWidget(_section_title("System Appearance", "🎨"))

        # Row 1 — theme | primary colour
        ra1 = QtWidgets.QHBoxLayout(); ra1.setSpacing(20)
        ca1 = self._field_col("Theme")
        self.theme_combo = QtWidgets.QComboBox()
        self.theme_combo.addItems(["Light", "Dark", "System Default"])
        ca1.addWidget(self.theme_combo)

        ca2 = self._field_col("Primary Color")
        color_hl = QtWidgets.QHBoxLayout(); color_hl.setSpacing(8)
        self.color_swatch = QtWidgets.QLabel()
        self.color_swatch.setFixedSize(28, 28)
        self.color_swatch.setStyleSheet(f"""
            QLabel {{
                background:#2563EB;
                border-radius:5px;
                border:1px solid {_BORDER};
            }}
        """)
        self.color_edit = QtWidgets.QLineEdit("#2563EB")
        color_pick_btn = QtWidgets.QPushButton("Pick")
        color_pick_btn.setFixedSize(46, 32)
        color_pick_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        color_pick_btn.setStyleSheet(f"""
            QPushButton {{
                background:{_WHITE}; border:1px solid {_BORDER};
                border-radius:5px; font-size:11px; color:{_TEXT_MID};
            }}
            QPushButton:hover {{ background:#f9fafb; }}
        """)
        color_pick_btn.clicked.connect(self._on_pick_color)
        color_hl.addWidget(self.color_swatch)
        color_hl.addWidget(self.color_edit, stretch=1)
        color_hl.addWidget(color_pick_btn)
        ca2.addLayout(color_hl)

        ra1.addLayout(ca1); ra1.addLayout(ca2)
        app_vl.addLayout(ra1)

        # Row 2 — sidebar style
        ra2 = QtWidgets.QHBoxLayout(); ra2.setSpacing(20)
        ca3 = self._field_col("Sidebar Style")
        self.sidebar_style = QtWidgets.QComboBox()
        self.sidebar_style.addItems(["Default (Compact)", "Wide", "Mini Icons Only"])
        ca3.addWidget(self.sidebar_style)
        ra2.addLayout(ca3); ra2.addStretch()
        app_vl.addLayout(ra2)
        lv.addWidget(app_card)

        # ── Email Settings ────────────────────────────────────────────
        email_card = _card()
        em_vl = QtWidgets.QVBoxLayout(email_card)
        em_vl.setContentsMargins(20, 16, 20, 18); em_vl.setSpacing(14)
        em_vl.addWidget(_section_title("Email Settings", "✉️"))

        # Row 1 — SMTP host | email address
        re1 = QtWidgets.QHBoxLayout(); re1.setSpacing(20)
        ce1 = self._field_col("SMTP Host")
        self.smtp_host = QtWidgets.QLineEdit("smtp.omssystem.com")
        ce1.addWidget(self.smtp_host)
        ce2 = self._field_col("Email Address")
        self.smtp_email = QtWidgets.QLineEdit("no-reply@omssystem.com")
        ce2.addWidget(self.smtp_email)
        re1.addLayout(ce1); re1.addLayout(ce2)
        em_vl.addLayout(re1)

        # Row 2 — SMTP port | username
        re2 = QtWidgets.QHBoxLayout(); re2.setSpacing(20)
        ce3 = self._field_col("SMTP Port")
        self.smtp_port = QtWidgets.QSpinBox()
        self.smtp_port.setRange(1, 65535); self.smtp_port.setValue(587)
        self.smtp_port.setFixedHeight(36)
        ce3.addWidget(self.smtp_port)
        ce4 = self._field_col("Username")
        self.smtp_user = QtWidgets.QLineEdit("no-reply@omssystem.com")
        ce4.addWidget(self.smtp_user)
        re2.addLayout(ce3); re2.addLayout(ce4)
        em_vl.addLayout(re2)

        # Row 3 — encryption | password | test button
        re3 = QtWidgets.QHBoxLayout(); re3.setSpacing(20)
        ce5 = self._field_col("Encryption")
        self.smtp_enc = QtWidgets.QComboBox()
        self.smtp_enc.addItems(["TLS", "SSL", "None"])
        ce5.addWidget(self.smtp_enc)

        ce6 = self._field_col("Password")
        pwd_hl = QtWidgets.QHBoxLayout(); pwd_hl.setSpacing(6)
        self.smtp_pwd = QtWidgets.QLineEdit("••••••••••••")
        self.smtp_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        eye_btn = QtWidgets.QPushButton("👁")
        eye_btn.setFixedSize(32, 32)
        eye_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        eye_btn.setCheckable(True)
        eye_btn.setStyleSheet(f"""
            QPushButton {{
                background:transparent; border:none;
                font-size:14px; color:{_TEXT_GREY};
            }}
        """)
        eye_btn.toggled.connect(lambda checked: self.smtp_pwd.setEchoMode(
            QtWidgets.QLineEdit.EchoMode.Normal if checked
            else QtWidgets.QLineEdit.EchoMode.Password))
        pwd_hl.addWidget(self.smtp_pwd, stretch=1)
        pwd_hl.addWidget(eye_btn)
        ce6.addLayout(pwd_hl)

        re3.addLayout(ce5); re3.addLayout(ce6)

        # Test connection button
        test_btn = QtWidgets.QPushButton("  ✈  Test Connection")
        test_btn.setFixedHeight(36)
        test_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        test_btn.setStyleSheet(f"""
            QPushButton {{
                background:{_WHITE}; color:{_TEXT_MID};
                border:1px solid {_BORDER}; border-radius:6px;
                font-size:12px; font-family:'Segoe UI',Arial;
                padding:0 14px;
            }}
            QPushButton:hover {{ background:#f9fafb; }}
        """)
        test_btn.clicked.connect(self._on_test_connection)
        re3_outer = QtWidgets.QHBoxLayout(); re3_outer.setSpacing(12)
        re3_outer.addLayout(re3, stretch=1)
        re3_outer.addWidget(test_btn, alignment=Qt.AlignmentFlag.AlignBottom)
        em_vl.addLayout(re3_outer)
        lv.addWidget(email_card)

        # ── Other Settings ────────────────────────────────────────────
        oth_card = _card()
        oth_vl = QtWidgets.QVBoxLayout(oth_card)
        oth_vl.setContentsMargins(20, 16, 20, 18); oth_vl.setSpacing(14)
        oth_vl.addWidget(_section_title("Other Settings", "🔧"))

        chk_grid = QtWidgets.QGridLayout(); chk_grid.setSpacing(12)

        # Left checkboxes
        self.chk_2fa   = self._checkbox("Enable Two-Factor Authentication", True)
        self.chk_self  = self._checkbox("Allow User Self Registration",     False)
        self.chk_audit = self._checkbox("Enable Audit Logging",             True)
        self.chk_maint = self._checkbox("Enable System Maintenance Mode",   False)

        # Right checkboxes
        self.chk_email  = self._checkbox("Send Email Notifications", True)
        self.chk_export = self._checkbox("Enable Data Export",       True)

        chk_grid.addWidget(self.chk_2fa,   0, 0)
        chk_grid.addWidget(self.chk_email,  0, 1)
        chk_grid.addWidget(self.chk_self,  1, 0)
        chk_grid.addWidget(self.chk_export, 1, 1)
        chk_grid.addWidget(self.chk_audit, 2, 0)
        chk_grid.addWidget(self.chk_maint, 3, 0)
        oth_vl.addLayout(chk_grid)

        # Spinboxes row
        spin_hl = QtWidgets.QHBoxLayout(); spin_hl.setSpacing(40)
        sc1 = self._field_col("Auto Logout (Minutes)")
        self.auto_logout = QtWidgets.QSpinBox()
        self.auto_logout.setRange(1, 480); self.auto_logout.setValue(30)
        self.auto_logout.setFixedHeight(36); self.auto_logout.setFixedWidth(120)
        sc1.addWidget(self.auto_logout)
        sc2 = self._field_col("Items Per Page")
        self.items_per_page = QtWidgets.QSpinBox()
        self.items_per_page.setRange(5, 100); self.items_per_page.setValue(10)
        self.items_per_page.setFixedHeight(36); self.items_per_page.setFixedWidth(120)
        sc2.addWidget(self.items_per_page)
        spin_hl.addLayout(sc1); spin_hl.addLayout(sc2); spin_hl.addStretch()
        oth_vl.addLayout(spin_hl)
        lv.addWidget(oth_card)

        # ── Bottom action buttons ─────────────────────────────────────
        btn_hl = QtWidgets.QHBoxLayout(); btn_hl.setSpacing(10)
        reset_btn  = self._outline_btn("Reset to Defaults")
        cancel_btn = self._outline_btn("Cancel")
        save_btn   = self._primary_btn("💾  Save Changes")
        reset_btn.clicked.connect(self._on_reset)
        cancel_btn.clicked.connect(self._on_cancel)
        save_btn.clicked.connect(self._on_save)
        btn_hl.addWidget(reset_btn); btn_hl.addStretch()
        btn_hl.addWidget(cancel_btn); btn_hl.addWidget(save_btn)
        lv.addLayout(btn_hl)
        lv.addStretch()

        scroll.setWidget(lc)
        outer.addWidget(scroll, stretch=1)

        # ════════════════════ RIGHT PANEL ════════════════════════════════════
        rp = QtWidgets.QWidget()
        rp.setFixedWidth(268)
        rp.setStyleSheet(f"background:{_BG};border-left:1px solid {_BORDER};")

        rp_scroll = QtWidgets.QScrollArea()
        rp_scroll.setWidgetResizable(True)
        rp_scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        rp_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        rp_scroll.setStyleSheet("background:transparent;border:none;")

        ri = QtWidgets.QWidget(); ri.setStyleSheet(f"background:{_BG};")
        rv = QtWidgets.QVBoxLayout(ri)
        rv.setContentsMargins(10, 16, 10, 16); rv.setSpacing(12)

        # ── System Information card ───────────────────────────────────
        si = _card()
        si_vl = QtWidgets.QVBoxLayout(si)
        si_vl.setContentsMargins(14, 14, 14, 14); si_vl.setSpacing(10)
        si_hdr = QtWidgets.QHBoxLayout()
        si_ico = QtWidgets.QLabel("ℹ️"); si_ico.setStyleSheet("font-size:14px;")
        si_t = QtWidgets.QLabel("System Information")
        si_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        si_hdr.addWidget(si_ico); si_hdr.addWidget(si_t); si_hdr.addStretch()
        si_vl.addLayout(si_hdr)

        # divider
        dv = QtWidgets.QFrame()
        dv.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        dv.setStyleSheet(f"color:{_BORDER};")
        si_vl.addWidget(dv)

        sys_info = [
            ("System Version",   "1.0.0",                  None),
            ("Database Version", "5.7.34",                 None),
            ("Last Updated",     "18 May 2025 02:40 PM",   None),
            ("System Status",    "Online",                  ("Online",  "#15803d","#dcfce7")),
            ("Uptime",           "5 days, 14 hours, 32 mins",None),
            ("Server",           "OMS-Server-01",           None),
        ]
        for label, value, badge_data in sys_info:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            ll = QtWidgets.QLabel(label)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
            ll.setFixedWidth(115)
            if badge_data:
                txt, fg, bg = badge_data
                vw = _badge(txt, fg, bg)
            else:
                vw = QtWidgets.QLabel(value)
                vw.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:600;")
            row.addWidget(ll); row.addWidget(vw); row.addStretch()
            si_vl.addLayout(row)
        rv.addWidget(si)

        # ── Security Summary card ─────────────────────────────────────
        ss = _card()
        ss_vl = QtWidgets.QVBoxLayout(ss)
        ss_vl.setContentsMargins(14, 14, 14, 14); ss_vl.setSpacing(10)
        ss_hdr = QtWidgets.QHBoxLayout()
        ss_ico = QtWidgets.QLabel("🔒"); ss_ico.setStyleSheet("font-size:14px;")
        ss_t = QtWidgets.QLabel("Security Summary")
        ss_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        ss_hdr.addWidget(ss_ico); ss_hdr.addWidget(ss_t); ss_hdr.addStretch()
        ss_vl.addLayout(ss_hdr)

        dv2 = QtWidgets.QFrame()
        dv2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        dv2.setStyleSheet(f"color:{_BORDER};")
        ss_vl.addWidget(dv2)

        sec_data = [
            ("Password Policy",         ("Strong",  "#15803d", "#dcfce7")),
            ("Two-Factor Authentication",("Enabled", "#15803d", "#dcfce7")),
            ("Failed Login Attempts",    ("0",       "#374151", "#f3f4f6")),
        ]
        for label, badge_d in sec_data:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            ll = QtWidgets.QLabel(label)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
            txt, fg, bg = badge_d
            vw = _badge(txt, fg, bg)
            row.addWidget(ll); row.addStretch(); row.addWidget(vw)
            ss_vl.addLayout(row)

        # Last password change
        lpc_row = QtWidgets.QHBoxLayout()
        lpc_l = QtWidgets.QLabel("Last Password Change")
        lpc_l.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
        lpc_v = QtWidgets.QLabel("12 May 2025")
        lpc_v.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:bold;")
        lpc_row.addWidget(lpc_l); lpc_row.addStretch(); lpc_row.addWidget(lpc_v)
        ss_vl.addLayout(lpc_row)

        # Change Password button
        cp_btn = QtWidgets.QPushButton("🔑  Change Password")
        cp_btn.setFixedHeight(34)
        cp_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        cp_btn.setStyleSheet(f"""
            QPushButton {{
                background:{_WHITE}; color:{_TEXT_MID};
                border:1px solid {_BORDER}; border-radius:6px;
                font-size:11px; font-family:'Segoe UI',Arial;
            }}
            QPushButton:hover {{ background:#f9fafb; }}
        """)
        cp_btn.clicked.connect(self._on_change_password)
        ss_vl.addWidget(cp_btn)
        rv.addWidget(ss)

        # ── System Backup card ────────────────────────────────────────
        sb = _card()
        sb_vl = QtWidgets.QVBoxLayout(sb)
        sb_vl.setContentsMargins(14, 14, 14, 14); sb_vl.setSpacing(10)
        sb_hdr = QtWidgets.QHBoxLayout()
        sb_ico = QtWidgets.QLabel("☁️"); sb_ico.setStyleSheet("font-size:14px;")
        sb_t = QtWidgets.QLabel("System Backup")
        sb_t.setStyleSheet(f"color:{_TEXT_DARK};font-size:13px;font-weight:bold;"
                           "font-family:'Segoe UI',Arial;")
        sb_hdr.addWidget(sb_ico); sb_hdr.addWidget(sb_t); sb_hdr.addStretch()
        sb_vl.addLayout(sb_hdr)

        dv3 = QtWidgets.QFrame()
        dv3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        dv3.setStyleSheet(f"color:{_BORDER};")
        sb_vl.addWidget(dv3)

        for lbl_t, val_t, badge_d in [
            ("Last Backup",    "17 May 2025 11:30 PM", None),
            ("Next Backup",    "18 May 2025 11:30 PM", None),
            ("Backup Status",  "",("Successful","#15803d","#dcfce7")),
        ]:
            row = QtWidgets.QHBoxLayout(); row.setSpacing(6)
            ll = QtWidgets.QLabel(lbl_t)
            ll.setStyleSheet(f"color:{_TEXT_GREY};font-size:10px;")
            if badge_d:
                txt, fg, bg = badge_d
                vw = _badge(txt, fg, bg)
            else:
                vw = QtWidgets.QLabel(val_t)
                vw.setStyleSheet(f"color:{_TEXT_DARK};font-size:10px;font-weight:600;")
            row.addWidget(ll); row.addStretch(); row.addWidget(vw)
            sb_vl.addLayout(row)

        bn_btn = QtWidgets.QPushButton("☁️  Backup Now")
        bn_btn.setFixedHeight(34)
        bn_btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        bn_btn.setStyleSheet(f"""
            QPushButton {{
                background:{_ACCENT}; color:{_WHITE}; border:none;
                border-radius:6px; font-size:11px; font-weight:bold;
                font-family:'Segoe UI',Arial;
            }}
            QPushButton:hover {{ background:#4a60ee; }}
        """)
        bn_btn.clicked.connect(self._on_backup_now)
        sb_vl.addWidget(bn_btn)
        rv.addWidget(sb)
        rv.addStretch()

        rp_scroll.setWidget(ri)
        rp_vl = QtWidgets.QVBoxLayout(rp)
        rp_vl.setContentsMargins(0, 0, 0, 0)
        rp_vl.addWidget(rp_scroll)
        outer.addWidget(rp)

    # ──────────────────────────────────────────────────────────────────────────
    # HELPERS
    # ──────────────────────────────────────────────────────────────────────────
    @staticmethod
    def _field_col(label: str) -> QtWidgets.QVBoxLayout:
        vl = QtWidgets.QVBoxLayout(); vl.setSpacing(5)
        vl.addWidget(_field_label(label))
        return vl

    @staticmethod
    def _checkbox(text: str, checked: bool) -> QtWidgets.QCheckBox:
        chk = QtWidgets.QCheckBox(text)
        chk.setChecked(checked)
        chk.setStyleSheet(f"""
            QCheckBox {{
                color: {_TEXT_MID};
                font-size: 12px;
                font-family: 'Segoe UI', Arial;
                spacing: 8px;
            }}
            QCheckBox::indicator {{
                width: 16px; height: 16px;
                border: 1.5px solid {_BORDER};
                border-radius: 3px;
                background: {_WHITE};
            }}
            QCheckBox::indicator:checked {{
                background: {_ACCENT};
                border-color: {_ACCENT};
                image: none;
            }}
        """)
        return chk

    @staticmethod
    def _outline_btn(text: str) -> QtWidgets.QPushButton:
        btn = QtWidgets.QPushButton(text)
        btn.setFixedHeight(36)
        btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        btn.setStyleSheet(f"""
            QPushButton {{
                background:{_WHITE}; color:{_TEXT_MID};
                border:1px solid {_BORDER}; border-radius:6px;
                padding:0 18px; font-size:12px;
                font-family:'Segoe UI',Arial;
            }}
            QPushButton:hover {{ background:#f9fafb; }}
        """)
        return btn

    @staticmethod
    def _primary_btn(text: str) -> QtWidgets.QPushButton:
        btn = QtWidgets.QPushButton(text)
        btn.setFixedHeight(36)
        btn.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        btn.setStyleSheet(f"""
            QPushButton {{
                background:{_ACCENT}; color:{_WHITE}; border:none;
                border-radius:6px; padding:0 20px;
                font-size:12px; font-weight:bold;
                font-family:'Segoe UI',Arial;
            }}
            QPushButton:hover {{ background:#4a60ee; }}
        """)
        return btn

    # ──────────────────────────────────────────────────────────────────────────
    # SLOTS
    # ──────────────────────────────────────────────────────────────────────────
    def _on_pick_color(self):
        colour = QtWidgets.QColorDialog.getColor(
            QtGui.QColor(self.color_edit.text()), self, "Select Primary Color"
        )
        if colour.isValid():
            hex_col = colour.name().upper()
            self.color_edit.setText(hex_col)
            self.color_swatch.setStyleSheet(f"""
                QLabel {{
                    background:{hex_col};
                    border-radius:5px;
                    border:1px solid {_BORDER};
                }}
            """)

    def _on_test_connection(self):
        QtWidgets.QMessageBox.information(
            self, "Test Connection",
            "✅  SMTP connection test successful!\n"
            "Server responded at smtp.omssystem.com:587 (TLS)"
        )

    def _on_save(self):
        QtWidgets.QMessageBox.information(
            self, "Settings Saved",
            "✅  All settings have been saved successfully."
        )

    def _on_cancel(self):
        reply = QtWidgets.QMessageBox.question(
            self, "Discard Changes",
            "Are you sure you want to discard unsaved changes?",
            QtWidgets.QMessageBox.StandardButton.Yes |
            QtWidgets.QMessageBox.StandardButton.No,
            QtWidgets.QMessageBox.StandardButton.No,
        )
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            self._reset_fields()

    def _on_reset(self):
        reply = QtWidgets.QMessageBox.question(
            self, "Reset to Defaults",
            "Are you sure you want to reset ALL settings to their default values?\n"
            "This action cannot be undone.",
            QtWidgets.QMessageBox.StandardButton.Yes |
            QtWidgets.QMessageBox.StandardButton.No,
            QtWidgets.QMessageBox.StandardButton.No,
        )
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            self._reset_fields()
            QtWidgets.QMessageBox.information(
                self, "Reset Complete",
                "✅  Settings have been reset to defaults."
            )

    def _reset_fields(self):
        self.org_name.setText("Operations Management System")
        self.org_tagline.setText("Excellence in Operations and Management")
        self.time_fmt.setCurrentIndex(0)
        self.language.setCurrentIndex(0)
        self.date_fmt.setCurrentIndex(0)
        self.timezone.setCurrentIndex(0)
        self.theme_combo.setCurrentIndex(0)
        self.color_edit.setText("#2563EB")
        self.color_swatch.setStyleSheet(f"""
            QLabel {{
                background:#2563EB;
                border-radius:5px;
                border:1px solid {_BORDER};
            }}
        """)
        self.sidebar_style.setCurrentIndex(0)
        self.smtp_host.setText("smtp.omssystem.com")
        self.smtp_email.setText("no-reply@omssystem.com")
        self.smtp_port.setValue(587)
        self.smtp_user.setText("no-reply@omssystem.com")
        self.smtp_enc.setCurrentIndex(0)
        self.chk_2fa.setChecked(True)
        self.chk_self.setChecked(False)
        self.chk_audit.setChecked(True)
        self.chk_maint.setChecked(False)
        self.chk_email.setChecked(True)
        self.chk_export.setChecked(True)
        self.auto_logout.setValue(30)
        self.items_per_page.setValue(10)

    def _on_change_password(self):
        dlg = _ChangePasswordDialog(self)
        dlg.exec()

    def _on_backup_now(self):
        QtWidgets.QMessageBox.information(
            self, "Backup Started",
            "☁️  System backup has been initiated.\n"
            "You will be notified when the backup is complete."
        )


# ==============================================================================
# CHANGE PASSWORD DIALOG
# ==============================================================================
class _ChangePasswordDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Change Password")
        self.setModal(True)
        self.setFixedSize(420, 340)
        self.setStyleSheet(f"""
            QDialog {{ background:{_WHITE}; font-family:'Segoe UI',Arial; }}
            QLabel#hdrTitle {{ color:{_TEXT_DARK}; font-size:15px; font-weight:bold; }}
            QLabel#hdrSub   {{ color:{_TEXT_GREY}; font-size:12px; }}
            QLabel#fldLbl   {{ color:{_TEXT_MID};  font-size:12px; font-weight:600; }}
            QLineEdit {{
                border:1px solid {_BORDER}; border-radius:6px;
                padding:8px 10px; font-size:12px;
                color:{_TEXT_DARK}; background:#f9fafb;
            }}
            QLineEdit:focus {{ border:1.5px solid {_ACCENT}; background:{_WHITE}; }}
            QPushButton#cancelBtn {{
                background:{_WHITE}; border:1px solid {_BORDER};
                border-radius:6px; padding:8px 22px;
                font-size:12px; color:{_TEXT_MID};
            }}
            QPushButton#cancelBtn:hover {{ background:#f9fafb; }}
            QPushButton#saveBtn {{
                background:{_ACCENT}; border:none; border-radius:6px;
                padding:8px 26px; font-size:12px;
                font-weight:bold; color:{_WHITE};
            }}
            QPushButton#saveBtn:hover {{ background:#4a60ee; }}
            QFrame#div {{ border:none; border-top:1px solid {_BORDER}; }}
        """)

        root = QtWidgets.QVBoxLayout(self)
        root.setContentsMargins(24, 20, 24, 18); root.setSpacing(0)

        hhl = QtWidgets.QHBoxLayout()
        ico = QtWidgets.QLabel("🔑")
        ico.setFixedSize(38, 38)
        ico.setAlignment(Qt.AlignmentFlag.AlignCenter)
        ico.setStyleSheet("background:#eff0ff;border-radius:19px;font-size:16px;")
        hvl = QtWidgets.QVBoxLayout(); hvl.setSpacing(2)
        ht = QtWidgets.QLabel("Change Password"); ht.setObjectName("hdrTitle")
        hs = QtWidgets.QLabel("Enter your current and new password.")
        hs.setObjectName("hdrSub")
        hvl.addWidget(ht); hvl.addWidget(hs)
        hhl.addWidget(ico); hhl.addSpacing(10)
        hhl.addLayout(hvl); hhl.addStretch()
        root.addLayout(hhl); root.addSpacing(14)

        d0 = QtWidgets.QFrame(); d0.setObjectName("div"); d0.setFixedHeight(1)
        root.addWidget(d0); root.addSpacing(14)

        def lbl(t):
            l = QtWidgets.QLabel(t); l.setObjectName("fldLbl"); return l

        form = QtWidgets.QFormLayout()
        form.setVerticalSpacing(12); form.setHorizontalSpacing(14)
        form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft)

        self.cur_pwd  = QtWidgets.QLineEdit(); self.cur_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.new_pwd  = QtWidgets.QLineEdit(); self.new_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.conf_pwd = QtWidgets.QLineEdit(); self.conf_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        form.addRow(lbl("Current Password *"), self.cur_pwd)
        form.addRow(lbl("New Password *"),     self.new_pwd)
        form.addRow(lbl("Confirm Password *"), self.conf_pwd)
        root.addLayout(form); root.addStretch()

        self.err_lbl = QtWidgets.QLabel("")
        self.err_lbl.setStyleSheet("color:#b91c1c;font-size:11px;")
        self.err_lbl.setVisible(False)
        root.addWidget(self.err_lbl); root.addSpacing(8)

        d1 = QtWidgets.QFrame(); d1.setObjectName("div"); d1.setFixedHeight(1)
        root.addWidget(d1); root.addSpacing(12)

        bhl = QtWidgets.QHBoxLayout(); bhl.addStretch()
        cb = QtWidgets.QPushButton("Cancel"); cb.setObjectName("cancelBtn")
        cb.setFixedHeight(36)
        cb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        cb.clicked.connect(self.reject)
        sb = QtWidgets.QPushButton("🔑  Update Password"); sb.setObjectName("saveBtn")
        sb.setFixedHeight(36)
        sb.setCursor(QtGui.QCursor(Qt.CursorShape.PointingHandCursor))
        sb.clicked.connect(self._on_save)
        bhl.addWidget(cb); bhl.addSpacing(8); bhl.addWidget(sb)
        root.addLayout(bhl)

    def _on_save(self):
        errs = []
        if not self.cur_pwd.text():  errs.append("Current password required.")
        if len(self.new_pwd.text()) < 8: errs.append("New password must be ≥ 8 chars.")
        if self.new_pwd.text() != self.conf_pwd.text(): errs.append("Passwords do not match.")
        if errs:
            self.err_lbl.setText("⚠  " + "  •  ".join(errs))
            self.err_lbl.setVisible(True); return
        self.err_lbl.setVisible(False)
        QtWidgets.QMessageBox.information(
            self, "Password Updated", "✅  Your password has been updated successfully.")
        self.accept()